import type { GameDef, GameId } from "./games-core";

export const TITLE_STRIP: { id: GameId; label: string }[] = [
  { id: "pokemon-vgc", label: "VGC" },
  { id: "pokemon-tcg", label: "PTCG" },
  { id: "one-piece", label: "OP" },
  { id: "yugioh", label: "YGO" },
  { id: "mtg", label: "MTG" },
  { id: "lorcana", label: "Lorcana" },
  { id: "swu", label: "SWU" },
  { id: "riftbound", label: "Rift" },
];

export const GAME_LIST: GameDef[] = [
  {
    id: "pokemon-vgc",
    name: "Pokémon VGC · Masters",
    short: "VGC M",
    category: "VGC",
    resource: { kind: "pips", label: "Pokemon remaining", shortLabel: "PKMN", min: 0, max: 6, start: 6, step: 1, invertWin: true, pips: true, pipStyle: "team" },
    extraLabel: "Team",
    extraPlaceholder: "Sun · Balance · Rain",
    scoreLabel: "Games",
    defaultBestOf: 3,
    defaultScorebug: "play",
    formats: [
      { id: "reg-i", label: "VGC 2026 Regulation I" },
      { id: "reg-h", label: "VGC 2026 Regulation H" },
      { id: "bo1", label: "Bo1 Swiss", bestOf: 1 },
      { id: "prerelease", label: "Pre-release", bestOf: 1 },
    ],
  },
  {
    id: "pokemon-vgc-seniors",
    name: "Pokémon VGC · Seniors",
    short: "VGC S",
    category: "VGC",
    resource: { kind: "pips", label: "Pokemon remaining", shortLabel: "PKMN", min: 0, max: 6, start: 6, step: 1, invertWin: true, pips: true, pipStyle: "team" },
    extraLabel: "Team",
    extraPlaceholder: "Sun · Balance · Rain",
    scoreLabel: "Games",
    defaultBestOf: 3,
    defaultScorebug: "play",
    formats: [
      { id: "reg-i", label: "VGC 2026 Regulation I" },
      { id: "reg-h", label: "VGC 2026 Regulation H" },
      { id: "bo1", label: "Bo1 Swiss", bestOf: 1 },
      { id: "prerelease", label: "Pre-release", bestOf: 1 },
    ],
  },
  {
    id: "pokemon-vgc-juniors",
    name: "Pokémon VGC · Juniors",
    short: "VGC J",
    category: "VGC",
    resource: { kind: "pips", label: "Pokemon remaining", shortLabel: "PKMN", min: 0, max: 6, start: 6, step: 1, invertWin: true, pips: true, pipStyle: "team" },
    extraLabel: "Team",
    extraPlaceholder: "Sun · Balance · Rain",
    scoreLabel: "Games",
    defaultBestOf: 3,
    defaultScorebug: "play",
    formats: [
      { id: "reg-i", label: "VGC 2026 Regulation I" },
      { id: "reg-h", label: "VGC 2026 Regulation H" },
      { id: "bo1", label: "Bo1 Swiss", bestOf: 1 },
      { id: "prerelease", label: "Pre-release", bestOf: 1 },
    ],
  },
  {
    id: "pokemon-tcg",
    name: "Pokémon TCG · Masters",
    short: "PTCG M",
    category: "TCG",
    resource: { kind: "pips", label: "Prize cards", shortLabel: "PRZ", min: 0, max: 6, start: 6, step: 1, invertWin: true, pips: true, pipStyle: "pokeball" },
    extraLabel: "Deck",
    extraPlaceholder: "Charizard ex · Raging Bolt",
    scoreLabel: "Games",
    defaultBestOf: 3,
    defaultScorebug: "play",
    formats: [
      { id: "standard", label: "Standard" },
      { id: "expanded", label: "Expanded" },
      { id: "pocket", label: "Pocket", resourceStart: 3, resourceMax: 3 },
      { id: "prerelease", label: "Pre-release", bestOf: 1, resourceStart: 4, resourceMax: 4 },
    ],
  },
  {
    id: "pokemon-tcg-seniors",
    name: "Pokémon TCG · Seniors",
    short: "PTCG S",
    category: "TCG",
    resource: { kind: "pips", label: "Prize cards", shortLabel: "PRZ", min: 0, max: 6, start: 6, step: 1, invertWin: true, pips: true, pipStyle: "pokeball" },
    extraLabel: "Deck",
    extraPlaceholder: "Charizard ex · Raging Bolt",
    scoreLabel: "Games",
    defaultBestOf: 3,
    defaultScorebug: "play",
    formats: [
      { id: "standard", label: "Standard" },
      { id: "expanded", label: "Expanded" },
      { id: "pocket", label: "Pocket", resourceStart: 3, resourceMax: 3 },
      { id: "prerelease", label: "Pre-release", bestOf: 1, resourceStart: 4, resourceMax: 4 },
    ],
  },
  {
    id: "pokemon-tcg-juniors",
    name: "Pokémon TCG · Juniors",
    short: "PTCG J",
    category: "TCG",
    resource: { kind: "pips", label: "Prize cards", shortLabel: "PRZ", min: 0, max: 6, start: 6, step: 1, invertWin: true, pips: true, pipStyle: "pokeball" },
    extraLabel: "Deck",
    extraPlaceholder: "Charizard ex · Raging Bolt",
    scoreLabel: "Games",
    defaultBestOf: 3,
    defaultScorebug: "play",
    formats: [
      { id: "standard", label: "Standard" },
      { id: "expanded", label: "Expanded" },
      { id: "pocket", label: "Pocket", resourceStart: 3, resourceMax: 3 },
      { id: "prerelease", label: "Pre-release", bestOf: 1, resourceStart: 4, resourceMax: 4 },
    ],
  },
  {
    id: "one-piece",
    name: "One Piece TCG",
    short: "OP",
    category: "TCG",
    resource: { kind: "pips", label: "Life", shortLabel: "LIFE", min: 0, max: 5, start: 5, step: 1, invertWin: true, pips: true },
    secondary: { label: "DON!!", min: 0, max: 10, start: 1, step: 1 },
    extraLabel: "Leader",
    extraPlaceholder: "Saka · Luffy · Yamato",
    scoreLabel: "Games",
    defaultBestOf: 1,
    defaultScorebug: "play",
    formats: [
      { id: "standard", label: "Standard", bestOf: 1 },
      { id: "extra", label: "Extra (all cards)", bestOf: 1 },
      { id: "sealed", label: "Pre-release / Sealed", bestOf: 1 },
      { id: "championship", label: "Championship top cut", bestOf: 3 },
    ],
  },
  {
    id: "yugioh",
    name: "Yu-Gi-Oh!",
    short: "YGO",
    category: "TCG",
    resource: { kind: "life", label: "Life points", shortLabel: "LP", min: 0, max: 16000, start: 8000, step: 100, invertWin: true, pips: false },
    extraLabel: "Deck",
    extraPlaceholder: "Tenpai · Yubel · Snake-Eye",
    scoreLabel: "Games",
    defaultBestOf: 3,
    defaultScorebug: "play",
    formats: [
      { id: "tcg", label: "TCG Advanced" },
      { id: "md", label: "Master Duel" },
      { id: "edison", label: "Edison" },
      { id: "goat", label: "Goat" },
      { id: "prerelease", label: "Pre-release", bestOf: 1 },
    ],
  },
  {
    id: "mtg",
    name: "Magic: The Gathering",
    short: "MTG",
    category: "TCG",
    resource: { kind: "life", label: "Life", shortLabel: "LIFE", min: 0, max: 99, start: 20, step: 1, invertWin: true, pips: false },
    secondary: { label: "Poison", min: 0, max: 10, start: 0, step: 1 },
    extraLabel: "Deck",
    extraPlaceholder: "Domain Zoo · Izzet Phoenix",
    scoreLabel: "Games",
    defaultBestOf: 3,
    defaultScorebug: "rok",
    formats: [
      { id: "standard", label: "Standard", family: "constructed" },
      { id: "modern", label: "Modern", family: "constructed" },
      { id: "pioneer", label: "Pioneer", family: "constructed" },
      { id: "legacy", label: "Legacy", family: "constructed" },
      { id: "pauper", label: "Pauper", family: "constructed" },
      { id: "prerelease", label: "Pre-release (Sealed)", family: "constructed", bestOf: 1 },
    ],
  },
  {
    id: "mtg-commander",
    name: "Commander",
    short: "EDH",
    category: "TCG",
    resource: { kind: "life", label: "Life", shortLabel: "LIFE", min: 0, max: 999, start: 40, step: 1, invertWin: true, pips: false },
    secondary: { label: "Poison", min: 0, max: 10, start: 0, step: 1 },
    extraLabel: "Commander",
    extraPlaceholder: "Search Atraxa, Kinnan…",
    scoreLabel: "Games",
    defaultBestOf: 1,
    defaultScorebug: "bar",
    formats: [
      { id: "commander", label: "Commander", family: "commander", resourceStart: 40, resourceMax: 999, bestOf: 1, seats: 4 },
      { id: "cedh", label: "cEDH", family: "commander", resourceStart: 40, resourceMax: 999, bestOf: 1, seats: 4 },
      { id: "duel", label: "Duel Commander", family: "commander", resourceStart: 20, resourceMax: 999, bestOf: 3, seats: 2 },
    ],
  },
  {
    id: "lorcana",
    name: "Disney Lorcana",
    short: "Lorcana",
    category: "TCG",
    resource: { kind: "points", label: "Lore", shortLabel: "LORE", min: 0, max: 20, start: 0, step: 1, invertWin: false, pips: false },
    extraLabel: "Deck",
    extraPlaceholder: "Ruby Aggro · Amber/Steel midrange",
    scoreLabel: "Games",
    defaultBestOf: 3,
    defaultScorebug: "play",
    formats: [
      { id: "core", label: "Core Constructed" },
      { id: "prerelease", label: "Pre-release", bestOf: 1 },
    ],
  },
  {
    id: "swu",
    name: "Star Wars Unlimited",
    short: "SWU",
    category: "TCG",
    resource: { kind: "life", label: "Base HP", shortLabel: "HP", min: 0, max: 40, start: 30, step: 1, invertWin: true, pips: false },
    extraLabel: "Leader / Base",
    extraPlaceholder: "Vader · Sabine",
    scoreLabel: "Games",
    defaultBestOf: 3,
    defaultScorebug: "rok",
    formats: [
      { id: "premier", label: "Premier" },
      { id: "prerelease", label: "Pre-release", bestOf: 1 },
    ],
  },
  {
    id: "riftbound",
    name: "Riftbound",
    short: "RB",
    category: "TCG",
    resource: { kind: "points", label: "Points", shortLabel: "PTS", min: 0, max: 8, start: 0, step: 1, invertWin: false, pips: true },
    extraLabel: "Champion",
    extraPlaceholder: "Jinx · Volibear · Annie",
    scoreLabel: "Games",
    defaultBestOf: 1,
    defaultScorebug: "rok",
    formats: [
      { id: "duel", label: "Duel (1v1)", bestOf: 1, seats: 2 },
      { id: "match", label: "Match (1v1, Bo3)", bestOf: 3, seats: 2 },
      { id: "skirmish", label: "Skirmish (FFA3)", bestOf: 1, seats: 3 },
      { id: "war", label: "War (FFA4)", bestOf: 1, seats: 4 },
      { id: "limited", label: "Limited / Sealed", bestOf: 3, seats: 2 },
      { id: "prerelease", label: "Pre-release", bestOf: 1, seats: 2 },
      { id: "bo1", label: "Bo1 Swiss", bestOf: 1, seats: 2 },
    ],
  },
];

export const GAMES: Record<GameId, GameDef> = Object.fromEntries(
  GAME_LIST.map((g) => [g.id, g]),
) as Record<GameId, GameDef>;

export const GAME_SLUG: Record<GameId, string> = {
  "pokemon-vgc": "vgc",
  "pokemon-vgc-seniors": "vgc-seniors",
  "pokemon-vgc-juniors": "vgc-juniors",
  "pokemon-tcg": "ptcg",
  "pokemon-tcg-seniors": "ptcg-seniors",
  "pokemon-tcg-juniors": "ptcg-juniors",
  "one-piece": "op",
  yugioh: "ygo",
  mtg: "mtg",
  "mtg-commander": "edh",
  lorcana: "lorcana",
  swu: "swu",
  riftbound: "rb",
};
