/** Regulation M-C formes that are not already on the national list. Mega formes are not included. */
export const REG_MC_FORMES = [
  { name: "Raichu-A", slug: "raichu-alolan", dex: 26, types: ["electric", "psychic"], abilities: ["Surge Surfer"] },
  { name: "Persian-A", slug: "persian-alolan", dex: 53, types: ["dark"], abilities: ["Fur Coat", "Technician", "Rattled"] },
  { name: "Slowbro-G", slug: "slowbro-galarian", dex: 80, types: ["poison", "psychic"], abilities: ["Quick Draw", "Own Tempo", "Regenerator"] },
  { name: "Slowking-G", slug: "slowking-galarian", dex: 199, types: ["poison", "psychic"], abilities: ["Curious Medicine", "Own Tempo", "Regenerator"] },
  { name: "Tauros-Paldea", slug: "tauros-paldea-combat", dex: 128, types: ["fighting"], abilities: ["Intimidate", "Anger Point", "Cud Chew"] },
  { name: "Tauros-Paldea-Blaze", slug: "tauros-paldea-blaze", dex: 128, types: ["fighting", "fire"], abilities: ["Intimidate", "Anger Point", "Cud Chew"] },
  { name: "Tauros-Paldea-Aqua", slug: "tauros-paldea-aqua", dex: 128, types: ["fighting", "water"], abilities: ["Intimidate", "Anger Point", "Cud Chew"] },
  { name: "Rotom-Heat", slug: "rotom-heat", dex: 479, types: ["electric", "fire"], abilities: ["Levitate"] },
  { name: "Rotom-Wash", slug: "rotom-wash", dex: 479, types: ["electric", "water"], abilities: ["Levitate"] },
  { name: "Rotom-Frost", slug: "rotom-frost", dex: 479, types: ["electric", "ice"], abilities: ["Levitate"] },
  { name: "Rotom-Fan", slug: "rotom-fan", dex: 479, types: ["electric", "flying"], abilities: ["Levitate"] },
  { name: "Rotom-Mow", slug: "rotom-mow", dex: 479, types: ["electric", "grass"], abilities: ["Levitate"] },
  { name: "Zoroark-H", slug: "zoroark-hisuian", dex: 571, types: ["normal", "ghost"], abilities: ["Illusion"] },
  { name: "Stunfisk-G", slug: "stunfisk-galarian", dex: 618, types: ["ground", "steel"], abilities: ["Mimicry"] },
  { name: "Meowstic-F", slug: "meowstic-female", dex: 678, types: ["psychic"], abilities: ["Keen Eye", "Infiltrator", "Competitive"] },
  { name: "Gourgeist-Small", slug: "gourgeist-small", dex: 711, types: ["ghost", "grass"], abilities: ["Pickup", "Frisk", "Insomnia"] },
  { name: "Gourgeist-Large", slug: "gourgeist-large", dex: 711, types: ["ghost", "grass"], abilities: ["Pickup", "Frisk", "Insomnia"] },
  { name: "Gourgeist-Super", slug: "gourgeist-super", dex: 711, types: ["ghost", "grass"], abilities: ["Pickup", "Frisk", "Insomnia"] },
  { name: "Avalugg-H", slug: "avalugg-hisuian", dex: 713, types: ["ice", "rock"], abilities: ["Strong Jaw", "Ice Body", "Sturdy"] },
  { name: "Lycanroc-Midnight", slug: "lycanroc-midnight", dex: 745, types: ["rock"], abilities: ["Keen Eye", "Vital Spirit", "No Guard"] },
  { name: "Lycanroc-Dusk", slug: "lycanroc-dusk", dex: 745, types: ["rock"], abilities: ["Tough Claws"] },
  { name: "Toxtricity-Low-Key", slug: "toxtricity-low-key", dex: 849, types: ["electric", "poison"], abilities: ["Punk Rock", "Minus", "Technician"] },
  { name: "Basculegion-F", slug: "basculegion-female", dex: 902, types: ["water", "ghost"], abilities: ["Swift Swim", "Adaptability", "Mold Breaker"] },
  { name: "Maushold-Three", slug: "maushold-family3", dex: 925, types: ["normal"], abilities: ["Friend Guard", "Cheek Pouch", "Technician"] },
] as const;

/** Species legal on the Regulation M-C signup sheet. Mega Evolutions are not listed. */
export const REG_MC_NAMES = [
  "Venusaur", "Charizard", "Blastoise", "Beedrill", "Pidgeot", "Arbok", "Pikachu", "Raichu", "Raichu-A",
  "Clefable", "Ninetales", "Ninetales-A", "Wigglytuff", "Vileplume", "Persian", "Persian-A", "Arcanine", "Arcanine-H",
  "Alakazam", "Machamp", "Victreebel", "Slowbro", "Slowbro-G", "Farfetch'd", "Gengar", "Kangaskhan", "Starmie",
  "Mr. Mime", "Pinsir", "Tauros", "Tauros-Paldea", "Tauros-Paldea-Blaze", "Tauros-Paldea-Aqua", "Gyarados", "Ditto",
  "Vaporeon", "Jolteon", "Flareon", "Aerodactyl", "Snorlax", "Dragonite", "Meganium", "Typhlosion", "Typhlosion-H",
  "Feraligatr", "Ariados", "Ampharos", "Azumarill", "Politoed", "Espeon", "Umbreon", "Slowking", "Slowking-G",
  "Forretress", "Steelix", "Qwilfish", "Scizor", "Heracross", "Skarmory", "Houndoom", "Tyranitar", "Sceptile",
  "Blaziken", "Swampert", "Pelipper", "Gardevoir", "Sableye", "Mawile", "Aggron", "Medicham", "Manectric", "Swalot",
  "Sharpedo", "Camerupt", "Torkoal", "Altaria", "Milotic", "Castform", "Banette", "Chimecho", "Absol", "Glalie",
  "Salamence", "Metagross", "Torterra", "Infernape", "Empoleon", "Staraptor", "Luxray", "Roserade", "Rampardos",
  "Bastiodon", "Lopunny", "Spiritomb", "Garchomp", "Lucario", "Hippowdon", "Toxicroak", "Abomasnow", "Weavile",
  "Rhyperior", "Leafeon", "Glaceon", "Gliscor", "Mamoswine", "Gallade", "Froslass", "Rotom", "Rotom-Heat",
  "Rotom-Wash", "Rotom-Frost", "Rotom-Fan", "Rotom-Mow", "Serperior", "Emboar", "Samurott", "Samurott-H",
  "Watchog", "Liepard", "Simisage", "Simisear", "Simipour", "Musharna", "Excadrill", "Audino", "Conkeldurr",
  "Scolipede", "Whimsicott", "Krookodile", "Scrafty", "Cofagrigus", "Garbodor", "Zoroark", "Zoroark-H", "Reuniclus",
  "Vanilluxe", "Emolga", "Eelektross", "Chandelure", "Beartic", "Stunfisk", "Stunfisk-G", "Golurk", "Hydreigon",
  "Volcarona", "Chesnaught", "Delphox", "Greninja", "Diggersby", "Talonflame", "Vivillon", "Pyroar", "Floette Eternal",
  "Florges", "Gogoat", "Pangoro", "Furfrou", "Meowstic", "Meowstic-F", "Aegislash", "Aromatisse", "Slurpuff",
  "Malamar", "Barbaracle", "Dragalge", "Clawitzer", "Heliolisk", "Tyrantrum", "Aurorus", "Sylveon", "Hawlucha",
  "Dedenne", "Goodra", "Goodra-H", "Klefki", "Trevenant", "Gourgeist", "Gourgeist-Small", "Gourgeist-Large",
  "Gourgeist-Super", "Avalugg", "Avalugg-H", "Noivern", "Decidueye", "Decidueye-H", "Incineroar", "Primarina",
  "Toucannon", "Crabominable", "Lycanroc", "Lycanroc-Midnight", "Lycanroc-Dusk", "Toxapex", "Mudsdale", "Araquanid",
  "Salazzle", "Tsareena", "Oranguru", "Passimian", "Golisopod", "Mimikyu", "Drampa", "Kommo-o", "Rillaboom",
  "Cinderace", "Inteleon", "Corviknight", "Thievul", "Flapple", "Appletun", "Sandaconda", "Toxtricity",
  "Toxtricity-Low-Key", "Grapploct", "Polteageist", "Hatterene", "Grimmsnarl", "Perrserker", "Sirfetch'd",
  "Mr. Rime", "Runerigus", "Alcremie", "Falinks", "Pincurchin", "Indeedee M", "Indeedee F", "Morpeko", "Dragapult",
  "Wyrdeer", "Kleavor", "Basculegion", "Basculegion-F", "Sneasler", "Overqwil", "Meowscarada", "Skeledirge",
  "Quaquaval", "Pawmot", "Maushold", "Maushold-Three", "Arboliva", "Squawkabilly", "Garganacl", "Armarouge", "Ceruledge", "Bellibolt",
  "Mabosstiff", "Scovillain", "Espathra", "Tinkaton", "Palafin", "Orthworm", "Glimmora", "Houndstone", "Annihilape",
  "Farigiraf", "Kingambit", "Baxcalibur", "Gholdengo", "Sinistcha", "Archaludon", "Hydrapple",
] as const;

export const REG_MC_NAME_SET = new Set(REG_MC_NAMES.map((name) => name.toLowerCase()));
