/* Generated from https://pokemondb.net/pokedex/national — do not edit by hand. */

export const SPECIES = [
  { name: "Bulbasaur", slug: "bulbasaur", dex: 1, types: ["grass", "poison"], abilities: [] },
  { name: "Ivysaur", slug: "ivysaur", dex: 2, types: ["grass", "poison"], abilities: [] },
  { name: "Venusaur", slug: "venusaur", dex: 3, types: ["grass", "poison"], abilities: ["Overgrow", "Chlorophyll"] },
  { name: "Charmander", slug: "charmander", dex: 4, types: ["fire"], abilities: [] },
  { name: "Charmeleon", slug: "charmeleon", dex: 5, types: ["fire"], abilities: [] },
  { name: "Charizard", slug: "charizard", dex: 6, types: ["fire", "flying"], abilities: ["Blaze", "Solar Power"] },
  { name: "Squirtle", slug: "squirtle", dex: 7, types: ["water"], abilities: [] },
  { name: "Wartortle", slug: "wartortle", dex: 8, types: ["water"], abilities: [] },
  { name: "Blastoise", slug: "blastoise", dex: 9, types: ["water"], abilities: ["Torrent", "Rain Dish"] },
  { name: "Caterpie", slug: "caterpie", dex: 10, types: ["bug"], abilities: [] },
  { name: "Metapod", slug: "metapod", dex: 11, types: ["bug"], abilities: [] },
  { name: "Butterfree", slug: "butterfree", dex: 12, types: ["bug", "flying"], abilities: [] },
  { name: "Weedle", slug: "weedle", dex: 13, types: ["bug", "poison"], abilities: [] },
  { name: "Kakuna", slug: "kakuna", dex: 14, types: ["bug", "poison"], abilities: [] },
  { name: "Beedrill", slug: "beedrill", dex: 15, types: ["bug", "poison"], abilities: [] },
  { name: "Pidgey", slug: "pidgey", dex: 16, types: ["normal", "flying"], abilities: [] },
  { name: "Pidgeotto", slug: "pidgeotto", dex: 17, types: ["normal", "flying"], abilities: [] },
  { name: "Pidgeot", slug: "pidgeot", dex: 18, types: ["normal", "flying"], abilities: [] },
  { name: "Rattata", slug: "rattata", dex: 19, types: ["normal"], abilities: [] },
  { name: "Raticate", slug: "raticate", dex: 20, types: ["normal"], abilities: [] },
  { name: "Spearow", slug: "spearow", dex: 21, types: ["normal", "flying"], abilities: [] },
  { name: "Fearow", slug: "fearow", dex: 22, types: ["normal", "flying"], abilities: [] },
  { name: "Ekans", slug: "ekans", dex: 23, types: ["poison"], abilities: [] },
  { name: "Arbok", slug: "arbok", dex: 24, types: ["poison"], abilities: [] },
  { name: "Pikachu", slug: "pikachu", dex: 25, types: ["electric"], abilities: [] },
  { name: "Raichu", slug: "raichu", dex: 26, types: ["electric"], abilities: [] },
  { name: "Sandshrew", slug: "sandshrew", dex: 27, types: ["ground"], abilities: [] },
  { name: "Sandslash", slug: "sandslash", dex: 28, types: ["ground"], abilities: [] },
  { name: "Nidoran♀", slug: "nidoran-f", dex: 29, types: ["poison"], abilities: [] },
  { name: "Nidorina", slug: "nidorina", dex: 30, types: ["poison"], abilities: [] },
  { name: "Nidoqueen", slug: "nidoqueen", dex: 31, types: ["poison", "ground"], abilities: [] },
  { name: "Nidoran♂", slug: "nidoran-m", dex: 32, types: ["poison"], abilities: [] },
  { name: "Nidorino", slug: "nidorino", dex: 33, types: ["poison"], abilities: [] },
  { name: "Nidoking", slug: "nidoking", dex: 34, types: ["poison", "ground"], abilities: [] },
  { name: "Clefairy", slug: "clefairy", dex: 35, types: ["fairy"], abilities: [] },
  { name: "Clefable", slug: "clefable", dex: 36, types: ["fairy"], abilities: [] },
  { name: "Vulpix", slug: "vulpix", dex: 37, types: ["fire"], abilities: [] },
  { name: "Ninetales", slug: "ninetales", dex: 38, types: ["fire"], abilities: [] },
  { name: "Jigglypuff", slug: "jigglypuff", dex: 39, types: ["normal", "fairy"], abilities: [] },
  { name: "Wigglytuff", slug: "wigglytuff", dex: 40, types: ["normal", "fairy"], abilities: [] },
  { name: "Zubat", slug: "zubat", dex: 41, types: ["poison", "flying"], abilities: [] },
  { name: "Golbat", slug: "golbat", dex: 42, types: ["poison", "flying"], abilities: [] },
  { name: "Oddish", slug: "oddish", dex: 43, types: ["grass", "poison"], abilities: [] },
  { name: "Gloom", slug: "gloom", dex: 44, types: ["grass", "poison"], abilities: [] },
  { name: "Vileplume", slug: "vileplume", dex: 45, types: ["grass", "poison"], abilities: [] },
  { name: "Paras", slug: "paras", dex: 46, types: ["bug", "grass"], abilities: [] },
  { name: "Parasect", slug: "parasect", dex: 47, types: ["bug", "grass"], abilities: [] },
  { name: "Venonat", slug: "venonat", dex: 48, types: ["bug", "poison"], abilities: [] },
  { name: "Venomoth", slug: "venomoth", dex: 49, types: ["bug", "poison"], abilities: [] },
  { name: "Diglett", slug: "diglett", dex: 50, types: ["ground"], abilities: [] },
  { name: "Dugtrio", slug: "dugtrio", dex: 51, types: ["ground"], abilities: [] },
  { name: "Meowth", slug: "meowth", dex: 52, types: ["normal"], abilities: [] },
  { name: "Persian", slug: "persian", dex: 53, types: ["normal"], abilities: [] },
  { name: "Psyduck", slug: "psyduck", dex: 54, types: ["water"], abilities: [] },
  { name: "Golduck", slug: "golduck", dex: 55, types: ["water"], abilities: [] },
  { name: "Mankey", slug: "mankey", dex: 56, types: ["fighting"], abilities: [] },
  { name: "Primeape", slug: "primeape", dex: 57, types: ["fighting"], abilities: [] },
  { name: "Growlithe", slug: "growlithe", dex: 58, types: ["fire"], abilities: [] },
  { name: "Arcanine", slug: "arcanine", dex: 59, types: ["fire"], abilities: [] },
  { name: "Poliwag", slug: "poliwag", dex: 60, types: ["water"], abilities: [] },
  { name: "Poliwhirl", slug: "poliwhirl", dex: 61, types: ["water"], abilities: [] },
  { name: "Poliwrath", slug: "poliwrath", dex: 62, types: ["water", "fighting"], abilities: [] },
  { name: "Abra", slug: "abra", dex: 63, types: ["psychic"], abilities: [] },
  { name: "Kadabra", slug: "kadabra", dex: 64, types: ["psychic"], abilities: [] },
  { name: "Alakazam", slug: "alakazam", dex: 65, types: ["psychic"], abilities: [] },
  { name: "Machop", slug: "machop", dex: 66, types: ["fighting"], abilities: [] },
  { name: "Machoke", slug: "machoke", dex: 67, types: ["fighting"], abilities: [] },
  { name: "Machamp", slug: "machamp", dex: 68, types: ["fighting"], abilities: [] },
  { name: "Bellsprout", slug: "bellsprout", dex: 69, types: ["grass", "poison"], abilities: [] },
  { name: "Weepinbell", slug: "weepinbell", dex: 70, types: ["grass", "poison"], abilities: [] },
  { name: "Victreebel", slug: "victreebel", dex: 71, types: ["grass", "poison"], abilities: [] },
  { name: "Tentacool", slug: "tentacool", dex: 72, types: ["water", "poison"], abilities: [] },
  { name: "Tentacruel", slug: "tentacruel", dex: 73, types: ["water", "poison"], abilities: [] },
  { name: "Geodude", slug: "geodude", dex: 74, types: ["rock", "ground"], abilities: [] },
  { name: "Graveler", slug: "graveler", dex: 75, types: ["rock", "ground"], abilities: [] },
  { name: "Golem", slug: "golem", dex: 76, types: ["rock", "ground"], abilities: [] },
  { name: "Ponyta", slug: "ponyta", dex: 77, types: ["fire"], abilities: [] },
  { name: "Rapidash", slug: "rapidash", dex: 78, types: ["fire"], abilities: [] },
  { name: "Slowpoke", slug: "slowpoke", dex: 79, types: ["water", "psychic"], abilities: [] },
  { name: "Slowbro", slug: "slowbro", dex: 80, types: ["water", "psychic"], abilities: [] },
  { name: "Magnemite", slug: "magnemite", dex: 81, types: ["electric", "steel"], abilities: [] },
  { name: "Magneton", slug: "magneton", dex: 82, types: ["electric", "steel"], abilities: [] },
  { name: "Farfetch'd", slug: "farfetchd", dex: 39, types: ["normal", "flying"], abilities: [] },
  { name: "Doduo", slug: "doduo", dex: 84, types: ["normal", "flying"], abilities: [] },
  { name: "Dodrio", slug: "dodrio", dex: 85, types: ["normal", "flying"], abilities: [] },
  { name: "Seel", slug: "seel", dex: 86, types: ["water"], abilities: [] },
  { name: "Dewgong", slug: "dewgong", dex: 87, types: ["water", "ice"], abilities: [] },
  { name: "Grimer", slug: "grimer", dex: 88, types: ["poison"], abilities: [] },
  { name: "Muk", slug: "muk", dex: 89, types: ["poison"], abilities: [] },
  { name: "Shellder", slug: "shellder", dex: 90, types: ["water"], abilities: [] },
  { name: "Cloyster", slug: "cloyster", dex: 91, types: ["water", "ice"], abilities: [] },
  { name: "Gastly", slug: "gastly", dex: 92, types: ["ghost", "poison"], abilities: [] },
  { name: "Haunter", slug: "haunter", dex: 93, types: ["ghost", "poison"], abilities: [] },
  { name: "Gengar", slug: "gengar", dex: 94, types: ["ghost", "poison"], abilities: ["Cursed Body"] },
  { name: "Onix", slug: "onix", dex: 95, types: ["rock", "ground"], abilities: [] },
  { name: "Drowzee", slug: "drowzee", dex: 96, types: ["psychic"], abilities: [] },
  { name: "Hypno", slug: "hypno", dex: 97, types: ["psychic"], abilities: [] },
  { name: "Krabby", slug: "krabby", dex: 98, types: ["water"], abilities: [] },
  { name: "Kingler", slug: "kingler", dex: 99, types: ["water"], abilities: [] },
  { name: "Voltorb", slug: "voltorb", dex: 100, types: ["electric"], abilities: [] },
  { name: "Electrode", slug: "electrode", dex: 101, types: ["electric"], abilities: [] },
  { name: "Exeggcute", slug: "exeggcute", dex: 102, types: ["grass", "psychic"], abilities: [] },
  { name: "Exeggutor", slug: "exeggutor", dex: 103, types: ["grass", "psychic"], abilities: [] },
  { name: "Cubone", slug: "cubone", dex: 104, types: ["ground"], abilities: [] },
  { name: "Marowak", slug: "marowak", dex: 105, types: ["ground"], abilities: [] },
  { name: "Hitmonlee", slug: "hitmonlee", dex: 106, types: ["fighting"], abilities: [] },
  { name: "Hitmonchan", slug: "hitmonchan", dex: 107, types: ["fighting"], abilities: [] },
  { name: "Lickitung", slug: "lickitung", dex: 108, types: ["normal"], abilities: [] },
  { name: "Koffing", slug: "koffing", dex: 109, types: ["poison"], abilities: [] },
  { name: "Weezing", slug: "weezing", dex: 110, types: ["poison"], abilities: [] },
  { name: "Rhyhorn", slug: "rhyhorn", dex: 111, types: ["ground", "rock"], abilities: [] },
  { name: "Rhydon", slug: "rhydon", dex: 112, types: ["ground", "rock"], abilities: [] },
  { name: "Chansey", slug: "chansey", dex: 113, types: ["normal"], abilities: [] },
  { name: "Tangela", slug: "tangela", dex: 114, types: ["grass"], abilities: [] },
  { name: "Kangaskhan", slug: "kangaskhan", dex: 115, types: ["normal"], abilities: [] },
  { name: "Horsea", slug: "horsea", dex: 116, types: ["water"], abilities: [] },
  { name: "Seadra", slug: "seadra", dex: 117, types: ["water"], abilities: [] },
  { name: "Goldeen", slug: "goldeen", dex: 118, types: ["water"], abilities: [] },
  { name: "Seaking", slug: "seaking", dex: 119, types: ["water"], abilities: [] },
  { name: "Staryu", slug: "staryu", dex: 120, types: ["water"], abilities: [] },
  { name: "Starmie", slug: "starmie", dex: 121, types: ["water", "psychic"], abilities: [] },
  { name: "Mr. Mime", slug: "mr-mime", dex: 122, types: ["psychic", "fairy"], abilities: [] },
  { name: "Scyther", slug: "scyther", dex: 123, types: ["bug", "flying"], abilities: [] },
  { name: "Jynx", slug: "jynx", dex: 124, types: ["ice", "psychic"], abilities: [] },
  { name: "Electabuzz", slug: "electabuzz", dex: 125, types: ["electric"], abilities: [] },
  { name: "Magmar", slug: "magmar", dex: 126, types: ["fire"], abilities: [] },
  { name: "Pinsir", slug: "pinsir", dex: 127, types: ["bug"], abilities: [] },
  { name: "Tauros", slug: "tauros", dex: 128, types: ["normal"], abilities: [] },
  { name: "Magikarp", slug: "magikarp", dex: 129, types: ["water"], abilities: [] },
  { name: "Gyarados", slug: "gyarados", dex: 130, types: ["water", "flying"], abilities: ["Intimidate", "Moxie"] },
  { name: "Lapras", slug: "lapras", dex: 131, types: ["water", "ice"], abilities: [] },
  { name: "Ditto", slug: "ditto", dex: 132, types: ["normal"], abilities: [] },
  { name: "Eevee", slug: "eevee", dex: 133, types: ["normal"], abilities: [] },
  { name: "Vaporeon", slug: "vaporeon", dex: 134, types: ["water"], abilities: [] },
  { name: "Jolteon", slug: "jolteon", dex: 135, types: ["electric"], abilities: [] },
  { name: "Flareon", slug: "flareon", dex: 136, types: ["fire"], abilities: [] },
  { name: "Porygon", slug: "porygon", dex: 137, types: ["normal"], abilities: [] },
  { name: "Omanyte", slug: "omanyte", dex: 138, types: ["rock", "water"], abilities: [] },
  { name: "Omastar", slug: "omastar", dex: 139, types: ["rock", "water"], abilities: [] },
  { name: "Kabuto", slug: "kabuto", dex: 140, types: ["rock", "water"], abilities: [] },
  { name: "Kabutops", slug: "kabutops", dex: 141, types: ["rock", "water"], abilities: [] },
  { name: "Aerodactyl", slug: "aerodactyl", dex: 142, types: ["rock", "flying"], abilities: [] },
  { name: "Snorlax", slug: "snorlax", dex: 143, types: ["normal"], abilities: [] },
  { name: "Articuno", slug: "articuno", dex: 144, types: ["ice", "flying"], abilities: [] },
  { name: "Zapdos", slug: "zapdos", dex: 145, types: ["electric", "flying"], abilities: [] },
  { name: "Moltres", slug: "moltres", dex: 146, types: ["fire", "flying"], abilities: [] },
  { name: "Dratini", slug: "dratini", dex: 147, types: ["dragon"], abilities: [] },
  { name: "Dragonair", slug: "dragonair", dex: 148, types: ["dragon"], abilities: [] },
  { name: "Dragonite", slug: "dragonite", dex: 149, types: ["dragon", "flying"], abilities: ["Inner Focus", "Multiscale"] },
  { name: "Mewtwo", slug: "mewtwo", dex: 150, types: ["psychic"], abilities: [] },
  { name: "Mew", slug: "mew", dex: 151, types: ["psychic"], abilities: [] },
  { name: "Chikorita", slug: "chikorita", dex: 152, types: ["grass"], abilities: [] },
  { name: "Bayleef", slug: "bayleef", dex: 153, types: ["grass"], abilities: [] },
  { name: "Meganium", slug: "meganium", dex: 154, types: ["grass"], abilities: [] },
  { name: "Cyndaquil", slug: "cyndaquil", dex: 155, types: ["fire"], abilities: [] },
  { name: "Quilava", slug: "quilava", dex: 156, types: ["fire"], abilities: [] },
  { name: "Typhlosion", slug: "typhlosion", dex: 157, types: ["fire"], abilities: [] },
  { name: "Totodile", slug: "totodile", dex: 158, types: ["water"], abilities: [] },
  { name: "Croconaw", slug: "croconaw", dex: 159, types: ["water"], abilities: [] },
  { name: "Feraligatr", slug: "feraligatr", dex: 160, types: ["water"], abilities: [] },
  { name: "Sentret", slug: "sentret", dex: 161, types: ["normal"], abilities: [] },
  { name: "Furret", slug: "furret", dex: 162, types: ["normal"], abilities: [] },
  { name: "Hoothoot", slug: "hoothoot", dex: 163, types: ["normal", "flying"], abilities: [] },
  { name: "Noctowl", slug: "noctowl", dex: 164, types: ["normal", "flying"], abilities: [] },
  { name: "Ledyba", slug: "ledyba", dex: 165, types: ["bug", "flying"], abilities: [] },
  { name: "Ledian", slug: "ledian", dex: 166, types: ["bug", "flying"], abilities: [] },
  { name: "Spinarak", slug: "spinarak", dex: 167, types: ["bug", "poison"], abilities: [] },
  { name: "Ariados", slug: "ariados", dex: 168, types: ["bug", "poison"], abilities: [] },
  { name: "Crobat", slug: "crobat", dex: 169, types: ["poison", "flying"], abilities: [] },
  { name: "Chinchou", slug: "chinchou", dex: 170, types: ["water", "electric"], abilities: [] },
  { name: "Lanturn", slug: "lanturn", dex: 171, types: ["water", "electric"], abilities: [] },
  { name: "Pichu", slug: "pichu", dex: 172, types: ["electric"], abilities: [] },
  { name: "Cleffa", slug: "cleffa", dex: 173, types: ["fairy"], abilities: [] },
  { name: "Igglybuff", slug: "igglybuff", dex: 174, types: ["normal", "fairy"], abilities: [] },
  { name: "Togepi", slug: "togepi", dex: 175, types: ["fairy"], abilities: [] },
  { name: "Togetic", slug: "togetic", dex: 176, types: ["fairy", "flying"], abilities: [] },
  { name: "Natu", slug: "natu", dex: 177, types: ["psychic", "flying"], abilities: [] },
  { name: "Xatu", slug: "xatu", dex: 178, types: ["psychic", "flying"], abilities: [] },
  { name: "Mareep", slug: "mareep", dex: 179, types: ["electric"], abilities: [] },
  { name: "Flaaffy", slug: "flaaffy", dex: 180, types: ["electric"], abilities: [] },
  { name: "Ampharos", slug: "ampharos", dex: 181, types: ["electric"], abilities: [] },
  { name: "Bellossom", slug: "bellossom", dex: 182, types: ["grass"], abilities: [] },
  { name: "Marill", slug: "marill", dex: 183, types: ["water", "fairy"], abilities: [] },
  { name: "Azumarill", slug: "azumarill", dex: 184, types: ["water", "fairy"], abilities: [] },
  { name: "Sudowoodo", slug: "sudowoodo", dex: 185, types: ["rock"], abilities: [] },
  { name: "Politoed", slug: "politoed", dex: 186, types: ["water"], abilities: ["Water Absorb", "Damp", "Drizzle"] },
  { name: "Hoppip", slug: "hoppip", dex: 187, types: ["grass", "flying"], abilities: [] },
  { name: "Skiploom", slug: "skiploom", dex: 188, types: ["grass", "flying"], abilities: [] },
  { name: "Jumpluff", slug: "jumpluff", dex: 189, types: ["grass", "flying"], abilities: [] },
  { name: "Aipom", slug: "aipom", dex: 190, types: ["normal"], abilities: [] },
  { name: "Sunkern", slug: "sunkern", dex: 191, types: ["grass"], abilities: [] },
  { name: "Sunflora", slug: "sunflora", dex: 192, types: ["grass"], abilities: [] },
  { name: "Yanma", slug: "yanma", dex: 193, types: ["bug", "flying"], abilities: [] },
  { name: "Wooper", slug: "wooper", dex: 194, types: ["water", "ground"], abilities: [] },
  { name: "Quagsire", slug: "quagsire", dex: 195, types: ["water", "ground"], abilities: [] },
  { name: "Espeon", slug: "espeon", dex: 196, types: ["psychic"], abilities: [] },
  { name: "Umbreon", slug: "umbreon", dex: 197, types: ["dark"], abilities: [] },
  { name: "Murkrow", slug: "murkrow", dex: 198, types: ["dark", "flying"], abilities: [] },
  { name: "Slowking", slug: "slowking", dex: 199, types: ["water", "psychic"], abilities: [] },
  { name: "Misdreavus", slug: "misdreavus", dex: 200, types: ["ghost"], abilities: [] },
  { name: "Unown", slug: "unown", dex: 201, types: ["psychic"], abilities: [] },
  { name: "Wobbuffet", slug: "wobbuffet", dex: 202, types: ["psychic"], abilities: [] },
  { name: "Girafarig", slug: "girafarig", dex: 203, types: ["normal", "psychic"], abilities: [] },
  { name: "Pineco", slug: "pineco", dex: 204, types: ["bug"], abilities: [] },
  { name: "Forretress", slug: "forretress", dex: 205, types: ["bug", "steel"], abilities: [] },
  { name: "Dunsparce", slug: "dunsparce", dex: 206, types: ["normal"], abilities: [] },
  { name: "Gligar", slug: "gligar", dex: 207, types: ["ground", "flying"], abilities: [] },
  { name: "Steelix", slug: "steelix", dex: 208, types: ["steel", "ground"], abilities: [] },
  { name: "Snubbull", slug: "snubbull", dex: 209, types: ["fairy"], abilities: [] },
  { name: "Granbull", slug: "granbull", dex: 210, types: ["fairy"], abilities: [] },
  { name: "Qwilfish", slug: "qwilfish", dex: 211, types: ["water", "poison"], abilities: [] },
  { name: "Scizor", slug: "scizor", dex: 212, types: ["bug", "steel"], abilities: [] },
  { name: "Shuckle", slug: "shuckle", dex: 213, types: ["bug", "rock"], abilities: [] },
  { name: "Heracross", slug: "heracross", dex: 214, types: ["bug", "fighting"], abilities: [] },
  { name: "Sneasel", slug: "sneasel", dex: 215, types: ["dark", "ice"], abilities: [] },
  { name: "Teddiursa", slug: "teddiursa", dex: 216, types: ["normal"], abilities: [] },
  { name: "Ursaring", slug: "ursaring", dex: 217, types: ["normal"], abilities: [] },
  { name: "Slugma", slug: "slugma", dex: 218, types: ["fire"], abilities: [] },
  { name: "Magcargo", slug: "magcargo", dex: 219, types: ["fire", "rock"], abilities: [] },
  { name: "Swinub", slug: "swinub", dex: 220, types: ["ice", "ground"], abilities: [] },
  { name: "Piloswine", slug: "piloswine", dex: 221, types: ["ice", "ground"], abilities: [] },
  { name: "Corsola", slug: "corsola", dex: 222, types: ["water", "rock"], abilities: [] },
  { name: "Remoraid", slug: "remoraid", dex: 223, types: ["water"], abilities: [] },
  { name: "Octillery", slug: "octillery", dex: 224, types: ["water"], abilities: [] },
  { name: "Delibird", slug: "delibird", dex: 225, types: ["ice", "flying"], abilities: [] },
  { name: "Mantine", slug: "mantine", dex: 226, types: ["water", "flying"], abilities: [] },
  { name: "Skarmory", slug: "skarmory", dex: 227, types: ["steel", "flying"], abilities: [] },
  { name: "Houndour", slug: "houndour", dex: 228, types: ["dark", "fire"], abilities: [] },
  { name: "Houndoom", slug: "houndoom", dex: 229, types: ["dark", "fire"], abilities: [] },
  { name: "Kingdra", slug: "kingdra", dex: 230, types: ["water", "dragon"], abilities: [] },
  { name: "Phanpy", slug: "phanpy", dex: 231, types: ["ground"], abilities: [] },
  { name: "Donphan", slug: "donphan", dex: 232, types: ["ground"], abilities: [] },
  { name: "Porygon2", slug: "porygon2", dex: 233, types: ["normal"], abilities: ["Trace", "Download", "Analytic"] },
  { name: "Stantler", slug: "stantler", dex: 234, types: ["normal"], abilities: [] },
  { name: "Smeargle", slug: "smeargle", dex: 235, types: ["normal"], abilities: [] },
  { name: "Tyrogue", slug: "tyrogue", dex: 236, types: ["fighting"], abilities: [] },
  { name: "Hitmontop", slug: "hitmontop", dex: 237, types: ["fighting"], abilities: [] },
  { name: "Smoochum", slug: "smoochum", dex: 238, types: ["ice", "psychic"], abilities: [] },
  { name: "Elekid", slug: "elekid", dex: 239, types: ["electric"], abilities: [] },
  { name: "Magby", slug: "magby", dex: 240, types: ["fire"], abilities: [] },
  { name: "Miltank", slug: "miltank", dex: 241, types: ["normal"], abilities: [] },
  { name: "Blissey", slug: "blissey", dex: 242, types: ["normal"], abilities: [] },
  { name: "Raikou", slug: "raikou", dex: 243, types: ["electric"], abilities: [] },
  { name: "Entei", slug: "entei", dex: 244, types: ["fire"], abilities: [] },
  { name: "Suicune", slug: "suicune", dex: 245, types: ["water"], abilities: [] },
  { name: "Larvitar", slug: "larvitar", dex: 246, types: ["rock", "ground"], abilities: [] },
  { name: "Pupitar", slug: "pupitar", dex: 247, types: ["rock", "ground"], abilities: [] },
  { name: "Tyranitar", slug: "tyranitar", dex: 248, types: ["rock", "dark"], abilities: ["Sand Stream", "Unnerve"] },
  { name: "Lugia", slug: "lugia", dex: 249, types: ["psychic", "flying"], abilities: [] },
  { name: "Ho-oh", slug: "ho-oh", dex: 250, types: ["fire", "flying"], abilities: [] },
  { name: "Celebi", slug: "celebi", dex: 251, types: ["psychic", "grass"], abilities: [] },
  { name: "Treecko", slug: "treecko", dex: 252, types: ["grass"], abilities: [] },
  { name: "Grovyle", slug: "grovyle", dex: 253, types: ["grass"], abilities: [] },
  { name: "Sceptile", slug: "sceptile", dex: 254, types: ["grass"], abilities: [] },
  { name: "Torchic", slug: "torchic", dex: 255, types: ["fire"], abilities: [] },
  { name: "Combusken", slug: "combusken", dex: 256, types: ["fire", "fighting"], abilities: [] },
  { name: "Blaziken", slug: "blaziken", dex: 257, types: ["fire", "fighting"], abilities: [] },
  { name: "Mudkip", slug: "mudkip", dex: 258, types: ["water"], abilities: [] },
  { name: "Marshtomp", slug: "marshtomp", dex: 259, types: ["water", "ground"], abilities: [] },
  { name: "Swampert", slug: "swampert", dex: 260, types: ["water", "ground"], abilities: [] },
  { name: "Poochyena", slug: "poochyena", dex: 261, types: ["dark"], abilities: [] },
  { name: "Mightyena", slug: "mightyena", dex: 262, types: ["dark"], abilities: [] },
  { name: "Zigzagoon", slug: "zigzagoon", dex: 263, types: ["normal"], abilities: [] },
  { name: "Linoone", slug: "linoone", dex: 264, types: ["normal"], abilities: [] },
  { name: "Wurmple", slug: "wurmple", dex: 265, types: ["bug"], abilities: [] },
  { name: "Silcoon", slug: "silcoon", dex: 266, types: ["bug"], abilities: [] },
  { name: "Beautifly", slug: "beautifly", dex: 267, types: ["bug", "flying"], abilities: [] },
  { name: "Cascoon", slug: "cascoon", dex: 268, types: ["bug"], abilities: [] },
  { name: "Dustox", slug: "dustox", dex: 269, types: ["bug", "poison"], abilities: [] },
  { name: "Lotad", slug: "lotad", dex: 270, types: ["water", "grass"], abilities: [] },
  { name: "Lombre", slug: "lombre", dex: 271, types: ["water", "grass"], abilities: [] },
  { name: "Ludicolo", slug: "ludicolo", dex: 272, types: ["water", "grass"], abilities: [] },
  { name: "Seedot", slug: "seedot", dex: 273, types: ["grass"], abilities: [] },
  { name: "Nuzleaf", slug: "nuzleaf", dex: 274, types: ["grass", "dark"], abilities: [] },
  { name: "Shiftry", slug: "shiftry", dex: 275, types: ["grass", "dark"], abilities: [] },
  { name: "Taillow", slug: "taillow", dex: 276, types: ["normal", "flying"], abilities: [] },
  { name: "Swellow", slug: "swellow", dex: 277, types: ["normal", "flying"], abilities: [] },
  { name: "Wingull", slug: "wingull", dex: 278, types: ["water", "flying"], abilities: [] },
  { name: "Pelipper", slug: "pelipper", dex: 279, types: ["water", "flying"], abilities: ["Keen Eye", "Drizzle", "Rain Dish"] },
  { name: "Ralts", slug: "ralts", dex: 280, types: ["psychic", "fairy"], abilities: [] },
  { name: "Kirlia", slug: "kirlia", dex: 281, types: ["psychic", "fairy"], abilities: [] },
  { name: "Gardevoir", slug: "gardevoir", dex: 282, types: ["psychic", "fairy"], abilities: ["Synchronize", "Trace", "Telepathy"] },
  { name: "Surskit", slug: "surskit", dex: 283, types: ["bug", "water"], abilities: [] },
  { name: "Masquerain", slug: "masquerain", dex: 284, types: ["bug", "flying"], abilities: [] },
  { name: "Shroomish", slug: "shroomish", dex: 285, types: ["grass"], abilities: [] },
  { name: "Breloom", slug: "breloom", dex: 286, types: ["grass", "fighting"], abilities: [] },
  { name: "Slakoth", slug: "slakoth", dex: 287, types: ["normal"], abilities: [] },
  { name: "Vigoroth", slug: "vigoroth", dex: 288, types: ["normal"], abilities: [] },
  { name: "Slaking", slug: "slaking", dex: 289, types: ["normal"], abilities: [] },
  { name: "Nincada", slug: "nincada", dex: 290, types: ["bug", "ground"], abilities: [] },
  { name: "Ninjask", slug: "ninjask", dex: 291, types: ["bug", "flying"], abilities: [] },
  { name: "Shedinja", slug: "shedinja", dex: 292, types: ["bug", "ghost"], abilities: [] },
  { name: "Whismur", slug: "whismur", dex: 293, types: ["normal"], abilities: [] },
  { name: "Loudred", slug: "loudred", dex: 294, types: ["normal"], abilities: [] },
  { name: "Exploud", slug: "exploud", dex: 295, types: ["normal"], abilities: [] },
  { name: "Makuhita", slug: "makuhita", dex: 296, types: ["fighting"], abilities: [] },
  { name: "Hariyama", slug: "hariyama", dex: 297, types: ["fighting"], abilities: [] },
  { name: "Azurill", slug: "azurill", dex: 298, types: ["normal", "fairy"], abilities: [] },
  { name: "Nosepass", slug: "nosepass", dex: 299, types: ["rock"], abilities: [] },
  { name: "Skitty", slug: "skitty", dex: 300, types: ["normal"], abilities: [] },
  { name: "Delcatty", slug: "delcatty", dex: 301, types: ["normal"], abilities: [] },
  { name: "Sableye", slug: "sableye", dex: 302, types: ["dark", "ghost"], abilities: [] },
  { name: "Mawile", slug: "mawile", dex: 303, types: ["steel", "fairy"], abilities: [] },
  { name: "Aron", slug: "aron", dex: 304, types: ["steel", "rock"], abilities: [] },
  { name: "Lairon", slug: "lairon", dex: 305, types: ["steel", "rock"], abilities: [] },
  { name: "Aggron", slug: "aggron", dex: 306, types: ["steel", "rock"], abilities: [] },
  { name: "Meditite", slug: "meditite", dex: 307, types: ["fighting", "psychic"], abilities: [] },
  { name: "Medicham", slug: "medicham", dex: 308, types: ["fighting", "psychic"], abilities: [] },
  { name: "Electrike", slug: "electrike", dex: 309, types: ["electric"], abilities: [] },
  { name: "Manectric", slug: "manectric", dex: 310, types: ["electric"], abilities: [] },
  { name: "Plusle", slug: "plusle", dex: 311, types: ["electric"], abilities: [] },
  { name: "Minun", slug: "minun", dex: 312, types: ["electric"], abilities: [] },
  { name: "Volbeat", slug: "volbeat", dex: 313, types: ["bug"], abilities: [] },
  { name: "Illumise", slug: "illumise", dex: 314, types: ["bug"], abilities: [] },
  { name: "Roselia", slug: "roselia", dex: 315, types: ["grass", "poison"], abilities: [] },
  { name: "Gulpin", slug: "gulpin", dex: 316, types: ["poison"], abilities: [] },
  { name: "Swalot", slug: "swalot", dex: 317, types: ["poison"], abilities: [] },
  { name: "Carvanha", slug: "carvanha", dex: 318, types: ["water", "dark"], abilities: [] },
  { name: "Sharpedo", slug: "sharpedo", dex: 319, types: ["water", "dark"], abilities: [] },
  { name: "Wailmer", slug: "wailmer", dex: 320, types: ["water"], abilities: [] },
  { name: "Wailord", slug: "wailord", dex: 321, types: ["water"], abilities: [] },
  { name: "Numel", slug: "numel", dex: 322, types: ["fire", "ground"], abilities: [] },
  { name: "Camerupt", slug: "camerupt", dex: 323, types: ["fire", "ground"], abilities: [] },
  { name: "Torkoal", slug: "torkoal", dex: 324, types: ["fire"], abilities: ["White Smoke", "Drought", "Shell Armor"] },
  { name: "Spoink", slug: "spoink", dex: 325, types: ["psychic"], abilities: [] },
  { name: "Grumpig", slug: "grumpig", dex: 326, types: ["psychic"], abilities: [] },
  { name: "Spinda", slug: "spinda", dex: 327, types: ["normal"], abilities: [] },
  { name: "Trapinch", slug: "trapinch", dex: 328, types: ["ground"], abilities: [] },
  { name: "Vibrava", slug: "vibrava", dex: 329, types: ["ground", "dragon"], abilities: [] },
  { name: "Flygon", slug: "flygon", dex: 330, types: ["ground", "dragon"], abilities: [] },
  { name: "Cacnea", slug: "cacnea", dex: 331, types: ["grass"], abilities: [] },
  { name: "Cacturne", slug: "cacturne", dex: 332, types: ["grass", "dark"], abilities: [] },
  { name: "Swablu", slug: "swablu", dex: 333, types: ["normal", "flying"], abilities: [] },
  { name: "Altaria", slug: "altaria", dex: 334, types: ["dragon", "flying"], abilities: [] },
  { name: "Zangoose", slug: "zangoose", dex: 335, types: ["normal"], abilities: [] },
  { name: "Seviper", slug: "seviper", dex: 336, types: ["poison"], abilities: [] },
  { name: "Lunatone", slug: "lunatone", dex: 337, types: ["rock", "psychic"], abilities: [] },
  { name: "Solrock", slug: "solrock", dex: 338, types: ["rock", "psychic"], abilities: [] },
  { name: "Barboach", slug: "barboach", dex: 339, types: ["water", "ground"], abilities: [] },
  { name: "Whiscash", slug: "whiscash", dex: 340, types: ["water", "ground"], abilities: [] },
  { name: "Corphish", slug: "corphish", dex: 341, types: ["water"], abilities: [] },
  { name: "Crawdaunt", slug: "crawdaunt", dex: 342, types: ["water", "dark"], abilities: [] },
  { name: "Baltoy", slug: "baltoy", dex: 343, types: ["ground", "psychic"], abilities: [] },
  { name: "Claydol", slug: "claydol", dex: 344, types: ["ground", "psychic"], abilities: [] },
  { name: "Lileep", slug: "lileep", dex: 345, types: ["rock", "grass"], abilities: [] },
  { name: "Cradily", slug: "cradily", dex: 346, types: ["rock", "grass"], abilities: [] },
  { name: "Anorith", slug: "anorith", dex: 347, types: ["rock", "bug"], abilities: [] },
  { name: "Armaldo", slug: "armaldo", dex: 348, types: ["rock", "bug"], abilities: [] },
  { name: "Feebas", slug: "feebas", dex: 349, types: ["water"], abilities: [] },
  { name: "Milotic", slug: "milotic", dex: 350, types: ["water"], abilities: [] },
  { name: "Castform", slug: "castform", dex: 351, types: ["normal"], abilities: [] },
  { name: "Kecleon", slug: "kecleon", dex: 352, types: ["normal"], abilities: [] },
  { name: "Shuppet", slug: "shuppet", dex: 353, types: ["ghost"], abilities: [] },
  { name: "Banette", slug: "banette", dex: 354, types: ["ghost"], abilities: [] },
  { name: "Duskull", slug: "duskull", dex: 355, types: ["ghost"], abilities: [] },
  { name: "Dusclops", slug: "dusclops", dex: 356, types: ["ghost"], abilities: [] },
  { name: "Tropius", slug: "tropius", dex: 357, types: ["grass", "flying"], abilities: [] },
  { name: "Chimecho", slug: "chimecho", dex: 358, types: ["psychic"], abilities: [] },
  { name: "Absol", slug: "absol", dex: 359, types: ["dark"], abilities: [] },
  { name: "Wynaut", slug: "wynaut", dex: 360, types: ["psychic"], abilities: [] },
  { name: "Snorunt", slug: "snorunt", dex: 361, types: ["ice"], abilities: [] },
  { name: "Glalie", slug: "glalie", dex: 362, types: ["ice"], abilities: [] },
  { name: "Spheal", slug: "spheal", dex: 363, types: ["ice", "water"], abilities: [] },
  { name: "Sealeo", slug: "sealeo", dex: 364, types: ["ice", "water"], abilities: [] },
  { name: "Walrein", slug: "walrein", dex: 365, types: ["ice", "water"], abilities: [] },
  { name: "Clamperl", slug: "clamperl", dex: 366, types: ["water"], abilities: [] },
  { name: "Huntail", slug: "huntail", dex: 367, types: ["water"], abilities: [] },
  { name: "Gorebyss", slug: "gorebyss", dex: 368, types: ["water"], abilities: [] },
  { name: "Relicanth", slug: "relicanth", dex: 369, types: ["water", "rock"], abilities: [] },
  { name: "Luvdisc", slug: "luvdisc", dex: 370, types: ["water"], abilities: [] },
  { name: "Bagon", slug: "bagon", dex: 371, types: ["dragon"], abilities: [] },
  { name: "Shelgon", slug: "shelgon", dex: 372, types: ["dragon"], abilities: [] },
  { name: "Salamence", slug: "salamence", dex: 373, types: ["dragon", "flying"], abilities: [] },
  { name: "Beldum", slug: "beldum", dex: 374, types: ["steel", "psychic"], abilities: [] },
  { name: "Metang", slug: "metang", dex: 375, types: ["steel", "psychic"], abilities: [] },
  { name: "Metagross", slug: "metagross", dex: 376, types: ["steel", "psychic"], abilities: ["Clear Body", "Light Metal"] },
  { name: "Regirock", slug: "regirock", dex: 377, types: ["rock"], abilities: [] },
  { name: "Regice", slug: "regice", dex: 378, types: ["ice"], abilities: [] },
  { name: "Registeel", slug: "registeel", dex: 379, types: ["steel"], abilities: [] },
  { name: "Latias", slug: "latias", dex: 380, types: ["dragon", "psychic"], abilities: [] },
  { name: "Latios", slug: "latios", dex: 381, types: ["dragon", "psychic"], abilities: [] },
  { name: "Kyogre", slug: "kyogre", dex: 382, types: ["water"], abilities: ["Drizzle"] },
  { name: "Groudon", slug: "groudon", dex: 383, types: ["ground"], abilities: ["Drought"] },
  { name: "Rayquaza", slug: "rayquaza", dex: 384, types: ["dragon", "flying"], abilities: [] },
  { name: "Jirachi", slug: "jirachi", dex: 385, types: ["steel", "psychic"], abilities: [] },
  { name: "Deoxys", slug: "deoxys", dex: 386, types: ["psychic"], abilities: [] },
  { name: "Turtwig", slug: "turtwig", dex: 387, types: ["grass"], abilities: [] },
  { name: "Grotle", slug: "grotle", dex: 388, types: ["grass"], abilities: [] },
  { name: "Torterra", slug: "torterra", dex: 389, types: ["grass", "ground"], abilities: [] },
  { name: "Chimchar", slug: "chimchar", dex: 390, types: ["fire"], abilities: [] },
  { name: "Monferno", slug: "monferno", dex: 391, types: ["fire", "fighting"], abilities: [] },
  { name: "Infernape", slug: "infernape", dex: 392, types: ["fire", "fighting"], abilities: [] },
  { name: "Piplup", slug: "piplup", dex: 393, types: ["water"], abilities: [] },
  { name: "Prinplup", slug: "prinplup", dex: 394, types: ["water"], abilities: [] },
  { name: "Empoleon", slug: "empoleon", dex: 395, types: ["water", "steel"], abilities: [] },
  { name: "Starly", slug: "starly", dex: 396, types: ["normal", "flying"], abilities: [] },
  { name: "Staravia", slug: "staravia", dex: 397, types: ["normal", "flying"], abilities: [] },
  { name: "Staraptor", slug: "staraptor", dex: 398, types: ["normal", "flying"], abilities: [] },
  { name: "Bidoof", slug: "bidoof", dex: 399, types: ["normal"], abilities: [] },
  { name: "Bibarel", slug: "bibarel", dex: 400, types: ["normal", "water"], abilities: [] },
  { name: "Kricketot", slug: "kricketot", dex: 401, types: ["bug"], abilities: [] },
  { name: "Kricketune", slug: "kricketune", dex: 402, types: ["bug"], abilities: [] },
  { name: "Shinx", slug: "shinx", dex: 403, types: ["electric"], abilities: [] },
  { name: "Luxio", slug: "luxio", dex: 404, types: ["electric"], abilities: [] },
  { name: "Luxray", slug: "luxray", dex: 405, types: ["electric"], abilities: [] },
  { name: "Budew", slug: "budew", dex: 406, types: ["grass", "poison"], abilities: [] },
  { name: "Roserade", slug: "roserade", dex: 407, types: ["grass", "poison"], abilities: [] },
  { name: "Cranidos", slug: "cranidos", dex: 408, types: ["rock"], abilities: [] },
  { name: "Rampardos", slug: "rampardos", dex: 409, types: ["rock"], abilities: [] },
  { name: "Shieldon", slug: "shieldon", dex: 410, types: ["rock", "steel"], abilities: [] },
  { name: "Bastiodon", slug: "bastiodon", dex: 411, types: ["rock", "steel"], abilities: [] },
  { name: "Burmy", slug: "burmy", dex: 412, types: ["bug"], abilities: [] },
  { name: "Wormadam", slug: "wormadam", dex: 413, types: ["bug", "grass"], abilities: [] },
  { name: "Mothim", slug: "mothim", dex: 414, types: ["bug", "flying"], abilities: [] },
  { name: "Combee", slug: "combee", dex: 415, types: ["bug", "flying"], abilities: [] },
  { name: "Vespiquen", slug: "vespiquen", dex: 416, types: ["bug", "flying"], abilities: [] },
  { name: "Pachirisu", slug: "pachirisu", dex: 417, types: ["electric"], abilities: [] },
  { name: "Buizel", slug: "buizel", dex: 418, types: ["water"], abilities: [] },
  { name: "Floatzel", slug: "floatzel", dex: 419, types: ["water"], abilities: [] },
  { name: "Cherubi", slug: "cherubi", dex: 420, types: ["grass"], abilities: [] },
  { name: "Cherrim", slug: "cherrim", dex: 421, types: ["grass"], abilities: [] },
  { name: "Shellos", slug: "shellos", dex: 422, types: ["water"], abilities: [] },
  { name: "Gastrodon", slug: "gastrodon", dex: 423, types: ["water", "ground"], abilities: ["Sticky Hold", "Storm Drain", "Sand Force"] },
  { name: "Ambipom", slug: "ambipom", dex: 424, types: ["normal"], abilities: [] },
  { name: "Drifloon", slug: "drifloon", dex: 425, types: ["ghost", "flying"], abilities: [] },
  { name: "Drifblim", slug: "drifblim", dex: 426, types: ["ghost", "flying"], abilities: [] },
  { name: "Buneary", slug: "buneary", dex: 427, types: ["normal"], abilities: [] },
  { name: "Lopunny", slug: "lopunny", dex: 428, types: ["normal"], abilities: [] },
  { name: "Mismagius", slug: "mismagius", dex: 429, types: ["ghost"], abilities: [] },
  { name: "Honchkrow", slug: "honchkrow", dex: 430, types: ["dark", "flying"], abilities: [] },
  { name: "Glameow", slug: "glameow", dex: 431, types: ["normal"], abilities: [] },
  { name: "Purugly", slug: "purugly", dex: 432, types: ["normal"], abilities: [] },
  { name: "Chingling", slug: "chingling", dex: 433, types: ["psychic"], abilities: [] },
  { name: "Stunky", slug: "stunky", dex: 434, types: ["poison", "dark"], abilities: [] },
  { name: "Skuntank", slug: "skuntank", dex: 435, types: ["poison", "dark"], abilities: [] },
  { name: "Bronzor", slug: "bronzor", dex: 436, types: ["steel", "psychic"], abilities: [] },
  { name: "Bronzong", slug: "bronzong", dex: 437, types: ["steel", "psychic"], abilities: [] },
  { name: "Bonsly", slug: "bonsly", dex: 438, types: ["rock"], abilities: [] },
  { name: "Mime Jr.", slug: "mime-jr", dex: 439, types: ["psychic", "fairy"], abilities: [] },
  { name: "Happiny", slug: "happiny", dex: 440, types: ["normal"], abilities: [] },
  { name: "Chatot", slug: "chatot", dex: 441, types: ["normal", "flying"], abilities: [] },
  { name: "Spiritomb", slug: "spiritomb", dex: 442, types: ["ghost", "dark"], abilities: [] },
  { name: "Gible", slug: "gible", dex: 443, types: ["dragon", "ground"], abilities: [] },
  { name: "Gabite", slug: "gabite", dex: 444, types: ["dragon", "ground"], abilities: [] },
  { name: "Garchomp", slug: "garchomp", dex: 445, types: ["dragon", "ground"], abilities: ["Sand Veil", "Rough Skin"] },
  { name: "Munchlax", slug: "munchlax", dex: 446, types: ["normal"], abilities: [] },
  { name: "Riolu", slug: "riolu", dex: 447, types: ["fighting"], abilities: [] },
  { name: "Lucario", slug: "lucario", dex: 448, types: ["fighting", "steel"], abilities: ["Steadfast", "Inner Focus", "Justified"] },
  { name: "Hippopotas", slug: "hippopotas", dex: 449, types: ["ground"], abilities: [] },
  { name: "Hippowdon", slug: "hippowdon", dex: 450, types: ["ground"], abilities: [] },
  { name: "Skorupi", slug: "skorupi", dex: 451, types: ["poison", "bug"], abilities: [] },
  { name: "Drapion", slug: "drapion", dex: 452, types: ["poison", "dark"], abilities: [] },
  { name: "Croagunk", slug: "croagunk", dex: 453, types: ["poison", "fighting"], abilities: [] },
  { name: "Toxicroak", slug: "toxicroak", dex: 454, types: ["poison", "fighting"], abilities: [] },
  { name: "Carnivine", slug: "carnivine", dex: 455, types: ["grass"], abilities: [] },
  { name: "Finneon", slug: "finneon", dex: 456, types: ["water"], abilities: [] },
  { name: "Lumineon", slug: "lumineon", dex: 457, types: ["water"], abilities: [] },
  { name: "Mantyke", slug: "mantyke", dex: 458, types: ["water", "flying"], abilities: [] },
  { name: "Snover", slug: "snover", dex: 459, types: ["grass", "ice"], abilities: [] },
  { name: "Abomasnow", slug: "abomasnow", dex: 460, types: ["grass", "ice"], abilities: [] },
  { name: "Weavile", slug: "weavile", dex: 461, types: ["dark", "ice"], abilities: [] },
  { name: "Magnezone", slug: "magnezone", dex: 462, types: ["electric", "steel"], abilities: [] },
  { name: "Lickilicky", slug: "lickilicky", dex: 463, types: ["normal"], abilities: [] },
  { name: "Rhyperior", slug: "rhyperior", dex: 464, types: ["ground", "rock"], abilities: [] },
  { name: "Tangrowth", slug: "tangrowth", dex: 465, types: ["grass"], abilities: [] },
  { name: "Electivire", slug: "electivire", dex: 466, types: ["electric"], abilities: [] },
  { name: "Magmortar", slug: "magmortar", dex: 467, types: ["fire"], abilities: [] },
  { name: "Togekiss", slug: "togekiss", dex: 468, types: ["fairy", "flying"], abilities: [] },
  { name: "Yanmega", slug: "yanmega", dex: 469, types: ["bug", "flying"], abilities: [] },
  { name: "Leafeon", slug: "leafeon", dex: 470, types: ["grass"], abilities: [] },
  { name: "Glaceon", slug: "glaceon", dex: 471, types: ["ice"], abilities: [] },
  { name: "Gliscor", slug: "gliscor", dex: 472, types: ["ground", "flying"], abilities: [] },
  { name: "Mamoswine", slug: "mamoswine", dex: 473, types: ["ice", "ground"], abilities: [] },
  { name: "Porygon-Z", slug: "porygon-z", dex: 474, types: ["normal"], abilities: ["Adaptability", "Download", "Analytic"] },
  { name: "Gallade", slug: "gallade", dex: 475, types: ["psychic", "fighting"], abilities: ["Steadfast", "Sharpness", "Justified"] },
  { name: "Probopass", slug: "probopass", dex: 476, types: ["rock", "steel"], abilities: [] },
  { name: "Dusknoir", slug: "dusknoir", dex: 477, types: ["ghost"], abilities: [] },
  { name: "Froslass", slug: "froslass", dex: 478, types: ["ice", "ghost"], abilities: [] },
  { name: "Rotom", slug: "rotom", dex: 479, types: ["electric", "ghost"], abilities: [] },
  { name: "Uxie", slug: "uxie", dex: 480, types: ["psychic"], abilities: [] },
  { name: "Mesprit", slug: "mesprit", dex: 481, types: ["psychic"], abilities: [] },
  { name: "Azelf", slug: "azelf", dex: 482, types: ["psychic"], abilities: [] },
  { name: "Dialga", slug: "dialga", dex: 483, types: ["steel", "dragon"], abilities: [] },
  { name: "Palkia", slug: "palkia", dex: 484, types: ["water", "dragon"], abilities: [] },
  { name: "Heatran", slug: "heatran", dex: 485, types: ["fire", "steel"], abilities: ["Flash Fire", "Flame Body"] },
  { name: "Regigigas", slug: "regigigas", dex: 486, types: ["normal"], abilities: [] },
  { name: "Giratina", slug: "giratina", dex: 487, types: ["ghost", "dragon"], abilities: [] },
  { name: "Cresselia", slug: "cresselia", dex: 488, types: ["psychic"], abilities: ["Levitate"] },
  { name: "Phione", slug: "phione", dex: 489, types: ["water"], abilities: [] },
  { name: "Manaphy", slug: "manaphy", dex: 490, types: ["water"], abilities: [] },
  { name: "Darkrai", slug: "darkrai", dex: 491, types: ["dark"], abilities: [] },
  { name: "Shaymin", slug: "shaymin", dex: 492, types: ["grass"], abilities: [] },
  { name: "Arceus", slug: "arceus", dex: 493, types: ["normal"], abilities: [] },
  { name: "Victini", slug: "victini", dex: 494, types: ["psychic", "fire"], abilities: [] },
  { name: "Snivy", slug: "snivy", dex: 495, types: ["grass"], abilities: [] },
  { name: "Servine", slug: "servine", dex: 496, types: ["grass"], abilities: [] },
  { name: "Serperior", slug: "serperior", dex: 497, types: ["grass"], abilities: [] },
  { name: "Tepig", slug: "tepig", dex: 498, types: ["fire"], abilities: [] },
  { name: "Pignite", slug: "pignite", dex: 499, types: ["fire", "fighting"], abilities: [] },
  { name: "Emboar", slug: "emboar", dex: 500, types: ["fire", "fighting"], abilities: [] },
  { name: "Oshawott", slug: "oshawott", dex: 501, types: ["water"], abilities: [] },
  { name: "Dewott", slug: "dewott", dex: 502, types: ["water"], abilities: [] },
  { name: "Samurott", slug: "samurott", dex: 503, types: ["water"], abilities: [] },
  { name: "Patrat", slug: "patrat", dex: 504, types: ["normal"], abilities: [] },
  { name: "Watchog", slug: "watchog", dex: 505, types: ["normal"], abilities: [] },
  { name: "Lillipup", slug: "lillipup", dex: 506, types: ["normal"], abilities: [] },
  { name: "Herdier", slug: "herdier", dex: 507, types: ["normal"], abilities: [] },
  { name: "Stoutland", slug: "stoutland", dex: 508, types: ["normal"], abilities: [] },
  { name: "Purrloin", slug: "purrloin", dex: 509, types: ["dark"], abilities: [] },
  { name: "Liepard", slug: "liepard", dex: 510, types: ["dark"], abilities: [] },
  { name: "Pansage", slug: "pansage", dex: 511, types: ["grass"], abilities: [] },
  { name: "Simisage", slug: "simisage", dex: 512, types: ["grass"], abilities: [] },
  { name: "Pansear", slug: "pansear", dex: 513, types: ["fire"], abilities: [] },
  { name: "Simisear", slug: "simisear", dex: 514, types: ["fire"], abilities: [] },
  { name: "Panpour", slug: "panpour", dex: 515, types: ["water"], abilities: [] },
  { name: "Simipour", slug: "simipour", dex: 516, types: ["water"], abilities: [] },
  { name: "Munna", slug: "munna", dex: 517, types: ["psychic"], abilities: [] },
  { name: "Musharna", slug: "musharna", dex: 518, types: ["psychic"], abilities: [] },
  { name: "Pidove", slug: "pidove", dex: 519, types: ["normal", "flying"], abilities: [] },
  { name: "Tranquill", slug: "tranquill", dex: 520, types: ["normal", "flying"], abilities: [] },
  { name: "Unfezant", slug: "unfezant", dex: 521, types: ["normal", "flying"], abilities: [] },
  { name: "Blitzle", slug: "blitzle", dex: 522, types: ["electric"], abilities: [] },
  { name: "Zebstrika", slug: "zebstrika", dex: 523, types: ["electric"], abilities: [] },
  { name: "Roggenrola", slug: "roggenrola", dex: 524, types: ["rock"], abilities: [] },
  { name: "Boldore", slug: "boldore", dex: 525, types: ["rock"], abilities: [] },
  { name: "Gigalith", slug: "gigalith", dex: 526, types: ["rock"], abilities: [] },
  { name: "Woobat", slug: "woobat", dex: 527, types: ["psychic", "flying"], abilities: [] },
  { name: "Swoobat", slug: "swoobat", dex: 528, types: ["psychic", "flying"], abilities: [] },
  { name: "Drilbur", slug: "drilbur", dex: 529, types: ["ground"], abilities: [] },
  { name: "Excadrill", slug: "excadrill", dex: 530, types: ["ground", "steel"], abilities: ["Sand Rush", "Sand Force", "Mold Breaker"] },
  { name: "Audino", slug: "audino", dex: 531, types: ["normal"], abilities: [] },
  { name: "Timburr", slug: "timburr", dex: 532, types: ["fighting"], abilities: [] },
  { name: "Gurdurr", slug: "gurdurr", dex: 533, types: ["fighting"], abilities: [] },
  { name: "Conkeldurr", slug: "conkeldurr", dex: 534, types: ["fighting"], abilities: [] },
  { name: "Tympole", slug: "tympole", dex: 535, types: ["water"], abilities: [] },
  { name: "Palpitoad", slug: "palpitoad", dex: 536, types: ["water", "ground"], abilities: [] },
  { name: "Seismitoad", slug: "seismitoad", dex: 537, types: ["water", "ground"], abilities: [] },
  { name: "Throh", slug: "throh", dex: 538, types: ["fighting"], abilities: [] },
  { name: "Sawk", slug: "sawk", dex: 539, types: ["fighting"], abilities: [] },
  { name: "Sewaddle", slug: "sewaddle", dex: 540, types: ["bug", "grass"], abilities: [] },
  { name: "Swadloon", slug: "swadloon", dex: 541, types: ["bug", "grass"], abilities: [] },
  { name: "Leavanny", slug: "leavanny", dex: 542, types: ["bug", "grass"], abilities: [] },
  { name: "Venipede", slug: "venipede", dex: 543, types: ["bug", "poison"], abilities: [] },
  { name: "Whirlipede", slug: "whirlipede", dex: 544, types: ["bug", "poison"], abilities: [] },
  { name: "Scolipede", slug: "scolipede", dex: 545, types: ["bug", "poison"], abilities: [] },
  { name: "Cottonee", slug: "cottonee", dex: 546, types: ["grass", "fairy"], abilities: [] },
  { name: "Whimsicott", slug: "whimsicott", dex: 547, types: ["grass", "fairy"], abilities: ["Prankster", "Infiltrator", "Chlorophyll"] },
  { name: "Petilil", slug: "petilil", dex: 548, types: ["grass"], abilities: [] },
  { name: "Lilligant", slug: "lilligant", dex: 549, types: ["grass"], abilities: [] },
  { name: "Basculin", slug: "basculin", dex: 550, types: ["water"], abilities: [] },
  { name: "Sandile", slug: "sandile", dex: 551, types: ["ground", "dark"], abilities: [] },
  { name: "Krokorok", slug: "krokorok", dex: 552, types: ["ground", "dark"], abilities: [] },
  { name: "Krookodile", slug: "krookodile", dex: 553, types: ["ground", "dark"], abilities: [] },
  { name: "Darumaka", slug: "darumaka", dex: 554, types: ["fire"], abilities: [] },
  { name: "Darmanitan", slug: "darmanitan", dex: 555, types: ["fire"], abilities: [] },
  { name: "Maractus", slug: "maractus", dex: 556, types: ["grass"], abilities: [] },
  { name: "Dwebble", slug: "dwebble", dex: 557, types: ["bug", "rock"], abilities: [] },
  { name: "Crustle", slug: "crustle", dex: 558, types: ["bug", "rock"], abilities: [] },
  { name: "Scraggy", slug: "scraggy", dex: 559, types: ["dark", "fighting"], abilities: [] },
  { name: "Scrafty", slug: "scrafty", dex: 560, types: ["dark", "fighting"], abilities: [] },
  { name: "Sigilyph", slug: "sigilyph", dex: 561, types: ["psychic", "flying"], abilities: [] },
  { name: "Yamask", slug: "yamask", dex: 562, types: ["ghost"], abilities: [] },
  { name: "Cofagrigus", slug: "cofagrigus", dex: 563, types: ["ghost"], abilities: [] },
  { name: "Tirtouga", slug: "tirtouga", dex: 564, types: ["water", "rock"], abilities: [] },
  { name: "Carracosta", slug: "carracosta", dex: 565, types: ["water", "rock"], abilities: [] },
  { name: "Archen", slug: "archen", dex: 566, types: ["rock", "flying"], abilities: [] },
  { name: "Archeops", slug: "archeops", dex: 567, types: ["rock", "flying"], abilities: [] },
  { name: "Trubbish", slug: "trubbish", dex: 568, types: ["poison"], abilities: [] },
  { name: "Garbodor", slug: "garbodor", dex: 569, types: ["poison"], abilities: [] },
  { name: "Zorua", slug: "zorua", dex: 570, types: ["dark"], abilities: [] },
  { name: "Zoroark", slug: "zoroark", dex: 571, types: ["dark"], abilities: [] },
  { name: "Minccino", slug: "minccino", dex: 572, types: ["normal"], abilities: [] },
  { name: "Cinccino", slug: "cinccino", dex: 573, types: ["normal"], abilities: [] },
  { name: "Gothita", slug: "gothita", dex: 574, types: ["psychic"], abilities: [] },
  { name: "Gothorita", slug: "gothorita", dex: 575, types: ["psychic"], abilities: [] },
  { name: "Gothitelle", slug: "gothitelle", dex: 576, types: ["psychic"], abilities: [] },
  { name: "Solosis", slug: "solosis", dex: 577, types: ["psychic"], abilities: [] },
  { name: "Duosion", slug: "duosion", dex: 578, types: ["psychic"], abilities: [] },
  { name: "Reuniclus", slug: "reuniclus", dex: 579, types: ["psychic"], abilities: [] },
  { name: "Ducklett", slug: "ducklett", dex: 580, types: ["water", "flying"], abilities: [] },
  { name: "Swanna", slug: "swanna", dex: 581, types: ["water", "flying"], abilities: [] },
  { name: "Vanillite", slug: "vanillite", dex: 582, types: ["ice"], abilities: [] },
  { name: "Vanillish", slug: "vanillish", dex: 583, types: ["ice"], abilities: [] },
  { name: "Vanilluxe", slug: "vanilluxe", dex: 584, types: ["ice"], abilities: [] },
  { name: "Deerling", slug: "deerling", dex: 585, types: ["normal", "grass"], abilities: [] },
  { name: "Sawsbuck", slug: "sawsbuck", dex: 586, types: ["normal", "grass"], abilities: [] },
  { name: "Emolga", slug: "emolga", dex: 587, types: ["electric", "flying"], abilities: [] },
  { name: "Karrablast", slug: "karrablast", dex: 588, types: ["bug"], abilities: [] },
  { name: "Escavalier", slug: "escavalier", dex: 589, types: ["bug", "steel"], abilities: [] },
  { name: "Foongus", slug: "foongus", dex: 590, types: ["grass", "poison"], abilities: [] },
  { name: "Amoonguss", slug: "amoonguss", dex: 591, types: ["grass", "poison"], abilities: ["Effect Spore", "Regenerator"] },
  { name: "Frillish", slug: "frillish", dex: 592, types: ["water", "ghost"], abilities: [] },
  { name: "Jellicent", slug: "jellicent", dex: 593, types: ["water", "ghost"], abilities: [] },
  { name: "Alomomola", slug: "alomomola", dex: 594, types: ["water"], abilities: [] },
  { name: "Joltik", slug: "joltik", dex: 595, types: ["bug", "electric"], abilities: [] },
  { name: "Galvantula", slug: "galvantula", dex: 596, types: ["bug", "electric"], abilities: [] },
  { name: "Ferroseed", slug: "ferroseed", dex: 597, types: ["grass", "steel"], abilities: [] },
  { name: "Ferrothorn", slug: "ferrothorn", dex: 598, types: ["grass", "steel"], abilities: [] },
  { name: "Klink", slug: "klink", dex: 599, types: ["steel"], abilities: [] },
  { name: "Klang", slug: "klang", dex: 600, types: ["steel"], abilities: [] },
  { name: "Klinklang", slug: "klinklang", dex: 601, types: ["steel"], abilities: [] },
  { name: "Tynamo", slug: "tynamo", dex: 602, types: ["electric"], abilities: [] },
  { name: "Eelektrik", slug: "eelektrik", dex: 603, types: ["electric"], abilities: [] },
  { name: "Eelektross", slug: "eelektross", dex: 604, types: ["electric"], abilities: [] },
  { name: "Elgyem", slug: "elgyem", dex: 605, types: ["psychic"], abilities: [] },
  { name: "Beheeyem", slug: "beheeyem", dex: 606, types: ["psychic"], abilities: [] },
  { name: "Litwick", slug: "litwick", dex: 607, types: ["ghost", "fire"], abilities: [] },
  { name: "Lampent", slug: "lampent", dex: 608, types: ["ghost", "fire"], abilities: [] },
  { name: "Chandelure", slug: "chandelure", dex: 609, types: ["ghost", "fire"], abilities: ["Flash Fire", "Flame Body", "Infiltrator"] },
  { name: "Axew", slug: "axew", dex: 610, types: ["dragon"], abilities: [] },
  { name: "Fraxure", slug: "fraxure", dex: 611, types: ["dragon"], abilities: [] },
  { name: "Haxorus", slug: "haxorus", dex: 612, types: ["dragon"], abilities: [] },
  { name: "Cubchoo", slug: "cubchoo", dex: 613, types: ["ice"], abilities: [] },
  { name: "Beartic", slug: "beartic", dex: 614, types: ["ice"], abilities: [] },
  { name: "Cryogonal", slug: "cryogonal", dex: 615, types: ["ice"], abilities: [] },
  { name: "Shelmet", slug: "shelmet", dex: 616, types: ["bug"], abilities: [] },
  { name: "Accelgor", slug: "accelgor", dex: 617, types: ["bug"], abilities: [] },
  { name: "Stunfisk", slug: "stunfisk", dex: 618, types: ["ground", "electric"], abilities: [] },
  { name: "Mienfoo", slug: "mienfoo", dex: 619, types: ["fighting"], abilities: [] },
  { name: "Mienshao", slug: "mienshao", dex: 620, types: ["fighting"], abilities: [] },
  { name: "Druddigon", slug: "druddigon", dex: 621, types: ["dragon"], abilities: [] },
  { name: "Golett", slug: "golett", dex: 622, types: ["ground", "ghost"], abilities: [] },
  { name: "Golurk", slug: "golurk", dex: 623, types: ["ground", "ghost"], abilities: [] },
  { name: "Pawniard", slug: "pawniard", dex: 624, types: ["dark", "steel"], abilities: [] },
  { name: "Bisharp", slug: "bisharp", dex: 625, types: ["dark", "steel"], abilities: [] },
  { name: "Bouffalant", slug: "bouffalant", dex: 626, types: ["normal"], abilities: [] },
  { name: "Rufflet", slug: "rufflet", dex: 627, types: ["normal", "flying"], abilities: [] },
  { name: "Braviary", slug: "braviary", dex: 628, types: ["normal", "flying"], abilities: [] },
  { name: "Vullaby", slug: "vullaby", dex: 629, types: ["dark", "flying"], abilities: [] },
  { name: "Mandibuzz", slug: "mandibuzz", dex: 630, types: ["dark", "flying"], abilities: [] },
  { name: "Heatmor", slug: "heatmor", dex: 631, types: ["fire"], abilities: [] },
  { name: "Durant", slug: "durant", dex: 632, types: ["bug", "steel"], abilities: [] },
  { name: "Deino", slug: "deino", dex: 633, types: ["dark", "dragon"], abilities: [] },
  { name: "Zweilous", slug: "zweilous", dex: 634, types: ["dark", "dragon"], abilities: [] },
  { name: "Hydreigon", slug: "hydreigon", dex: 635, types: ["dark", "dragon"], abilities: ["Levitate"] },
  { name: "Larvesta", slug: "larvesta", dex: 636, types: ["bug", "fire"], abilities: [] },
  { name: "Volcarona", slug: "volcarona", dex: 637, types: ["bug", "fire"], abilities: ["Flame Body", "Swarm"] },
  { name: "Cobalion", slug: "cobalion", dex: 638, types: ["steel", "fighting"], abilities: [] },
  { name: "Terrakion", slug: "terrakion", dex: 639, types: ["rock", "fighting"], abilities: [] },
  { name: "Virizion", slug: "virizion", dex: 640, types: ["grass", "fighting"], abilities: [] },
  { name: "Tornadus", slug: "tornadus", dex: 641, types: ["flying"], abilities: ["Prankster", "Defiant"] },
  { name: "Thundurus", slug: "thundurus", dex: 642, types: ["electric", "flying"], abilities: ["Prankster", "Defiant"] },
  { name: "Reshiram", slug: "reshiram", dex: 643, types: ["dragon", "fire"], abilities: [] },
  { name: "Zekrom", slug: "zekrom", dex: 644, types: ["dragon", "electric"], abilities: [] },
  { name: "Landorus", slug: "landorus", dex: 645, types: ["ground", "flying"], abilities: ["Sand Force", "Sheer Force"] },
  { name: "Kyurem", slug: "kyurem", dex: 646, types: ["dragon", "ice"], abilities: [] },
  { name: "Keldeo", slug: "keldeo", dex: 647, types: ["water", "fighting"], abilities: [] },
  { name: "Meloetta", slug: "meloetta", dex: 648, types: ["normal", "psychic"], abilities: [] },
  { name: "Genesect", slug: "genesect", dex: 649, types: ["bug", "steel"], abilities: [] },
  { name: "Chespin", slug: "chespin", dex: 650, types: ["grass"], abilities: [] },
  { name: "Quilladin", slug: "quilladin", dex: 651, types: ["grass"], abilities: [] },
  { name: "Chesnaught", slug: "chesnaught", dex: 652, types: ["grass", "fighting"], abilities: [] },
  { name: "Fennekin", slug: "fennekin", dex: 653, types: ["fire"], abilities: [] },
  { name: "Braixen", slug: "braixen", dex: 654, types: ["fire"], abilities: [] },
  { name: "Delphox", slug: "delphox", dex: 655, types: ["fire", "psychic"], abilities: [] },
  { name: "Froakie", slug: "froakie", dex: 656, types: ["water"], abilities: [] },
  { name: "Frogadier", slug: "frogadier", dex: 657, types: ["water"], abilities: [] },
  { name: "Greninja", slug: "greninja", dex: 658, types: ["water", "dark"], abilities: [] },
  { name: "Bunnelby", slug: "bunnelby", dex: 659, types: ["normal"], abilities: [] },
  { name: "Diggersby", slug: "diggersby", dex: 660, types: ["normal", "ground"], abilities: [] },
  { name: "Fletchling", slug: "fletchling", dex: 661, types: ["normal", "flying"], abilities: [] },
  { name: "Fletchinder", slug: "fletchinder", dex: 662, types: ["fire", "flying"], abilities: [] },
  { name: "Talonflame", slug: "talonflame", dex: 663, types: ["fire", "flying"], abilities: [] },
  { name: "Scatterbug", slug: "scatterbug", dex: 664, types: ["bug"], abilities: [] },
  { name: "Spewpa", slug: "spewpa", dex: 665, types: ["bug"], abilities: [] },
  { name: "Vivillon", slug: "vivillon", dex: 666, types: ["bug", "flying"], abilities: [] },
  { name: "Litleo", slug: "litleo", dex: 667, types: ["fire", "normal"], abilities: [] },
  { name: "Pyroar", slug: "pyroar", dex: 668, types: ["fire", "normal"], abilities: [] },
  { name: "Flabébé", slug: "flabebe", dex: 669, types: ["fairy"], abilities: [] },
  { name: "Floette", slug: "floette", dex: 670, types: ["fairy"], abilities: [] },
  { name: "Florges", slug: "florges", dex: 671, types: ["fairy"], abilities: [] },
  { name: "Skiddo", slug: "skiddo", dex: 672, types: ["grass"], abilities: [] },
  { name: "Gogoat", slug: "gogoat", dex: 673, types: ["grass"], abilities: [] },
  { name: "Pancham", slug: "pancham", dex: 674, types: ["fighting"], abilities: [] },
  { name: "Pangoro", slug: "pangoro", dex: 675, types: ["fighting", "dark"], abilities: [] },
  { name: "Furfrou", slug: "furfrou", dex: 676, types: ["normal"], abilities: [] },
  { name: "Espurr", slug: "espurr", dex: 677, types: ["psychic"], abilities: [] },
  { name: "Meowstic", slug: "meowstic", dex: 678, types: ["psychic"], abilities: [] },
  { name: "Honedge", slug: "honedge", dex: 679, types: ["steel", "ghost"], abilities: [] },
  { name: "Doublade", slug: "doublade", dex: 680, types: ["steel", "ghost"], abilities: [] },
  { name: "Aegislash", slug: "aegislash", dex: 681, types: ["steel", "ghost"], abilities: ["Stance Change"] },
  { name: "Spritzee", slug: "spritzee", dex: 682, types: ["fairy"], abilities: [] },
  { name: "Aromatisse", slug: "aromatisse", dex: 683, types: ["fairy"], abilities: [] },
  { name: "Swirlix", slug: "swirlix", dex: 684, types: ["fairy"], abilities: [] },
  { name: "Slurpuff", slug: "slurpuff", dex: 685, types: ["fairy"], abilities: [] },
  { name: "Inkay", slug: "inkay", dex: 686, types: ["dark", "psychic"], abilities: [] },
  { name: "Malamar", slug: "malamar", dex: 687, types: ["dark", "psychic"], abilities: [] },
  { name: "Binacle", slug: "binacle", dex: 688, types: ["rock", "water"], abilities: [] },
  { name: "Barbaracle", slug: "barbaracle", dex: 689, types: ["rock", "water"], abilities: [] },
  { name: "Skrelp", slug: "skrelp", dex: 690, types: ["poison", "water"], abilities: [] },
  { name: "Dragalge", slug: "dragalge", dex: 691, types: ["poison", "dragon"], abilities: ["Poison Point", "Poison Touch", "Adaptability"] },
  { name: "Clauncher", slug: "clauncher", dex: 692, types: ["water"], abilities: [] },
  { name: "Clawitzer", slug: "clawitzer", dex: 693, types: ["water"], abilities: [] },
  { name: "Helioptile", slug: "helioptile", dex: 694, types: ["electric", "normal"], abilities: [] },
  { name: "Heliolisk", slug: "heliolisk", dex: 695, types: ["electric", "normal"], abilities: [] },
  { name: "Tyrunt", slug: "tyrunt", dex: 696, types: ["rock", "dragon"], abilities: [] },
  { name: "Tyrantrum", slug: "tyrantrum", dex: 697, types: ["rock", "dragon"], abilities: [] },
  { name: "Amaura", slug: "amaura", dex: 698, types: ["rock", "ice"], abilities: [] },
  { name: "Aurorus", slug: "aurorus", dex: 699, types: ["rock", "ice"], abilities: [] },
  { name: "Sylveon", slug: "sylveon", dex: 700, types: ["fairy"], abilities: ["Cute Charm", "Pixilate"] },
  { name: "Hawlucha", slug: "hawlucha", dex: 701, types: ["fighting", "flying"], abilities: [] },
  { name: "Dedenne", slug: "dedenne", dex: 702, types: ["electric", "fairy"], abilities: [] },
  { name: "Carbink", slug: "carbink", dex: 703, types: ["rock", "fairy"], abilities: [] },
  { name: "Goomy", slug: "goomy", dex: 704, types: ["dragon"], abilities: [] },
  { name: "Sliggoo", slug: "sliggoo", dex: 705, types: ["dragon"], abilities: [] },
  { name: "Goodra", slug: "goodra", dex: 706, types: ["dragon"], abilities: [] },
  { name: "Klefki", slug: "klefki", dex: 707, types: ["steel", "fairy"], abilities: [] },
  { name: "Phantump", slug: "phantump", dex: 708, types: ["ghost", "grass"], abilities: [] },
  { name: "Trevenant", slug: "trevenant", dex: 709, types: ["ghost", "grass"], abilities: [] },
  { name: "Pumpkaboo", slug: "pumpkaboo", dex: 710, types: ["ghost", "grass"], abilities: [] },
  { name: "Gourgeist", slug: "gourgeist", dex: 711, types: ["ghost", "grass"], abilities: [] },
  { name: "Bergmite", slug: "bergmite", dex: 712, types: ["ice"], abilities: [] },
  { name: "Avalugg", slug: "avalugg", dex: 713, types: ["ice"], abilities: [] },
  { name: "Noibat", slug: "noibat", dex: 714, types: ["flying", "dragon"], abilities: [] },
  { name: "Noivern", slug: "noivern", dex: 715, types: ["flying", "dragon"], abilities: [] },
  { name: "Xerneas", slug: "xerneas", dex: 716, types: ["fairy"], abilities: [] },
  { name: "Yveltal", slug: "yveltal", dex: 717, types: ["dark", "flying"], abilities: [] },
  { name: "Zygarde", slug: "zygarde", dex: 718, types: ["dragon", "ground"], abilities: [] },
  { name: "Diancie", slug: "diancie", dex: 719, types: ["rock", "fairy"], abilities: [] },
  { name: "Hoopa", slug: "hoopa", dex: 720, types: ["psychic", "ghost"], abilities: [] },
  { name: "Volcanion", slug: "volcanion", dex: 721, types: ["fire", "water"], abilities: [] },
  { name: "Rowlet", slug: "rowlet", dex: 722, types: ["grass", "flying"], abilities: [] },
  { name: "Dartrix", slug: "dartrix", dex: 723, types: ["grass", "flying"], abilities: [] },
  { name: "Decidueye", slug: "decidueye", dex: 724, types: ["grass", "ghost"], abilities: [] },
  { name: "Litten", slug: "litten", dex: 725, types: ["fire"], abilities: [] },
  { name: "Torracat", slug: "torracat", dex: 726, types: ["fire"], abilities: [] },
  { name: "Incineroar", slug: "incineroar", dex: 727, types: ["fire", "dark"], abilities: ["Blaze", "Intimidate"] },
  { name: "Popplio", slug: "popplio", dex: 728, types: ["water"], abilities: [] },
  { name: "Brionne", slug: "brionne", dex: 729, types: ["water"], abilities: [] },
  { name: "Primarina", slug: "primarina", dex: 730, types: ["water", "fairy"], abilities: ["Torrent", "Liquid Voice"] },
  { name: "Pikipek", slug: "pikipek", dex: 731, types: ["normal", "flying"], abilities: [] },
  { name: "Trumbeak", slug: "trumbeak", dex: 732, types: ["normal", "flying"], abilities: [] },
  { name: "Toucannon", slug: "toucannon", dex: 733, types: ["normal", "flying"], abilities: [] },
  { name: "Yungoos", slug: "yungoos", dex: 734, types: ["normal"], abilities: [] },
  { name: "Gumshoos", slug: "gumshoos", dex: 735, types: ["normal"], abilities: [] },
  { name: "Grubbin", slug: "grubbin", dex: 736, types: ["bug"], abilities: [] },
  { name: "Charjabug", slug: "charjabug", dex: 737, types: ["bug", "electric"], abilities: [] },
  { name: "Vikavolt", slug: "vikavolt", dex: 738, types: ["bug", "electric"], abilities: [] },
  { name: "Crabrawler", slug: "crabrawler", dex: 739, types: ["fighting"], abilities: [] },
  { name: "Crabominable", slug: "crabominable", dex: 740, types: ["fighting", "ice"], abilities: [] },
  { name: "Oricorio", slug: "oricorio", dex: 741, types: ["fire", "flying"], abilities: [] },
  { name: "Cutiefly", slug: "cutiefly", dex: 742, types: ["bug", "fairy"], abilities: [] },
  { name: "Ribombee", slug: "ribombee", dex: 743, types: ["bug", "fairy"], abilities: [] },
  { name: "Rockruff", slug: "rockruff", dex: 744, types: ["rock"], abilities: [] },
  { name: "Lycanroc", slug: "lycanroc", dex: 745, types: ["rock"], abilities: [] },
  { name: "Wishiwashi", slug: "wishiwashi", dex: 746, types: ["water"], abilities: [] },
  { name: "Mareanie", slug: "mareanie", dex: 747, types: ["poison", "water"], abilities: [] },
  { name: "Toxapex", slug: "toxapex", dex: 748, types: ["poison", "water"], abilities: [] },
  { name: "Mudbray", slug: "mudbray", dex: 749, types: ["ground"], abilities: [] },
  { name: "Mudsdale", slug: "mudsdale", dex: 750, types: ["ground"], abilities: [] },
  { name: "Dewpider", slug: "dewpider", dex: 751, types: ["water", "bug"], abilities: [] },
  { name: "Araquanid", slug: "araquanid", dex: 752, types: ["water", "bug"], abilities: [] },
  { name: "Fomantis", slug: "fomantis", dex: 753, types: ["grass"], abilities: [] },
  { name: "Lurantis", slug: "lurantis", dex: 754, types: ["grass"], abilities: [] },
  { name: "Morelull", slug: "morelull", dex: 755, types: ["grass", "fairy"], abilities: [] },
  { name: "Shiinotic", slug: "shiinotic", dex: 756, types: ["grass", "fairy"], abilities: [] },
  { name: "Salandit", slug: "salandit", dex: 757, types: ["poison", "fire"], abilities: [] },
  { name: "Salazzle", slug: "salazzle", dex: 758, types: ["poison", "fire"], abilities: [] },
  { name: "Stufful", slug: "stufful", dex: 759, types: ["normal", "fighting"], abilities: [] },
  { name: "Bewear", slug: "bewear", dex: 760, types: ["normal", "fighting"], abilities: [] },
  { name: "Bounsweet", slug: "bounsweet", dex: 761, types: ["grass"], abilities: [] },
  { name: "Steenee", slug: "steenee", dex: 762, types: ["grass"], abilities: [] },
  { name: "Tsareena", slug: "tsareena", dex: 763, types: ["grass"], abilities: [] },
  { name: "Comfey", slug: "comfey", dex: 764, types: ["fairy"], abilities: [] },
  { name: "Oranguru", slug: "oranguru", dex: 765, types: ["normal", "psychic"], abilities: [] },
  { name: "Passimian", slug: "passimian", dex: 766, types: ["fighting"], abilities: [] },
  { name: "Wimpod", slug: "wimpod", dex: 767, types: ["bug", "water"], abilities: [] },
  { name: "Golisopod", slug: "golisopod", dex: 768, types: ["bug", "water"], abilities: [] },
  { name: "Sandygast", slug: "sandygast", dex: 769, types: ["ghost", "ground"], abilities: [] },
  { name: "Palossand", slug: "palossand", dex: 770, types: ["ghost", "ground"], abilities: [] },
  { name: "Pyukumuku", slug: "pyukumuku", dex: 771, types: ["water"], abilities: [] },
  { name: "Type: Null", slug: "type-null", dex: 772, types: ["normal"], abilities: [] },
  { name: "Silvally", slug: "silvally", dex: 773, types: ["normal"], abilities: [] },
  { name: "Minior", slug: "minior", dex: 774, types: ["rock", "flying"], abilities: [] },
  { name: "Komala", slug: "komala", dex: 775, types: ["normal"], abilities: [] },
  { name: "Turtonator", slug: "turtonator", dex: 776, types: ["fire", "dragon"], abilities: [] },
  { name: "Togedemaru", slug: "togedemaru", dex: 777, types: ["electric", "steel"], abilities: [] },
  { name: "Mimikyu", slug: "mimikyu", dex: 778, types: ["ghost", "fairy"], abilities: [] },
  { name: "Bruxish", slug: "bruxish", dex: 779, types: ["water", "psychic"], abilities: [] },
  { name: "Drampa", slug: "drampa", dex: 780, types: ["normal", "dragon"], abilities: [] },
  { name: "Dhelmise", slug: "dhelmise", dex: 781, types: ["ghost", "grass"], abilities: [] },
  { name: "Jangmo-o", slug: "jangmo-o", dex: 782, types: ["dragon"], abilities: [] },
  { name: "Hakamo-o", slug: "hakamo-o", dex: 783, types: ["dragon", "fighting"], abilities: [] },
  { name: "Kommo-o", slug: "kommo-o", dex: 784, types: ["dragon", "fighting"], abilities: ["Bulletproof", "Soundproof", "Overcoat"] },
  { name: "Tapu Koko", slug: "tapu-koko", dex: 785, types: ["electric", "fairy"], abilities: [] },
  { name: "Tapu Lele", slug: "tapu-lele", dex: 786, types: ["psychic", "fairy"], abilities: [] },
  { name: "Tapu Bulu", slug: "tapu-bulu", dex: 787, types: ["grass", "fairy"], abilities: [] },
  { name: "Tapu Fini", slug: "tapu-fini", dex: 788, types: ["water", "fairy"], abilities: [] },
  { name: "Cosmog", slug: "cosmog", dex: 789, types: ["psychic"], abilities: [] },
  { name: "Cosmoem", slug: "cosmoem", dex: 790, types: ["psychic"], abilities: [] },
  { name: "Solgaleo", slug: "solgaleo", dex: 791, types: ["psychic", "steel"], abilities: ["Full Metal Body"] },
  { name: "Lunala", slug: "lunala", dex: 792, types: ["psychic", "ghost"], abilities: ["Shadow Shield"] },
  { name: "Nihilego", slug: "nihilego", dex: 793, types: ["rock", "poison"], abilities: [] },
  { name: "Buzzwole", slug: "buzzwole", dex: 794, types: ["bug", "fighting"], abilities: [] },
  { name: "Pheromosa", slug: "pheromosa", dex: 795, types: ["bug", "fighting"], abilities: [] },
  { name: "Xurkitree", slug: "xurkitree", dex: 796, types: ["electric"], abilities: [] },
  { name: "Celesteela", slug: "celesteela", dex: 797, types: ["steel", "flying"], abilities: [] },
  { name: "Kartana", slug: "kartana", dex: 798, types: ["grass", "steel"], abilities: [] },
  { name: "Guzzlord", slug: "guzzlord", dex: 799, types: ["dark", "dragon"], abilities: [] },
  { name: "Necrozma", slug: "necrozma", dex: 800, types: ["psychic"], abilities: [] },
  { name: "Magearna", slug: "magearna", dex: 801, types: ["steel", "fairy"], abilities: [] },
  { name: "Marshadow", slug: "marshadow", dex: 802, types: ["fighting", "ghost"], abilities: [] },
  { name: "Poipole", slug: "poipole", dex: 803, types: ["poison"], abilities: [] },
  { name: "Naganadel", slug: "naganadel", dex: 804, types: ["poison", "dragon"], abilities: [] },
  { name: "Stakataka", slug: "stakataka", dex: 805, types: ["rock", "steel"], abilities: [] },
  { name: "Blacephalon", slug: "blacephalon", dex: 806, types: ["fire", "ghost"], abilities: [] },
  { name: "Zeraora", slug: "zeraora", dex: 807, types: ["electric"], abilities: [] },
  { name: "Meltan", slug: "meltan", dex: 808, types: ["steel"], abilities: [] },
  { name: "Melmetal", slug: "melmetal", dex: 809, types: ["steel"], abilities: [] },
  { name: "Grookey", slug: "grookey", dex: 810, types: ["grass"], abilities: [] },
  { name: "Thwackey", slug: "thwackey", dex: 811, types: ["grass"], abilities: [] },
  { name: "Rillaboom", slug: "rillaboom", dex: 812, types: ["grass"], abilities: ["Overgrow", "Grassy Surge"] },
  { name: "Scorbunny", slug: "scorbunny", dex: 813, types: ["fire"], abilities: [] },
  { name: "Raboot", slug: "raboot", dex: 814, types: ["fire"], abilities: [] },
  { name: "Cinderace", slug: "cinderace", dex: 815, types: ["fire"], abilities: [] },
  { name: "Sobble", slug: "sobble", dex: 816, types: ["water"], abilities: [] },
  { name: "Drizzile", slug: "drizzile", dex: 817, types: ["water"], abilities: [] },
  { name: "Inteleon", slug: "inteleon", dex: 818, types: ["water"], abilities: [] },
  { name: "Skwovet", slug: "skwovet", dex: 819, types: ["normal"], abilities: [] },
  { name: "Greedent", slug: "greedent", dex: 820, types: ["normal"], abilities: [] },
  { name: "Rookidee", slug: "rookidee", dex: 821, types: ["flying"], abilities: [] },
  { name: "Corvisquire", slug: "corvisquire", dex: 822, types: ["flying"], abilities: [] },
  { name: "Corviknight", slug: "corviknight", dex: 823, types: ["flying", "steel"], abilities: ["Pressure", "Unnerve", "Mirror Armor"] },
  { name: "Blipbug", slug: "blipbug", dex: 824, types: ["bug"], abilities: [] },
  { name: "Dottler", slug: "dottler", dex: 825, types: ["bug", "psychic"], abilities: [] },
  { name: "Orbeetle", slug: "orbeetle", dex: 826, types: ["bug", "psychic"], abilities: [] },
  { name: "Nickit", slug: "nickit", dex: 827, types: ["dark"], abilities: [] },
  { name: "Thievul", slug: "thievul", dex: 828, types: ["dark"], abilities: [] },
  { name: "Gossifleur", slug: "gossifleur", dex: 829, types: ["grass"], abilities: [] },
  { name: "Eldegoss", slug: "eldegoss", dex: 830, types: ["grass"], abilities: [] },
  { name: "Wooloo", slug: "wooloo", dex: 831, types: ["normal"], abilities: [] },
  { name: "Dubwool", slug: "dubwool", dex: 832, types: ["normal"], abilities: [] },
  { name: "Chewtle", slug: "chewtle", dex: 833, types: ["water"], abilities: [] },
  { name: "Drednaw", slug: "drednaw", dex: 834, types: ["water", "rock"], abilities: [] },
  { name: "Yamper", slug: "yamper", dex: 835, types: ["electric"], abilities: [] },
  { name: "Boltund", slug: "boltund", dex: 836, types: ["electric"], abilities: [] },
  { name: "Rolycoly", slug: "rolycoly", dex: 837, types: ["rock"], abilities: [] },
  { name: "Carkol", slug: "carkol", dex: 838, types: ["rock", "fire"], abilities: [] },
  { name: "Coalossal", slug: "coalossal", dex: 839, types: ["rock", "fire"], abilities: [] },
  { name: "Applin", slug: "applin", dex: 840, types: ["grass", "dragon"], abilities: [] },
  { name: "Flapple", slug: "flapple", dex: 841, types: ["grass", "dragon"], abilities: [] },
  { name: "Appletun", slug: "appletun", dex: 842, types: ["grass", "dragon"], abilities: [] },
  { name: "Silicobra", slug: "silicobra", dex: 843, types: ["ground"], abilities: [] },
  { name: "Sandaconda", slug: "sandaconda", dex: 844, types: ["ground"], abilities: [] },
  { name: "Cramorant", slug: "cramorant", dex: 845, types: ["flying", "water"], abilities: [] },
  { name: "Arrokuda", slug: "arrokuda", dex: 846, types: ["water"], abilities: [] },
  { name: "Barraskewda", slug: "barraskewda", dex: 847, types: ["water"], abilities: [] },
  { name: "Toxel", slug: "toxel", dex: 848, types: ["electric", "poison"], abilities: [] },
  { name: "Toxtricity", slug: "toxtricity", dex: 849, types: ["electric", "poison"], abilities: ["Punk Rock", "Plus", "Technician"] },
  { name: "Sizzlipede", slug: "sizzlipede", dex: 850, types: ["fire", "bug"], abilities: [] },
  { name: "Centiskorch", slug: "centiskorch", dex: 851, types: ["fire", "bug"], abilities: [] },
  { name: "Clobbopus", slug: "clobbopus", dex: 852, types: ["fighting"], abilities: [] },
  { name: "Grapploct", slug: "grapploct", dex: 853, types: ["fighting"], abilities: [] },
  { name: "Sinistea", slug: "sinistea", dex: 854, types: ["ghost"], abilities: [] },
  { name: "Polteageist", slug: "polteageist", dex: 855, types: ["ghost"], abilities: [] },
  { name: "Hatenna", slug: "hatenna", dex: 856, types: ["psychic"], abilities: [] },
  { name: "Hattrem", slug: "hattrem", dex: 857, types: ["psychic"], abilities: [] },
  { name: "Hatterene", slug: "hatterene", dex: 858, types: ["psychic", "fairy"], abilities: ["Healer", "Anticipation", "Magic Bounce"] },
  { name: "Impidimp", slug: "impidimp", dex: 859, types: ["dark", "fairy"], abilities: [] },
  { name: "Morgrem", slug: "morgrem", dex: 860, types: ["dark", "fairy"], abilities: [] },
  { name: "Grimmsnarl", slug: "grimmsnarl", dex: 861, types: ["dark", "fairy"], abilities: ["Prankster", "Frisk", "Pickpocket"] },
  { name: "Obstagoon", slug: "obstagoon", dex: 862, types: ["dark", "normal"], abilities: [] },
  { name: "Perrserker", slug: "perrserker", dex: 863, types: ["steel"], abilities: [] },
  { name: "Cursola", slug: "cursola", dex: 864, types: ["ghost"], abilities: [] },
  { name: "Sirfetch'd", slug: "sirfetchd", dex: 39, types: ["fighting"], abilities: [] },
  { name: "Mr. Rime", slug: "mr-rime", dex: 866, types: ["ice", "psychic"], abilities: [] },
  { name: "Runerigus", slug: "runerigus", dex: 867, types: ["ground", "ghost"], abilities: [] },
  { name: "Milcery", slug: "milcery", dex: 868, types: ["fairy"], abilities: [] },
  { name: "Alcremie", slug: "alcremie", dex: 869, types: ["fairy"], abilities: [] },
  { name: "Falinks", slug: "falinks", dex: 870, types: ["fighting"], abilities: [] },
  { name: "Pincurchin", slug: "pincurchin", dex: 871, types: ["electric"], abilities: [] },
  { name: "Snom", slug: "snom", dex: 872, types: ["ice", "bug"], abilities: [] },
  { name: "Frosmoth", slug: "frosmoth", dex: 873, types: ["ice", "bug"], abilities: [] },
  { name: "Stonjourner", slug: "stonjourner", dex: 874, types: ["rock"], abilities: [] },
  { name: "Eiscue", slug: "eiscue", dex: 875, types: ["ice"], abilities: [] },
  { name: "Indeedee", slug: "indeedee", dex: 876, types: ["psychic", "normal"], abilities: [] },
  { name: "Morpeko", slug: "morpeko", dex: 877, types: ["electric", "dark"], abilities: [] },
  { name: "Cufant", slug: "cufant", dex: 878, types: ["steel"], abilities: [] },
  { name: "Copperajah", slug: "copperajah", dex: 879, types: ["steel"], abilities: [] },
  { name: "Dracozolt", slug: "dracozolt", dex: 880, types: ["electric", "dragon"], abilities: [] },
  { name: "Arctozolt", slug: "arctozolt", dex: 881, types: ["electric", "ice"], abilities: [] },
  { name: "Dracovish", slug: "dracovish", dex: 882, types: ["water", "dragon"], abilities: [] },
  { name: "Arctovish", slug: "arctovish", dex: 883, types: ["water", "ice"], abilities: [] },
  { name: "Duraludon", slug: "duraludon", dex: 884, types: ["steel", "dragon"], abilities: [] },
  { name: "Dreepy", slug: "dreepy", dex: 885, types: ["dragon", "ghost"], abilities: [] },
  { name: "Drakloak", slug: "drakloak", dex: 886, types: ["dragon", "ghost"], abilities: [] },
  { name: "Dragapult", slug: "dragapult", dex: 887, types: ["dragon", "ghost"], abilities: ["Clear Body", "Infiltrator", "Cursed Body"] },
  { name: "Zacian", slug: "zacian", dex: 888, types: ["fairy"], abilities: ["Intrepid Sword"] },
  { name: "Zamazenta", slug: "zamazenta", dex: 889, types: ["fighting"], abilities: ["Dauntless Shield"] },
  { name: "Eternatus", slug: "eternatus", dex: 890, types: ["poison", "dragon"], abilities: ["Pressure"] },
  { name: "Kubfu", slug: "kubfu", dex: 891, types: ["fighting"], abilities: [] },
  { name: "Urshifu", slug: "urshifu-single-strike", dex: 892, types: ["fighting", "dark"], abilities: ["Unseen Fist"] },
  { name: "Zarude", slug: "zarude", dex: 893, types: ["dark", "grass"], abilities: [] },
  { name: "Regieleki", slug: "regieleki", dex: 894, types: ["electric"], abilities: ["Transistor"] },
  { name: "Regidrago", slug: "regidrago", dex: 895, types: ["dragon"], abilities: ["Dragon's Maw"] },
  { name: "Glastrier", slug: "glastrier", dex: 896, types: ["ice"], abilities: ["Chilling Neigh"] },
  { name: "Spectrier", slug: "spectrier", dex: 897, types: ["ghost"], abilities: ["Grim Neigh"] },
  { name: "Calyrex", slug: "calyrex", dex: 898, types: ["psychic", "grass"], abilities: [] },
  { name: "Wyrdeer", slug: "wyrdeer", dex: 899, types: ["normal", "psychic"], abilities: [] },
  { name: "Kleavor", slug: "kleavor", dex: 900, types: ["bug", "rock"], abilities: [] },
  { name: "Ursaluna", slug: "ursaluna", dex: 901, types: ["ground", "normal"], abilities: ["Guts", "Bulletproof", "Unnerve"] },
  { name: "Basculegion", slug: "basculegion", dex: 902, types: ["water", "ghost"], abilities: ["Swift Swim", "Adaptability", "Mold Breaker"] },
  { name: "Sneasler", slug: "sneasler", dex: 903, types: ["fighting", "poison"], abilities: ["Pressure", "Unburden", "Poison Touch"] },
  { name: "Overqwil", slug: "overqwil", dex: 904, types: ["dark", "poison"], abilities: ["Poison Point", "Swift Swim", "Intimidate"] },
  { name: "Enamorus", slug: "enamorus", dex: 905, types: ["fairy", "flying"], abilities: ["Cute Charm", "Contrary"] },
  { name: "Sprigatito", slug: "sprigatito", dex: 906, types: ["grass"], abilities: [] },
  { name: "Floragato", slug: "floragato", dex: 907, types: ["grass"], abilities: [] },
  { name: "Meowscarada", slug: "meowscarada", dex: 908, types: ["grass", "dark"], abilities: [] },
  { name: "Fuecoco", slug: "fuecoco", dex: 909, types: ["fire"], abilities: [] },
  { name: "Crocalor", slug: "crocalor", dex: 910, types: ["fire"], abilities: [] },
  { name: "Skeledirge", slug: "skeledirge", dex: 911, types: ["fire", "ghost"], abilities: [] },
  { name: "Quaxly", slug: "quaxly", dex: 912, types: ["water"], abilities: [] },
  { name: "Quaxwell", slug: "quaxwell", dex: 913, types: ["water"], abilities: [] },
  { name: "Quaquaval", slug: "quaquaval", dex: 914, types: ["water", "fighting"], abilities: [] },
  { name: "Lechonk", slug: "lechonk", dex: 915, types: ["normal"], abilities: [] },
  { name: "Oinkologne", slug: "oinkologne", dex: 916, types: ["normal"], abilities: [] },
  { name: "Tarountula", slug: "tarountula", dex: 917, types: ["bug"], abilities: [] },
  { name: "Spidops", slug: "spidops", dex: 918, types: ["bug"], abilities: [] },
  { name: "Nymble", slug: "nymble", dex: 919, types: ["bug"], abilities: [] },
  { name: "Lokix", slug: "lokix", dex: 920, types: ["bug", "dark"], abilities: [] },
  { name: "Pawmi", slug: "pawmi", dex: 921, types: ["electric"], abilities: [] },
  { name: "Pawmo", slug: "pawmo", dex: 922, types: ["electric", "fighting"], abilities: [] },
  { name: "Pawmot", slug: "pawmot", dex: 923, types: ["electric", "fighting"], abilities: [] },
  { name: "Tandemaus", slug: "tandemaus", dex: 924, types: ["normal"], abilities: [] },
  { name: "Maushold", slug: "maushold", dex: 925, types: ["normal"], abilities: ["Friend Guard", "Cheek Pouch", "Technician"] },
  { name: "Fidough", slug: "fidough", dex: 926, types: ["fairy"], abilities: [] },
  { name: "Dachsbun", slug: "dachsbun", dex: 927, types: ["fairy"], abilities: [] },
  { name: "Smoliv", slug: "smoliv", dex: 928, types: ["grass", "normal"], abilities: [] },
  { name: "Dolliv", slug: "dolliv", dex: 929, types: ["grass", "normal"], abilities: [] },
  { name: "Arboliva", slug: "arboliva", dex: 930, types: ["grass", "normal"], abilities: [] },
  { name: "Squawkabilly", slug: "squawkabilly", dex: 931, types: ["normal", "flying"], abilities: [] },
  { name: "Nacli", slug: "nacli", dex: 932, types: ["rock"], abilities: [] },
  { name: "Naclstack", slug: "naclstack", dex: 933, types: ["rock"], abilities: [] },
  { name: "Garganacl", slug: "garganacl", dex: 934, types: ["rock"], abilities: ["Purifying Salt", "Sturdy", "Clear Body"] },
  { name: "Charcadet", slug: "charcadet", dex: 935, types: ["fire"], abilities: [] },
  { name: "Armarouge", slug: "armarouge", dex: 936, types: ["fire", "psychic"], abilities: ["Flash Fire", "Weak Armor"] },
  { name: "Ceruledge", slug: "ceruledge", dex: 937, types: ["fire", "ghost"], abilities: ["Flash Fire", "Weak Armor"] },
  { name: "Tadbulb", slug: "tadbulb", dex: 938, types: ["electric"], abilities: [] },
  { name: "Bellibolt", slug: "bellibolt", dex: 939, types: ["electric"], abilities: [] },
  { name: "Wattrel", slug: "wattrel", dex: 940, types: ["electric", "flying"], abilities: [] },
  { name: "Kilowattrel", slug: "kilowattrel", dex: 941, types: ["electric", "flying"], abilities: ["Wind Power", "Volt Absorb", "Competitive"] },
  { name: "Maschiff", slug: "maschiff", dex: 942, types: ["dark"], abilities: [] },
  { name: "Mabosstiff", slug: "mabosstiff", dex: 943, types: ["dark"], abilities: [] },
  { name: "Shroodle", slug: "shroodle", dex: 944, types: ["poison", "normal"], abilities: [] },
  { name: "Grafaiai", slug: "grafaiai", dex: 945, types: ["poison", "normal"], abilities: [] },
  { name: "Bramblin", slug: "bramblin", dex: 946, types: ["grass", "ghost"], abilities: [] },
  { name: "Brambleghast", slug: "brambleghast", dex: 947, types: ["grass", "ghost"], abilities: [] },
  { name: "Toedscool", slug: "toedscool", dex: 948, types: ["ground", "grass"], abilities: [] },
  { name: "Toedscruel", slug: "toedscruel", dex: 949, types: ["ground", "grass"], abilities: [] },
  { name: "Klawf", slug: "klawf", dex: 950, types: ["rock"], abilities: [] },
  { name: "Capsakid", slug: "capsakid", dex: 951, types: ["grass"], abilities: [] },
  { name: "Scovillain", slug: "scovillain", dex: 952, types: ["grass", "fire"], abilities: ["Chlorophyll", "Insomnia", "Moody"] },
  { name: "Rellor", slug: "rellor", dex: 953, types: ["bug"], abilities: [] },
  { name: "Rabsca", slug: "rabsca", dex: 954, types: ["bug", "psychic"], abilities: [] },
  { name: "Flittle", slug: "flittle", dex: 955, types: ["psychic"], abilities: [] },
  { name: "Espathra", slug: "espathra", dex: 956, types: ["psychic"], abilities: ["Opportunist", "Frisk", "Speed Boost"] },
  { name: "Tinkatink", slug: "tinkatink", dex: 957, types: ["fairy", "steel"], abilities: [] },
  { name: "Tinkatuff", slug: "tinkatuff", dex: 958, types: ["fairy", "steel"], abilities: [] },
  { name: "Tinkaton", slug: "tinkaton", dex: 959, types: ["fairy", "steel"], abilities: ["Mold Breaker", "Own Tempo", "Pickpocket"] },
  { name: "Wiglett", slug: "wiglett", dex: 960, types: ["water"], abilities: [] },
  { name: "Wugtrio", slug: "wugtrio", dex: 961, types: ["water"], abilities: [] },
  { name: "Bombirdier", slug: "bombirdier", dex: 962, types: ["flying", "dark"], abilities: ["Big Pecks", "Keen Eye", "Rocky Payload"] },
  { name: "Finizen", slug: "finizen", dex: 963, types: ["water"], abilities: [] },
  { name: "Palafin", slug: "palafin", dex: 964, types: ["water"], abilities: ["Zero to Hero"] },
  { name: "Varoom", slug: "varoom", dex: 965, types: ["steel", "poison"], abilities: [] },
  { name: "Revavroom", slug: "revavroom", dex: 966, types: ["steel", "poison"], abilities: [] },
  { name: "Cyclizar", slug: "cyclizar", dex: 967, types: ["dragon", "normal"], abilities: [] },
  { name: "Orthworm", slug: "orthworm", dex: 968, types: ["steel"], abilities: ["Earth Eater", "Sand Veil"] },
  { name: "Glimmet", slug: "glimmet", dex: 969, types: ["rock", "poison"], abilities: [] },
  { name: "Glimmora", slug: "glimmora", dex: 970, types: ["rock", "poison"], abilities: ["Toxic Debris", "Corrosion"] },
  { name: "Greavard", slug: "greavard", dex: 971, types: ["ghost"], abilities: [] },
  { name: "Houndstone", slug: "houndstone", dex: 972, types: ["ghost"], abilities: [] },
  { name: "Flamigo", slug: "flamigo", dex: 973, types: ["flying", "fighting"], abilities: [] },
  { name: "Cetoddle", slug: "cetoddle", dex: 974, types: ["ice"], abilities: [] },
  { name: "Cetitan", slug: "cetitan", dex: 975, types: ["ice"], abilities: [] },
  { name: "Veluza", slug: "veluza", dex: 976, types: ["water", "psychic"], abilities: [] },
  { name: "Dondozo", slug: "dondozo", dex: 977, types: ["water"], abilities: ["Unaware", "Oblivious", "Water Veil"] },
  { name: "Tatsugiri", slug: "tatsugiri", dex: 978, types: ["dragon", "water"], abilities: ["Commander", "Storm Drain"] },
  { name: "Annihilape", slug: "annihilape", dex: 979, types: ["fighting", "ghost"], abilities: ["Vital Spirit", "Inner Focus", "Defiant"] },
  { name: "Clodsire", slug: "clodsire", dex: 980, types: ["poison", "ground"], abilities: [] },
  { name: "Farigiraf", slug: "farigiraf", dex: 981, types: ["normal", "psychic"], abilities: ["Cud Chew", "Armor Tail", "Sap Sipper"] },
  { name: "Dudunsparce", slug: "dudunsparce", dex: 982, types: ["normal"], abilities: [] },
  { name: "Kingambit", slug: "kingambit", dex: 983, types: ["dark", "steel"], abilities: ["Defiant", "Supreme Overlord", "Pressure"] },
  { name: "Great Tusk", slug: "great-tusk", dex: 984, types: ["ground", "fighting"], abilities: ["Protosynthesis"] },
  { name: "Scream Tail", slug: "scream-tail", dex: 985, types: ["fairy", "psychic"], abilities: ["Protosynthesis"] },
  { name: "Brute Bonnet", slug: "brute-bonnet", dex: 986, types: ["grass", "dark"], abilities: [] },
  { name: "Flutter Mane", slug: "flutter-mane", dex: 987, types: ["ghost", "fairy"], abilities: ["Protosynthesis"] },
  { name: "Slither Wing", slug: "slither-wing", dex: 988, types: ["bug", "fighting"], abilities: [] },
  { name: "Sandy Shocks", slug: "sandy-shocks", dex: 989, types: ["electric", "ground"], abilities: [] },
  { name: "Iron Treads", slug: "iron-treads", dex: 990, types: ["ground", "steel"], abilities: ["Quark Drive"] },
  { name: "Iron Bundle", slug: "iron-bundle", dex: 991, types: ["ice", "water"], abilities: ["Quark Drive"] },
  { name: "Iron Hands", slug: "iron-hands", dex: 992, types: ["fighting", "electric"], abilities: ["Quark Drive"] },
  { name: "Iron Jugulis", slug: "iron-jugulis", dex: 993, types: ["dark", "flying"], abilities: [] },
  { name: "Iron Moth", slug: "iron-moth", dex: 994, types: ["fire", "poison"], abilities: ["Quark Drive"] },
  { name: "Iron Thorns", slug: "iron-thorns", dex: 995, types: ["rock", "electric"], abilities: [] },
  { name: "Frigibax", slug: "frigibax", dex: 996, types: ["dragon", "ice"], abilities: [] },
  { name: "Arctibax", slug: "arctibax", dex: 997, types: ["dragon", "ice"], abilities: [] },
  { name: "Baxcalibur", slug: "baxcalibur", dex: 998, types: ["dragon", "ice"], abilities: ["Thermal Exchange", "Ice Body"] },
  { name: "Gimmighoul", slug: "gimmighoul", dex: 999, types: ["ghost"], abilities: [] },
  { name: "Gholdengo", slug: "gholdengo", dex: 1000, types: ["steel", "ghost"], abilities: ["Good as Gold"] },
  { name: "Wo-Chien", slug: "wo-chien", dex: 1001, types: ["dark", "grass"], abilities: ["Tablets of Ruin"] },
  { name: "Chien-Pao", slug: "chien-pao", dex: 1002, types: ["dark", "ice"], abilities: ["Sword of Ruin"] },
  { name: "Ting-Lu", slug: "ting-lu", dex: 1003, types: ["dark", "ground"], abilities: ["Vessel of Ruin"] },
  { name: "Chi-Yu", slug: "chi-yu", dex: 1004, types: ["dark", "fire"], abilities: ["Beads of Ruin"] },
  { name: "Roaring Moon", slug: "roaring-moon", dex: 1005, types: ["dragon", "dark"], abilities: ["Protosynthesis"] },
  { name: "Iron Valiant", slug: "iron-valiant", dex: 1006, types: ["fairy", "fighting"], abilities: ["Quark Drive"] },
  { name: "Koraidon", slug: "koraidon", dex: 1007, types: ["fighting", "dragon"], abilities: ["Orichalcum Pulse"] },
  { name: "Miraidon", slug: "miraidon", dex: 1008, types: ["electric", "dragon"], abilities: ["Hadron Engine"] },
  { name: "Walking Wake", slug: "walking-wake", dex: 1009, types: ["water", "dragon"], abilities: ["Protosynthesis"] },
  { name: "Iron Leaves", slug: "iron-leaves", dex: 1010, types: ["grass", "psychic"], abilities: [] },
  { name: "Dipplin", slug: "dipplin", dex: 1011, types: ["grass", "dragon"], abilities: [] },
  { name: "Poltchageist", slug: "poltchageist", dex: 1012, types: ["grass", "ghost"], abilities: [] },
  { name: "Sinistcha", slug: "sinistcha", dex: 1013, types: ["grass", "ghost"], abilities: ["Hospitality", "Heatproof"] },
  { name: "Okidogi", slug: "okidogi", dex: 1014, types: ["poison", "fighting"], abilities: ["Toxic Chain", "Guard Dog"] },
  { name: "Munkidori", slug: "munkidori", dex: 1015, types: ["poison", "psychic"], abilities: ["Toxic Chain", "Frisk"] },
  { name: "Fezandipiti", slug: "fezandipiti", dex: 1016, types: ["poison", "fairy"], abilities: ["Toxic Chain", "Technician"] },
  { name: "Ogerpon", slug: "ogerpon", dex: 1017, types: ["grass"], abilities: ["Defiant"] },
  { name: "Archaludon", slug: "archaludon", dex: 1018, types: ["steel", "dragon"], abilities: ["Stamina", "Sturdy", "Stalwart"] },
  { name: "Hydrapple", slug: "hydrapple", dex: 1019, types: ["grass", "dragon"], abilities: [] },
  { name: "Gouging Fire", slug: "gouging-fire", dex: 1020, types: ["fire", "dragon"], abilities: ["Protosynthesis"] },
  { name: "Raging Bolt", slug: "raging-bolt", dex: 1021, types: ["electric", "dragon"], abilities: ["Protosynthesis"] },
  { name: "Iron Boulder", slug: "iron-boulder", dex: 1022, types: ["rock", "psychic"], abilities: [] },
  { name: "Iron Crown", slug: "iron-crown", dex: 1023, types: ["steel", "psychic"], abilities: ["Quark Drive"] },
  { name: "Terapagos", slug: "terapagos", dex: 1024, types: ["normal"], abilities: ["Tera Shift"] },
  { name: "Pecharunt", slug: "pecharunt", dex: 1025, types: ["poison", "ghost"], abilities: ["Poison Puppeteer"] },
  { name: "Urshifu Rapid", slug: "urshifu-rapid-strike", dex: 892, spriteDex: 10191, types: ["fighting", "water"], abilities: ["Unseen Fist"] },
  { name: "Ogerpon Wellspring", slug: "ogerpon-wellspring", dex: 1017, spriteDex: 10273, types: ["grass", "water"], abilities: ["Water Absorb"] },
  { name: "Ogerpon Hearthflame", slug: "ogerpon-hearthflame", dex: 1017, spriteDex: 10274, types: ["grass", "fire"], abilities: ["Mold Breaker"] },
  { name: "Ogerpon Cornerstone", slug: "ogerpon-cornerstone", dex: 1017, spriteDex: 10275, types: ["grass", "rock"], abilities: ["Sturdy"] },
  { name: "Indeedee F", slug: "indeedee-female", dex: 876, spriteDex: 10186, types: ["psychic", "normal"], abilities: ["Own Tempo", "Synchronize", "Psychic Surge"] },
  { name: "Indeedee M", slug: "indeedee-male", dex: 876, types: ["psychic", "normal"], abilities: ["Inner Focus", "Synchronize", "Psychic Surge"] },
  { name: "Landorus Therian", slug: "landorus-therian", dex: 645, spriteDex: 10021, types: ["ground", "flying"], abilities: ["Intimidate"] },
  { name: "Tornadus Therian", slug: "tornadus-therian", dex: 641, types: ["flying"], abilities: ["Regenerator"] },
  { name: "Thundurus Therian", slug: "thundurus-therian", dex: 642, types: ["electric", "flying"], abilities: ["Volt Absorb"] },
  { name: "Calyrex Ice", slug: "calyrex-ice-rider", dex: 898, spriteDex: 10193, types: ["psychic", "ice"], abilities: ["As One"] },
  { name: "Calyrex Shadow", slug: "calyrex-shadow-rider", dex: 898, spriteDex: 10194, types: ["psychic", "ghost"], abilities: ["As One"] },
  { name: "Ursaluna Bloodmoon", slug: "ursaluna-bloodmoon", dex: 901, spriteDex: 10272, types: ["ground", "normal"], abilities: ["Mind's Eye"] },
  { name: "Ninetales-A", slug: "ninetales-alolan", dex: 38, spriteDex: 10104, types: ["ice", "fairy"], abilities: ["Snow Cloak", "Snow Warning"] },
  { name: "Arcanine-H", slug: "arcanine-hisuian", dex: 59, spriteDex: 10230, types: ["fire", "rock"], abilities: ["Intimidate", "Flash Fire", "Rock Head"] },
  { name: "Typhlosion-H", slug: "typhlosion-hisuian", dex: 157, spriteDex: 10233, types: ["fire", "ghost"], abilities: ["Blaze", "Frisk"] },
  { name: "Samurott-H", slug: "samurott-hisuian", dex: 503, spriteDex: 10236, types: ["water", "dark"], abilities: ["Torrent", "Sharpness"] },
  { name: "Decidueye-H", slug: "decidueye-hisuian", dex: 724, spriteDex: 10244, types: ["grass", "fighting"], abilities: ["Overgrow", "Scrappy"] },
  { name: "Lilligant-H", slug: "lilligant-hisuian", dex: 549, spriteDex: 10237, types: ["grass", "fighting"], abilities: ["Chlorophyll", "Hustle", "Leaf Guard"] },
  { name: "Electrode-H", slug: "electrode-hisuian", dex: 101, spriteDex: 10232, types: ["electric", "grass"], abilities: ["Soundproof", "Static", "Aftermath"] },
  { name: "Goodra-H", slug: "goodra-hisuian", dex: 706, spriteDex: 10242, types: ["steel", "dragon"], abilities: ["Sap Sipper", "Shell Armor", "Gooey"] },
];
