/* Generated from https://pokemondb.net/move/all — do not edit by hand. */

export const ALL_MOVES = [
  { name: "10,000,000 Volt Thunderbolt", type: "electric" },
  { name: "Absorb", type: "grass" },
  { name: "Accelerock", type: "rock" },
  { name: "Acid", type: "poison" },
  { name: "Acid Armor", type: "poison" },
  { name: "Acid Downpour", type: "poison" },
  { name: "Acid Spray", type: "poison" },
  { name: "Acrobatics", type: "flying" },
  { name: "Acupressure", type: "normal" },
  { name: "Aerial Ace", type: "flying" },
  { name: "Aeroblast", type: "flying" },
  { name: "After You", type: "normal" },
  { name: "Agility", type: "psychic" },
  { name: "Air Cutter", type: "flying" },
  { name: "Air Slash", type: "flying" },
  { name: "All-Out Pummeling", type: "fighting" },
  { name: "Alluring Voice", type: "fairy" },
  { name: "Ally Switch", type: "psychic" },
  { name: "Amnesia", type: "psychic" },
  { name: "Anchor Shot", type: "steel" },
  { name: "Ancient Power", type: "rock" },
  { name: "Apple Acid", type: "grass" },
  { name: "Aqua Cutter", type: "water" },
  { name: "Aqua Jet", type: "water" },
  { name: "Aqua Ring", type: "water" },
  { name: "Aqua Step", type: "water" },
  { name: "Aqua Tail", type: "water" },
  { name: "Arm Thrust", type: "fighting" },
  { name: "Armor Cannon", type: "fire" },
  { name: "Aromatherapy", type: "grass" },
  { name: "Aromatic Mist", type: "fairy" },
  { name: "Assist", type: "normal" },
  { name: "Assurance", type: "dark" },
  { name: "Astonish", type: "ghost" },
  { name: "Astral Barrage", type: "ghost" },
  { name: "Attack Order", type: "bug" },
  { name: "Attract", type: "normal" },
  { name: "Aura Sphere", type: "fighting" },
  { name: "Aura Wheel", type: "electric" },
  { name: "Aurora Beam", type: "ice" },
  { name: "Aurora Veil", type: "ice" },
  { name: "Autotomize", type: "steel" },
  { name: "Avalanche", type: "ice" },
  { name: "Axe Kick", type: "fighting" },
  { name: "Baby-Doll Eyes", type: "fairy" },
  { name: "Baddy Bad", type: "dark" },
  { name: "Baneful Bunker", type: "poison" },
  { name: "Barb Barrage", type: "poison" },
  { name: "Barrage", type: "normal" },
  { name: "Barrier", type: "psychic" },
  { name: "Baton Pass", type: "normal" },
  { name: "Beak Blast", type: "flying" },
  { name: "Beat Up", type: "dark" },
  { name: "Behemoth Bash", type: "steel" },
  { name: "Behemoth Blade", type: "steel" },
  { name: "Belch", type: "poison" },
  { name: "Belly Drum", type: "normal" },
  { name: "Bestow", type: "normal" },
  { name: "Bide", type: "normal" },
  { name: "Bind", type: "normal" },
  { name: "Bite", type: "dark" },
  { name: "Bitter Blade", type: "fire" },
  { name: "Bitter Malice", type: "ghost" },
  { name: "Black Hole Eclipse", type: "dark" },
  { name: "Blast Burn", type: "fire" },
  { name: "Blaze Kick", type: "fire" },
  { name: "Blazing Torque", type: "fire" },
  { name: "Bleakwind Storm", type: "flying" },
  { name: "Blizzard", type: "ice" },
  { name: "Block", type: "normal" },
  { name: "Blood Moon", type: "normal" },
  { name: "Bloom Doom", type: "grass" },
  { name: "Blue Flare", type: "fire" },
  { name: "Body Press", type: "fighting" },
  { name: "Body Slam", type: "normal" },
  { name: "Bolt Beak", type: "electric" },
  { name: "Bolt Strike", type: "electric" },
  { name: "Bone Club", type: "ground" },
  { name: "Bone Rush", type: "ground" },
  { name: "Bonemerang", type: "ground" },
  { name: "Boomburst", type: "normal" },
  { name: "Bounce", type: "flying" },
  { name: "Bouncy Bubble", type: "water" },
  { name: "Branch Poke", type: "grass" },
  { name: "Brave Bird", type: "flying" },
  { name: "Breaking Swipe", type: "dragon" },
  { name: "Breakneck Blitz", type: "normal" },
  { name: "Brick Break", type: "fighting" },
  { name: "Brine", type: "water" },
  { name: "Brutal Swing", type: "dark" },
  { name: "Bubble", type: "water" },
  { name: "Bubble Beam", type: "water" },
  { name: "Bug Bite", type: "bug" },
  { name: "Bug Buzz", type: "bug" },
  { name: "Bulk Up", type: "fighting" },
  { name: "Bulldoze", type: "ground" },
  { name: "Bullet Punch", type: "steel" },
  { name: "Bullet Seed", type: "grass" },
  { name: "Burn Up", type: "fire" },
  { name: "Burning Bulwark", type: "fire" },
  { name: "Burning Jealousy", type: "fire" },
  { name: "Buzzy Buzz", type: "electric" },
  { name: "Calm Mind", type: "psychic" },
  { name: "Camouflage", type: "normal" },
  { name: "Captivate", type: "normal" },
  { name: "Catastropika", type: "electric" },
  { name: "Ceaseless Edge", type: "dark" },
  { name: "Celebrate", type: "normal" },
  { name: "Charge", type: "electric" },
  { name: "Charge Beam", type: "electric" },
  { name: "Charm", type: "fairy" },
  { name: "Chatter", type: "flying" },
  { name: "Chilling Water", type: "water" },
  { name: "Chilly Reception", type: "ice" },
  { name: "Chip Away", type: "normal" },
  { name: "Chloroblast", type: "grass" },
  { name: "Circle Throw", type: "fighting" },
  { name: "Clamp", type: "water" },
  { name: "Clanging Scales", type: "dragon" },
  { name: "Clangorous Soul", type: "dragon" },
  { name: "Clangorous Soulblaze", type: "dragon" },
  { name: "Clear Smog", type: "poison" },
  { name: "Close Combat", type: "fighting" },
  { name: "Coaching", type: "fighting" },
  { name: "Coil", type: "poison" },
  { name: "Collision Course", type: "fighting" },
  { name: "Combat Torque", type: "fighting" },
  { name: "Comet Punch", type: "normal" },
  { name: "Comeuppance", type: "dark" },
  { name: "Confide", type: "normal" },
  { name: "Confuse Ray", type: "ghost" },
  { name: "Confusion", type: "psychic" },
  { name: "Constrict", type: "normal" },
  { name: "Continental Crush", type: "rock" },
  { name: "Conversion", type: "normal" },
  { name: "Conversion 2", type: "normal" },
  { name: "Copycat", type: "normal" },
  { name: "Core Enforcer", type: "dragon" },
  { name: "Corkscrew Crash", type: "steel" },
  { name: "Corrosive Gas", type: "poison" },
  { name: "Cosmic Power", type: "psychic" },
  { name: "Cotton Guard", type: "grass" },
  { name: "Cotton Spore", type: "grass" },
  { name: "Counter", type: "fighting" },
  { name: "Court Change", type: "normal" },
  { name: "Covet", type: "normal" },
  { name: "Crabhammer", type: "water" },
  { name: "Crafty Shield", type: "fairy" },
  { name: "Cross Chop", type: "fighting" },
  { name: "Cross Poison", type: "poison" },
  { name: "Crunch", type: "dark" },
  { name: "Crush Claw", type: "normal" },
  { name: "Crush Grip", type: "normal" },
  { name: "Curse", type: "ghost" },
  { name: "Cut", type: "normal" },
  { name: "Dark Pulse", type: "dark" },
  { name: "Dark Void", type: "dark" },
  { name: "Darkest Lariat", type: "dark" },
  { name: "Dazzling Gleam", type: "fairy" },
  { name: "Decorate", type: "fairy" },
  { name: "Defend Order", type: "bug" },
  { name: "Defense Curl", type: "normal" },
  { name: "Defog", type: "flying" },
  { name: "Destiny Bond", type: "ghost" },
  { name: "Detect", type: "fighting" },
  { name: "Devastating Drake", type: "dragon" },
  { name: "Diamond Storm", type: "rock" },
  { name: "Dig", type: "ground" },
  { name: "Dire Claw", type: "poison" },
  { name: "Disable", type: "normal" },
  { name: "Disarming Voice", type: "fairy" },
  { name: "Discharge", type: "electric" },
  { name: "Dive", type: "water" },
  { name: "Dizzy Punch", type: "normal" },
  { name: "Doodle", type: "normal" },
  { name: "Doom Desire", type: "steel" },
  { name: "Double Hit", type: "normal" },
  { name: "Double Iron Bash", type: "steel" },
  { name: "Double Kick", type: "fighting" },
  { name: "Double Shock", type: "electric" },
  { name: "Double Slap", type: "normal" },
  { name: "Double Team", type: "normal" },
  { name: "Double-Edge", type: "normal" },
  { name: "Draco Meteor", type: "dragon" },
  { name: "Dragon Ascent", type: "flying" },
  { name: "Dragon Breath", type: "dragon" },
  { name: "Dragon Cheer", type: "dragon" },
  { name: "Dragon Claw", type: "dragon" },
  { name: "Dragon Dance", type: "dragon" },
  { name: "Dragon Darts", type: "dragon" },
  { name: "Dragon Energy", type: "dragon" },
  { name: "Dragon Hammer", type: "dragon" },
  { name: "Dragon Pulse", type: "dragon" },
  { name: "Dragon Rage", type: "dragon" },
  { name: "Dragon Rush", type: "dragon" },
  { name: "Dragon Tail", type: "dragon" },
  { name: "Drain Punch", type: "fighting" },
  { name: "Draining Kiss", type: "fairy" },
  { name: "Dream Eater", type: "psychic" },
  { name: "Drill Peck", type: "flying" },
  { name: "Drill Run", type: "ground" },
  { name: "Drum Beating", type: "grass" },
  { name: "Dual Chop", type: "dragon" },
  { name: "Dual Wingbeat", type: "flying" },
  { name: "Dynamax Cannon", type: "dragon" },
  { name: "Dynamic Punch", type: "fighting" },
  { name: "Earth Power", type: "ground" },
  { name: "Earthquake", type: "ground" },
  { name: "Echoed Voice", type: "normal" },
  { name: "Eerie Impulse", type: "electric" },
  { name: "Eerie Spell", type: "psychic" },
  { name: "Egg Bomb", type: "normal" },
  { name: "Electric Terrain", type: "electric" },
  { name: "Electrify", type: "electric" },
  { name: "Electro Ball", type: "electric" },
  { name: "Electro Drift", type: "electric" },
  { name: "Electro Shot", type: "electric" },
  { name: "Electroweb", type: "electric" },
  { name: "Embargo", type: "dark" },
  { name: "Ember", type: "fire" },
  { name: "Encore", type: "normal" },
  { name: "Endeavor", type: "normal" },
  { name: "Endure", type: "normal" },
  { name: "Energy Ball", type: "grass" },
  { name: "Entrainment", type: "normal" },
  { name: "Eruption", type: "fire" },
  { name: "Esper Wing", type: "psychic" },
  { name: "Eternabeam", type: "dragon" },
  { name: "Expanding Force", type: "psychic" },
  { name: "Explosion", type: "normal" },
  { name: "Extrasensory", type: "psychic" },
  { name: "Extreme Evoboost", type: "normal" },
  { name: "Extreme Speed", type: "normal" },
  { name: "Facade", type: "normal" },
  { name: "Fairy Lock", type: "fairy" },
  { name: "Fairy Wind", type: "fairy" },
  { name: "Fake Out", type: "normal" },
  { name: "Fake Tears", type: "dark" },
  { name: "False Surrender", type: "dark" },
  { name: "False Swipe", type: "normal" },
  { name: "Feather Dance", type: "flying" },
  { name: "Feint", type: "normal" },
  { name: "Feint Attack", type: "dark" },
  { name: "Fell Stinger", type: "bug" },
  { name: "Fickle Beam", type: "dragon" },
  { name: "Fiery Dance", type: "fire" },
  { name: "Fiery Wrath", type: "dark" },
  { name: "Fillet Away", type: "normal" },
  { name: "Final Gambit", type: "fighting" },
  { name: "Fire Blast", type: "fire" },
  { name: "Fire Fang", type: "fire" },
  { name: "Fire Lash", type: "fire" },
  { name: "Fire Pledge", type: "fire" },
  { name: "Fire Punch", type: "fire" },
  { name: "Fire Spin", type: "fire" },
  { name: "First Impression", type: "bug" },
  { name: "Fishious Rend", type: "water" },
  { name: "Fissure", type: "ground" },
  { name: "Flail", type: "normal" },
  { name: "Flame Burst", type: "fire" },
  { name: "Flame Charge", type: "fire" },
  { name: "Flame Wheel", type: "fire" },
  { name: "Flamethrower", type: "fire" },
  { name: "Flare Blitz", type: "fire" },
  { name: "Flash", type: "normal" },
  { name: "Flash Cannon", type: "steel" },
  { name: "Flatter", type: "dark" },
  { name: "Fleur Cannon", type: "fairy" },
  { name: "Fling", type: "dark" },
  { name: "Flip Turn", type: "water" },
  { name: "Floaty Fall", type: "flying" },
  { name: "Floral Healing", type: "fairy" },
  { name: "Flower Shield", type: "fairy" },
  { name: "Flower Trick", type: "grass" },
  { name: "Fly", type: "flying" },
  { name: "Flying Press", type: "fighting" },
  { name: "Focus Blast", type: "fighting" },
  { name: "Focus Energy", type: "normal" },
  { name: "Focus Punch", type: "fighting" },
  { name: "Follow Me", type: "normal" },
  { name: "Force Palm", type: "fighting" },
  { name: "Foresight", type: "normal" },
  { name: "Forest's Curse", type: "grass" },
  { name: "Foul Play", type: "dark" },
  { name: "Freeze Shock", type: "ice" },
  { name: "Freeze-Dry", type: "ice" },
  { name: "Freezing Glare", type: "psychic" },
  { name: "Freezy Frost", type: "ice" },
  { name: "Frenzy Plant", type: "grass" },
  { name: "Frost Breath", type: "ice" },
  { name: "Frustration", type: "normal" },
  { name: "Fury Attack", type: "normal" },
  { name: "Fury Cutter", type: "bug" },
  { name: "Fury Swipes", type: "normal" },
  { name: "Fusion Bolt", type: "electric" },
  { name: "Fusion Flare", type: "fire" },
  { name: "Future Sight", type: "psychic" },
  { name: "G-Max Befuddle", type: "bug" },
  { name: "G-Max Cannonade", type: "water" },
  { name: "G-Max Centiferno", type: "fire" },
  { name: "G-Max Chi Strike", type: "fighting" },
  { name: "G-Max Cuddle", type: "normal" },
  { name: "G-Max Depletion", type: "dragon" },
  { name: "G-Max Drum Solo", type: "grass" },
  { name: "G-Max Finale", type: "fairy" },
  { name: "G-Max Fireball", type: "fire" },
  { name: "G-Max Foam Burst", type: "water" },
  { name: "G-Max Gold Rush", type: "normal" },
  { name: "G-Max Gravitas", type: "psychic" },
  { name: "G-Max Hydrosnipe", type: "water" },
  { name: "G-Max Malodor", type: "poison" },
  { name: "G-Max Meltdown", type: "steel" },
  { name: "G-Max One Blow", type: "dark" },
  { name: "G-Max Rapid Flow", type: "water" },
  { name: "G-Max Replenish", type: "normal" },
  { name: "G-Max Resonance", type: "ice" },
  { name: "G-Max Sandblast", type: "ground" },
  { name: "G-Max Smite", type: "fairy" },
  { name: "G-Max Snooze", type: "dark" },
  { name: "G-Max Steelsurge", type: "steel" },
  { name: "G-Max Stonesurge", type: "water" },
  { name: "G-Max Stun Shock", type: "electric" },
  { name: "G-Max Sweetness", type: "grass" },
  { name: "G-Max Tartness", type: "grass" },
  { name: "G-Max Terror", type: "ghost" },
  { name: "G-Max Vine Lash", type: "grass" },
  { name: "G-Max Volcalith", type: "rock" },
  { name: "G-Max Volt Crash", type: "electric" },
  { name: "G-Max Wildfire", type: "fire" },
  { name: "G-Max Wind Rage", type: "flying" },
  { name: "Gastro Acid", type: "poison" },
  { name: "Gear Grind", type: "steel" },
  { name: "Gear Up", type: "steel" },
  { name: "Genesis Supernova", type: "psychic" },
  { name: "Geomancy", type: "fairy" },
  { name: "Giga Drain", type: "grass" },
  { name: "Giga Impact", type: "normal" },
  { name: "Gigaton Hammer", type: "steel" },
  { name: "Gigavolt Havoc", type: "electric" },
  { name: "Glacial Lance", type: "ice" },
  { name: "Glaciate", type: "ice" },
  { name: "Glaive Rush", type: "dragon" },
  { name: "Glare", type: "normal" },
  { name: "Glitzy Glow", type: "psychic" },
  { name: "Grass Knot", type: "grass" },
  { name: "Grass Pledge", type: "grass" },
  { name: "Grass Whistle", type: "grass" },
  { name: "Grassy Glide", type: "grass" },
  { name: "Grassy Terrain", type: "grass" },
  { name: "Grav Apple", type: "grass" },
  { name: "Gravity", type: "psychic" },
  { name: "Growl", type: "normal" },
  { name: "Growth", type: "normal" },
  { name: "Grudge", type: "ghost" },
  { name: "Guard Split", type: "psychic" },
  { name: "Guard Swap", type: "psychic" },
  { name: "Guardian of Alola", type: "fairy" },
  { name: "Guillotine", type: "normal" },
  { name: "Gunk Shot", type: "poison" },
  { name: "Gust", type: "flying" },
  { name: "Gyro Ball", type: "steel" },
  { name: "Hail", type: "ice" },
  { name: "Hammer Arm", type: "fighting" },
  { name: "Happy Hour", type: "normal" },
  { name: "Hard Press", type: "steel" },
  { name: "Harden", type: "normal" },
  { name: "Haze", type: "ice" },
  { name: "Head Charge", type: "normal" },
  { name: "Head Smash", type: "rock" },
  { name: "Headbutt", type: "normal" },
  { name: "Headlong Rush", type: "ground" },
  { name: "Heal Bell", type: "normal" },
  { name: "Heal Block", type: "psychic" },
  { name: "Heal Order", type: "bug" },
  { name: "Heal Pulse", type: "psychic" },
  { name: "Healing Wish", type: "psychic" },
  { name: "Heart Stamp", type: "psychic" },
  { name: "Heart Swap", type: "psychic" },
  { name: "Heat Crash", type: "fire" },
  { name: "Heat Wave", type: "fire" },
  { name: "Heavy Slam", type: "steel" },
  { name: "Helping Hand", type: "normal" },
  { name: "Hex", type: "ghost" },
  { name: "Hidden Power", type: "normal" },
  { name: "High Horsepower", type: "ground" },
  { name: "High Jump Kick", type: "fighting" },
  { name: "Hold Back", type: "normal" },
  { name: "Hold Hands", type: "normal" },
  { name: "Hone Claws", type: "dark" },
  { name: "Horn Attack", type: "normal" },
  { name: "Horn Drill", type: "normal" },
  { name: "Horn Leech", type: "grass" },
  { name: "Howl", type: "normal" },
  { name: "Hurricane", type: "flying" },
  { name: "Hydro Cannon", type: "water" },
  { name: "Hydro Pump", type: "water" },
  { name: "Hydro Steam", type: "water" },
  { name: "Hydro Vortex", type: "water" },
  { name: "Hyper Beam", type: "normal" },
  { name: "Hyper Drill", type: "normal" },
  { name: "Hyper Fang", type: "normal" },
  { name: "Hyper Voice", type: "normal" },
  { name: "Hyperspace Fury", type: "dark" },
  { name: "Hyperspace Hole", type: "psychic" },
  { name: "Hypnosis", type: "psychic" },
  { name: "Ice Ball", type: "ice" },
  { name: "Ice Beam", type: "ice" },
  { name: "Ice Burn", type: "ice" },
  { name: "Ice Fang", type: "ice" },
  { name: "Ice Hammer", type: "ice" },
  { name: "Ice Punch", type: "ice" },
  { name: "Ice Shard", type: "ice" },
  { name: "Ice Spinner", type: "ice" },
  { name: "Icicle Crash", type: "ice" },
  { name: "Icicle Spear", type: "ice" },
  { name: "Icy Wind", type: "ice" },
  { name: "Imprison", type: "psychic" },
  { name: "Incinerate", type: "fire" },
  { name: "Infernal Parade", type: "ghost" },
  { name: "Inferno", type: "fire" },
  { name: "Inferno Overdrive", type: "fire" },
  { name: "Infestation", type: "bug" },
  { name: "Ingrain", type: "grass" },
  { name: "Instruct", type: "psychic" },
  { name: "Ion Deluge", type: "electric" },
  { name: "Iron Defense", type: "steel" },
  { name: "Iron Head", type: "steel" },
  { name: "Iron Tail", type: "steel" },
  { name: "Ivy Cudgel", type: "grass" },
  { name: "Jaw Lock", type: "dark" },
  { name: "Jet Punch", type: "water" },
  { name: "Judgment", type: "normal" },
  { name: "Jump Kick", type: "fighting" },
  { name: "Jungle Healing", type: "grass" },
  { name: "Karate Chop", type: "fighting" },
  { name: "Kinesis", type: "psychic" },
  { name: "King's Shield", type: "steel" },
  { name: "Knock Off", type: "dark" },
  { name: "Kowtow Cleave", type: "dark" },
  { name: "Land's Wrath", type: "ground" },
  { name: "Laser Focus", type: "normal" },
  { name: "Lash Out", type: "dark" },
  { name: "Last Resort", type: "normal" },
  { name: "Last Respects", type: "ghost" },
  { name: "Lava Plume", type: "fire" },
  { name: "Leaf Blade", type: "grass" },
  { name: "Leaf Storm", type: "grass" },
  { name: "Leaf Tornado", type: "grass" },
  { name: "Leafage", type: "grass" },
  { name: "Leech Life", type: "bug" },
  { name: "Leech Seed", type: "grass" },
  { name: "Leer", type: "normal" },
  { name: "Let's Snuggle Forever", type: "fairy" },
  { name: "Lick", type: "ghost" },
  { name: "Life Dew", type: "water" },
  { name: "Light of Ruin", type: "fairy" },
  { name: "Light Screen", type: "psychic" },
  { name: "Light That Burns the Sky", type: "psychic" },
  { name: "Liquidation", type: "water" },
  { name: "Lock-On", type: "normal" },
  { name: "Lovely Kiss", type: "normal" },
  { name: "Low Kick", type: "fighting" },
  { name: "Low Sweep", type: "fighting" },
  { name: "Lucky Chant", type: "normal" },
  { name: "Lumina Crash", type: "psychic" },
  { name: "Lunar Blessing", type: "psychic" },
  { name: "Lunar Dance", type: "psychic" },
  { name: "Lunge", type: "bug" },
  { name: "Luster Purge", type: "psychic" },
  { name: "Mach Punch", type: "fighting" },
  { name: "Magic Coat", type: "psychic" },
  { name: "Magic Powder", type: "psychic" },
  { name: "Magic Room", type: "psychic" },
  { name: "Magical Leaf", type: "grass" },
  { name: "Magical Torque", type: "fairy" },
  { name: "Magma Storm", type: "fire" },
  { name: "Magnet Bomb", type: "steel" },
  { name: "Magnet Rise", type: "electric" },
  { name: "Magnetic Flux", type: "electric" },
  { name: "Magnitude", type: "ground" },
  { name: "Make It Rain", type: "steel" },
  { name: "Malicious Moonsault", type: "dark" },
  { name: "Malignant Chain", type: "poison" },
  { name: "Mat Block", type: "fighting" },
  { name: "Matcha Gotcha", type: "grass" },
  { name: "Max Airstream", type: "flying" },
  { name: "Max Darkness", type: "dark" },
  { name: "Max Flare", type: "fire" },
  { name: "Max Flutterby", type: "bug" },
  { name: "Max Geyser", type: "water" },
  { name: "Max Guard", type: "normal" },
  { name: "Max Hailstorm", type: "ice" },
  { name: "Max Knuckle", type: "fighting" },
  { name: "Max Lightning", type: "electric" },
  { name: "Max Mindstorm", type: "psychic" },
  { name: "Max Ooze", type: "poison" },
  { name: "Max Overgrowth", type: "grass" },
  { name: "Max Phantasm", type: "ghost" },
  { name: "Max Quake", type: "ground" },
  { name: "Max Rockfall", type: "rock" },
  { name: "Max Starfall", type: "fairy" },
  { name: "Max Steelspike", type: "steel" },
  { name: "Max Strike", type: "normal" },
  { name: "Max Wyrmwind", type: "dragon" },
  { name: "Me First", type: "normal" },
  { name: "Mean Look", type: "normal" },
  { name: "Meditate", type: "psychic" },
  { name: "Mega Drain", type: "grass" },
  { name: "Mega Kick", type: "normal" },
  { name: "Mega Punch", type: "normal" },
  { name: "Megahorn", type: "bug" },
  { name: "Memento", type: "dark" },
  { name: "Menacing Moonraze Maelstrom", type: "ghost" },
  { name: "Metal Burst", type: "steel" },
  { name: "Metal Claw", type: "steel" },
  { name: "Metal Sound", type: "steel" },
  { name: "Meteor Assault", type: "fighting" },
  { name: "Meteor Beam", type: "rock" },
  { name: "Meteor Mash", type: "steel" },
  { name: "Metronome", type: "normal" },
  { name: "Mighty Cleave", type: "rock" },
  { name: "Milk Drink", type: "normal" },
  { name: "Mimic", type: "normal" },
  { name: "Mind Blown", type: "fire" },
  { name: "Mind Reader", type: "normal" },
  { name: "Minimize", type: "normal" },
  { name: "Miracle Eye", type: "psychic" },
  { name: "Mirror Coat", type: "psychic" },
  { name: "Mirror Move", type: "flying" },
  { name: "Mirror Shot", type: "steel" },
  { name: "Mist", type: "ice" },
  { name: "Mist Ball", type: "psychic" },
  { name: "Misty Explosion", type: "fairy" },
  { name: "Misty Terrain", type: "fairy" },
  { name: "Moonblast", type: "fairy" },
  { name: "Moongeist Beam", type: "ghost" },
  { name: "Moonlight", type: "fairy" },
  { name: "Morning Sun", type: "normal" },
  { name: "Mortal Spin", type: "poison" },
  { name: "Mountain Gale", type: "ice" },
  { name: "Mud Bomb", type: "ground" },
  { name: "Mud Shot", type: "ground" },
  { name: "Mud Sport", type: "ground" },
  { name: "Mud-Slap", type: "ground" },
  { name: "Muddy Water", type: "water" },
  { name: "Multi-Attack", type: "normal" },
  { name: "Mystical Fire", type: "fire" },
  { name: "Mystical Power", type: "psychic" },
  { name: "Nasty Plot", type: "dark" },
  { name: "Natural Gift", type: "normal" },
  { name: "Nature Power", type: "normal" },
  { name: "Nature's Madness", type: "fairy" },
  { name: "Needle Arm", type: "grass" },
  { name: "Never-Ending Nightmare", type: "ghost" },
  { name: "Night Daze", type: "dark" },
  { name: "Night Shade", type: "ghost" },
  { name: "Night Slash", type: "dark" },
  { name: "Nightmare", type: "ghost" },
  { name: "No Retreat", type: "fighting" },
  { name: "Noble Roar", type: "normal" },
  { name: "Noxious Torque", type: "poison" },
  { name: "Nuzzle", type: "electric" },
  { name: "Oblivion Wing", type: "flying" },
  { name: "Obstruct", type: "dark" },
  { name: "Oceanic Operetta", type: "water" },
  { name: "Octazooka", type: "water" },
  { name: "Octolock", type: "fighting" },
  { name: "Odor Sleuth", type: "normal" },
  { name: "Ominous Wind", type: "ghost" },
  { name: "Order Up", type: "dragon" },
  { name: "Origin Pulse", type: "water" },
  { name: "Outrage", type: "dragon" },
  { name: "Overdrive", type: "electric" },
  { name: "Overheat", type: "fire" },
  { name: "Pain Split", type: "normal" },
  { name: "Parabolic Charge", type: "electric" },
  { name: "Parting Shot", type: "dark" },
  { name: "Pay Day", type: "normal" },
  { name: "Payback", type: "dark" },
  { name: "Peck", type: "flying" },
  { name: "Perish Song", type: "normal" },
  { name: "Petal Blizzard", type: "grass" },
  { name: "Petal Dance", type: "grass" },
  { name: "Phantom Force", type: "ghost" },
  { name: "Photon Geyser", type: "psychic" },
  { name: "Pika Papow", type: "electric" },
  { name: "Pin Missile", type: "bug" },
  { name: "Plasma Fists", type: "electric" },
  { name: "Play Nice", type: "normal" },
  { name: "Play Rough", type: "fairy" },
  { name: "Pluck", type: "flying" },
  { name: "Poison Fang", type: "poison" },
  { name: "Poison Gas", type: "poison" },
  { name: "Poison Jab", type: "poison" },
  { name: "Poison Powder", type: "poison" },
  { name: "Poison Sting", type: "poison" },
  { name: "Poison Tail", type: "poison" },
  { name: "Pollen Puff", type: "bug" },
  { name: "Poltergeist", type: "ghost" },
  { name: "Population Bomb", type: "normal" },
  { name: "Pounce", type: "bug" },
  { name: "Pound", type: "normal" },
  { name: "Powder", type: "bug" },
  { name: "Powder Snow", type: "ice" },
  { name: "Power Gem", type: "rock" },
  { name: "Power Shift", type: "normal" },
  { name: "Power Split", type: "psychic" },
  { name: "Power Swap", type: "psychic" },
  { name: "Power Trick", type: "psychic" },
  { name: "Power Trip", type: "dark" },
  { name: "Power Whip", type: "grass" },
  { name: "Power-Up Punch", type: "fighting" },
  { name: "Precipice Blades", type: "ground" },
  { name: "Present", type: "normal" },
  { name: "Prismatic Laser", type: "psychic" },
  { name: "Protect", type: "normal" },
  { name: "Psybeam", type: "psychic" },
  { name: "Psyblade", type: "psychic" },
  { name: "Psych Up", type: "normal" },
  { name: "Psychic", type: "psychic" },
  { name: "Psychic Fangs", type: "psychic" },
  { name: "Psychic Noise", type: "psychic" },
  { name: "Psychic Terrain", type: "psychic" },
  { name: "Psycho Boost", type: "psychic" },
  { name: "Psycho Cut", type: "psychic" },
  { name: "Psycho Shift", type: "psychic" },
  { name: "Psyshield Bash", type: "psychic" },
  { name: "Psyshock", type: "psychic" },
  { name: "Psystrike", type: "psychic" },
  { name: "Psywave", type: "psychic" },
  { name: "Pulverizing Pancake", type: "normal" },
  { name: "Punishment", type: "dark" },
  { name: "Purify", type: "poison" },
  { name: "Pursuit", type: "dark" },
  { name: "Pyro Ball", type: "fire" },
  { name: "Quash", type: "dark" },
  { name: "Quick Attack", type: "normal" },
  { name: "Quick Guard", type: "fighting" },
  { name: "Quiver Dance", type: "bug" },
  { name: "Rage", type: "normal" },
  { name: "Rage Fist", type: "ghost" },
  { name: "Rage Powder", type: "bug" },
  { name: "Raging Bull", type: "normal" },
  { name: "Raging Fury", type: "fire" },
  { name: "Rain Dance", type: "water" },
  { name: "Rapid Spin", type: "normal" },
  { name: "Razor Leaf", type: "grass" },
  { name: "Razor Shell", type: "water" },
  { name: "Razor Wind", type: "normal" },
  { name: "Recover", type: "normal" },
  { name: "Recycle", type: "normal" },
  { name: "Reflect", type: "psychic" },
  { name: "Reflect Type", type: "normal" },
  { name: "Refresh", type: "normal" },
  { name: "Relic Song", type: "normal" },
  { name: "Rest", type: "psychic" },
  { name: "Retaliate", type: "normal" },
  { name: "Return", type: "normal" },
  { name: "Revelation Dance", type: "normal" },
  { name: "Revenge", type: "fighting" },
  { name: "Reversal", type: "fighting" },
  { name: "Revival Blessing", type: "normal" },
  { name: "Rising Voltage", type: "electric" },
  { name: "Roar", type: "normal" },
  { name: "Roar of Time", type: "dragon" },
  { name: "Rock Blast", type: "rock" },
  { name: "Rock Climb", type: "normal" },
  { name: "Rock Polish", type: "rock" },
  { name: "Rock Slide", type: "rock" },
  { name: "Rock Smash", type: "fighting" },
  { name: "Rock Throw", type: "rock" },
  { name: "Rock Tomb", type: "rock" },
  { name: "Rock Wrecker", type: "rock" },
  { name: "Role Play", type: "psychic" },
  { name: "Rolling Kick", type: "fighting" },
  { name: "Rollout", type: "rock" },
  { name: "Roost", type: "flying" },
  { name: "Rototiller", type: "ground" },
  { name: "Round", type: "normal" },
  { name: "Ruination", type: "dark" },
  { name: "Sacred Fire", type: "fire" },
  { name: "Sacred Sword", type: "fighting" },
  { name: "Safeguard", type: "normal" },
  { name: "Salt Cure", type: "rock" },
  { name: "Sand Attack", type: "ground" },
  { name: "Sand Tomb", type: "ground" },
  { name: "Sandsear Storm", type: "ground" },
  { name: "Sandstorm", type: "rock" },
  { name: "Sappy Seed", type: "grass" },
  { name: "Savage Spin-Out", type: "bug" },
  { name: "Scald", type: "water" },
  { name: "Scale Shot", type: "dragon" },
  { name: "Scary Face", type: "normal" },
  { name: "Scorching Sands", type: "ground" },
  { name: "Scratch", type: "normal" },
  { name: "Screech", type: "normal" },
  { name: "Searing Shot", type: "fire" },
  { name: "Searing Sunraze Smash", type: "steel" },
  { name: "Secret Power", type: "normal" },
  { name: "Secret Sword", type: "fighting" },
  { name: "Seed Bomb", type: "grass" },
  { name: "Seed Flare", type: "grass" },
  { name: "Seismic Toss", type: "fighting" },
  { name: "Self-Destruct", type: "normal" },
  { name: "Shadow Ball", type: "ghost" },
  { name: "Shadow Bone", type: "ghost" },
  { name: "Shadow Claw", type: "ghost" },
  { name: "Shadow Force", type: "ghost" },
  { name: "Shadow Punch", type: "ghost" },
  { name: "Shadow Sneak", type: "ghost" },
  { name: "Sharpen", type: "normal" },
  { name: "Shattered Psyche", type: "psychic" },
  { name: "Shed Tail", type: "normal" },
  { name: "Sheer Cold", type: "ice" },
  { name: "Shell Side Arm", type: "poison" },
  { name: "Shell Smash", type: "normal" },
  { name: "Shell Trap", type: "fire" },
  { name: "Shelter", type: "steel" },
  { name: "Shift Gear", type: "steel" },
  { name: "Shock Wave", type: "electric" },
  { name: "Shore Up", type: "ground" },
  { name: "Signal Beam", type: "bug" },
  { name: "Silk Trap", type: "bug" },
  { name: "Silver Wind", type: "bug" },
  { name: "Simple Beam", type: "normal" },
  { name: "Sing", type: "normal" },
  { name: "Sinister Arrow Raid", type: "ghost" },
  { name: "Sizzly Slide", type: "fire" },
  { name: "Sketch", type: "normal" },
  { name: "Skill Swap", type: "psychic" },
  { name: "Skitter Smack", type: "bug" },
  { name: "Skull Bash", type: "normal" },
  { name: "Sky Attack", type: "flying" },
  { name: "Sky Drop", type: "flying" },
  { name: "Sky Uppercut", type: "fighting" },
  { name: "Slack Off", type: "normal" },
  { name: "Slam", type: "normal" },
  { name: "Slash", type: "normal" },
  { name: "Sleep Powder", type: "grass" },
  { name: "Sleep Talk", type: "normal" },
  { name: "Sludge", type: "poison" },
  { name: "Sludge Bomb", type: "poison" },
  { name: "Sludge Wave", type: "poison" },
  { name: "Smack Down", type: "rock" },
  { name: "Smart Strike", type: "steel" },
  { name: "Smelling Salts", type: "normal" },
  { name: "Smog", type: "poison" },
  { name: "Smokescreen", type: "normal" },
  { name: "Snap Trap", type: "grass" },
  { name: "Snarl", type: "dark" },
  { name: "Snatch", type: "dark" },
  { name: "Snipe Shot", type: "water" },
  { name: "Snore", type: "normal" },
  { name: "Snowscape", type: "ice" },
  { name: "Soak", type: "water" },
  { name: "Soft-Boiled", type: "normal" },
  { name: "Solar Beam", type: "grass" },
  { name: "Solar Blade", type: "grass" },
  { name: "Sonic Boom", type: "normal" },
  { name: "Soul-Stealing 7-Star Strike", type: "ghost" },
  { name: "Spacial Rend", type: "dragon" },
  { name: "Spark", type: "electric" },
  { name: "Sparkling Aria", type: "water" },
  { name: "Sparkly Swirl", type: "fairy" },
  { name: "Spectral Thief", type: "ghost" },
  { name: "Speed Swap", type: "psychic" },
  { name: "Spicy Extract", type: "grass" },
  { name: "Spider Web", type: "bug" },
  { name: "Spike Cannon", type: "normal" },
  { name: "Spikes", type: "ground" },
  { name: "Spiky Shield", type: "grass" },
  { name: "Spin Out", type: "steel" },
  { name: "Spirit Break", type: "fairy" },
  { name: "Spirit Shackle", type: "ghost" },
  { name: "Spit Up", type: "normal" },
  { name: "Spite", type: "ghost" },
  { name: "Splash", type: "normal" },
  { name: "Splintered Stormshards", type: "rock" },
  { name: "Splishy Splash", type: "water" },
  { name: "Spore", type: "grass" },
  { name: "Spotlight", type: "normal" },
  { name: "Springtide Storm", type: "fairy" },
  { name: "Stealth Rock", type: "rock" },
  { name: "Steam Eruption", type: "water" },
  { name: "Steamroller", type: "bug" },
  { name: "Steel Beam", type: "steel" },
  { name: "Steel Roller", type: "steel" },
  { name: "Steel Wing", type: "steel" },
  { name: "Sticky Web", type: "bug" },
  { name: "Stockpile", type: "normal" },
  { name: "Stoked Sparksurfer", type: "electric" },
  { name: "Stomp", type: "normal" },
  { name: "Stomping Tantrum", type: "ground" },
  { name: "Stone Axe", type: "rock" },
  { name: "Stone Edge", type: "rock" },
  { name: "Stored Power", type: "psychic" },
  { name: "Storm Throw", type: "fighting" },
  { name: "Strange Steam", type: "fairy" },
  { name: "Strength", type: "normal" },
  { name: "Strength Sap", type: "grass" },
  { name: "String Shot", type: "bug" },
  { name: "Struggle", type: "normal" },
  { name: "Struggle Bug", type: "bug" },
  { name: "Stuff Cheeks", type: "normal" },
  { name: "Stun Spore", type: "grass" },
  { name: "Submission", type: "fighting" },
  { name: "Substitute", type: "normal" },
  { name: "Subzero Slammer", type: "ice" },
  { name: "Sucker Punch", type: "dark" },
  { name: "Sunny Day", type: "fire" },
  { name: "Sunsteel Strike", type: "steel" },
  { name: "Super Fang", type: "normal" },
  { name: "Supercell Slam", type: "electric" },
  { name: "Superpower", type: "fighting" },
  { name: "Supersonic", type: "normal" },
  { name: "Supersonic Skystrike", type: "flying" },
  { name: "Surf", type: "water" },
  { name: "Surging Strikes", type: "water" },
  { name: "Swagger", type: "normal" },
  { name: "Swallow", type: "normal" },
  { name: "Sweet Kiss", type: "fairy" },
  { name: "Sweet Scent", type: "normal" },
  { name: "Swift", type: "normal" },
  { name: "Switcheroo", type: "dark" },
  { name: "Swords Dance", type: "normal" },
  { name: "Synchronoise", type: "psychic" },
  { name: "Synthesis", type: "grass" },
  { name: "Syrup Bomb", type: "grass" },
  { name: "Tachyon Cutter", type: "steel" },
  { name: "Tackle", type: "normal" },
  { name: "Tail Glow", type: "bug" },
  { name: "Tail Slap", type: "normal" },
  { name: "Tail Whip", type: "normal" },
  { name: "Tailwind", type: "flying" },
  { name: "Take Down", type: "normal" },
  { name: "Take Heart", type: "psychic" },
  { name: "Tar Shot", type: "rock" },
  { name: "Taunt", type: "dark" },
  { name: "Tearful Look", type: "normal" },
  { name: "Teatime", type: "normal" },
  { name: "Techno Blast", type: "normal" },
  { name: "Tectonic Rage", type: "ground" },
  { name: "Teeter Dance", type: "normal" },
  { name: "Telekinesis", type: "psychic" },
  { name: "Teleport", type: "psychic" },
  { name: "Temper Flare", type: "fire" },
  { name: "Tera Blast", type: "normal" },
  { name: "Tera Starstorm", type: "normal" },
  { name: "Terrain Pulse", type: "normal" },
  { name: "Thief", type: "dark" },
  { name: "Thousand Arrows", type: "ground" },
  { name: "Thousand Waves", type: "ground" },
  { name: "Thrash", type: "normal" },
  { name: "Throat Chop", type: "dark" },
  { name: "Thunder", type: "electric" },
  { name: "Thunder Cage", type: "electric" },
  { name: "Thunder Fang", type: "electric" },
  { name: "Thunder Punch", type: "electric" },
  { name: "Thunder Shock", type: "electric" },
  { name: "Thunder Wave", type: "electric" },
  { name: "Thunderbolt", type: "electric" },
  { name: "Thunderclap", type: "electric" },
  { name: "Thunderous Kick", type: "fighting" },
  { name: "Tickle", type: "normal" },
  { name: "Tidy Up", type: "normal" },
  { name: "Topsy-Turvy", type: "dark" },
  { name: "Torch Song", type: "fire" },
  { name: "Torment", type: "dark" },
  { name: "Toxic", type: "poison" },
  { name: "Toxic Spikes", type: "poison" },
  { name: "Toxic Thread", type: "poison" },
  { name: "Trailblaze", type: "grass" },
  { name: "Transform", type: "normal" },
  { name: "Tri Attack", type: "normal" },
  { name: "Trick", type: "psychic" },
  { name: "Trick Room", type: "psychic" },
  { name: "Trick-or-Treat", type: "ghost" },
  { name: "Triple Arrows", type: "fighting" },
  { name: "Triple Axel", type: "ice" },
  { name: "Triple Dive", type: "water" },
  { name: "Triple Kick", type: "fighting" },
  { name: "Trop Kick", type: "grass" },
  { name: "Trump Card", type: "normal" },
  { name: "Twin Beam", type: "psychic" },
  { name: "Twineedle", type: "bug" },
  { name: "Twinkle Tackle", type: "fairy" },
  { name: "Twister", type: "dragon" },
  { name: "U-turn", type: "bug" },
  { name: "Upper Hand", type: "fighting" },
  { name: "Uproar", type: "normal" },
  { name: "V-create", type: "fire" },
  { name: "Vacuum Wave", type: "fighting" },
  { name: "Veevee Volley", type: "normal" },
  { name: "Venom Drench", type: "poison" },
  { name: "Venoshock", type: "poison" },
  { name: "Victory Dance", type: "fighting" },
  { name: "Vine Whip", type: "grass" },
  { name: "Vise Grip", type: "normal" },
  { name: "Vital Throw", type: "fighting" },
  { name: "Volt Switch", type: "electric" },
  { name: "Volt Tackle", type: "electric" },
  { name: "Wake-Up Slap", type: "fighting" },
  { name: "Water Gun", type: "water" },
  { name: "Water Pledge", type: "water" },
  { name: "Water Pulse", type: "water" },
  { name: "Water Shuriken", type: "water" },
  { name: "Water Sport", type: "water" },
  { name: "Water Spout", type: "water" },
  { name: "Waterfall", type: "water" },
  { name: "Wave Crash", type: "water" },
  { name: "Weather Ball", type: "normal" },
  { name: "Whirlpool", type: "water" },
  { name: "Whirlwind", type: "normal" },
  { name: "Wicked Blow", type: "dark" },
  { name: "Wicked Torque", type: "dark" },
  { name: "Wide Guard", type: "rock" },
  { name: "Wild Charge", type: "electric" },
  { name: "Wildbolt Storm", type: "electric" },
  { name: "Will-O-Wisp", type: "fire" },
  { name: "Wing Attack", type: "flying" },
  { name: "Wish", type: "normal" },
  { name: "Withdraw", type: "water" },
  { name: "Wonder Room", type: "psychic" },
  { name: "Wood Hammer", type: "grass" },
  { name: "Work Up", type: "normal" },
  { name: "Worry Seed", type: "grass" },
  { name: "Wrap", type: "normal" },
  { name: "Wring Out", type: "normal" },
  { name: "X-Scissor", type: "bug" },
  { name: "Yawn", type: "normal" },
  { name: "Zap Cannon", type: "electric" },
  { name: "Zen Headbutt", type: "psychic" },
  { name: "Zing Zap", type: "electric" },
  { name: "Zippy Zap", type: "electric" },
];
