export const POKE_TYPES = [
  "normal",
  "fire",
  "water",
  "electric",
  "grass",
  "ice",
  "fighting",
  "poison",
  "ground",
  "flying",
  "psychic",
  "bug",
  "rock",
  "ghost",
  "dragon",
  "dark",
  "steel",
  "fairy",
] as const;

export type PokeType = (typeof POKE_TYPES)[number];

export const TYPE_LABEL: Record<PokeType, string> = {
  normal: "Normal",
  fire: "Fire",
  water: "Water",
  electric: "Electric",
  grass: "Grass",
  ice: "Ice",
  fighting: "Fighting",
  poison: "Poison",
  ground: "Ground",
  flying: "Flying",
  psychic: "Psychic",
  bug: "Bug",
  rock: "Rock",
  ghost: "Ghost",
  dragon: "Dragon",
  dark: "Dark",
  steel: "Steel",
  fairy: "Fairy",
};

export const TERA_OPTIONS = [...POKE_TYPES, "stellar"] as const;
export type TeraType = (typeof TERA_OPTIONS)[number];

export const TERA_LABEL: Record<TeraType, string> = {
  ...TYPE_LABEL,
  stellar: "Stellar",
};

export type MonTypes = [PokeType | "", PokeType | ""];

export type MoveSlot = {
  name: string;
  type: PokeType | "";
};

export type TeamMon = {
  species: string;
  dex: number;
  types: MonTypes;
  tera: TeraType | "";
  ability: string;
  item: string;
  moves: [MoveSlot, MoveSlot, MoveSlot, MoveSlot];
};

export type SpeciesDef = {
  name: string;
  dex: number;
  spriteDex?: number;
  types: PokeType[];
  abilities: string[];
};

export function speciesArtDex(species: SpeciesDef): number {
  return species.spriteDex ?? species.dex;
}

export function emptyTypes(): MonTypes {
  return ["", ""];
}

export function isPokeType(value: unknown): value is PokeType {
  return typeof value === "string" && (POKE_TYPES as readonly string[]).includes(value);
}

export function typesFromSpecies(name: string): MonTypes {
  const found = findSpecies(name);
  return [found?.types[0] ?? "", found?.types[1] ?? ""];
}

export function mergeTypes(raw: unknown, speciesName = ""): MonTypes {
  const list = Array.isArray(raw) ? raw : [];
  const first = isPokeType(list[0]) ? list[0] : "";
  const second = isPokeType(list[1]) ? list[1] : "";
  if (first || second) return [first, second];
  return typesFromSpecies(speciesName);
}

export function emptyMove(): MoveSlot {
  return { name: "", type: "" };
}

export function emptyMon(): TeamMon {
  return {
    species: "",
    dex: 0,
    types: emptyTypes(),
    tera: "",
    ability: "",
    item: "",
    moves: [emptyMove(), emptyMove(), emptyMove(), emptyMove()],
  };
}

export function emptyTeam(): TeamMon[] {
  return [emptyMon(), emptyMon(), emptyMon(), emptyMon(), emptyMon(), emptyMon()];
}

export function spriteUrl(dex: number): string {
  if (!dex) return "";
  return `https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/${dex}.png`;
}

export const SPECIES: SpeciesDef[] = [
  { name: "Incineroar", dex: 727, types: ["fire", "dark"], abilities: ["Blaze", "Intimidate"] },
  { name: "Archaludon", dex: 1018, types: ["steel", "dragon"], abilities: ["Stamina", "Sturdy", "Stalwart"] },
  { name: "Scovillain", dex: 952, types: ["grass", "fire"], abilities: ["Chlorophyll", "Insomnia", "Moody"] },
  { name: "Espathra", dex: 956, types: ["psychic"], abilities: ["Opportunist", "Frisk", "Speed Boost"] },
  { name: "Politoed", dex: 186, types: ["water"], abilities: ["Water Absorb", "Damp", "Drizzle"] },
  { name: "Sylveon", dex: 700, types: ["fairy"], abilities: ["Cute Charm", "Pixilate"] },
  { name: "Flutter Mane", dex: 987, types: ["ghost", "fairy"], abilities: ["Protosynthesis"] },
  { name: "Amoonguss", dex: 591, types: ["grass", "poison"], abilities: ["Effect Spore", "Regenerator"] },
  { name: "Rillaboom", dex: 812, types: ["grass"], abilities: ["Overgrow", "Grassy Surge"] },
  { name: "Urshifu", dex: 892, types: ["fighting", "dark"], abilities: ["Unseen Fist"] },
  { name: "Urshifu Rapid", dex: 892, spriteDex: 10191, types: ["fighting", "water"], abilities: ["Unseen Fist"] },
  { name: "Ogerpon", dex: 1017, types: ["grass"], abilities: ["Defiant"] },
  { name: "Ogerpon Wellspring", dex: 1017, spriteDex: 10273, types: ["grass", "water"], abilities: ["Water Absorb"] },
  { name: "Ogerpon Hearthflame", dex: 1017, spriteDex: 10274, types: ["grass", "fire"], abilities: ["Mold Breaker"] },
  { name: "Ogerpon Cornerstone", dex: 1017, spriteDex: 10275, types: ["grass", "rock"], abilities: ["Sturdy"] },
  { name: "Farigiraf", dex: 981, types: ["normal", "psychic"], abilities: ["Cud Chew", "Armor Tail", "Sap Sipper"] },
  { name: "Indeedee F", dex: 876, spriteDex: 10186, types: ["psychic", "normal"], abilities: ["Own Tempo", "Synchronize", "Psychic Surge"] },
  { name: "Indeedee M", dex: 876, types: ["psychic", "normal"], abilities: ["Inner Focus", "Synchronize", "Psychic Surge"] },
  { name: "Gholdengo", dex: 1000, types: ["steel", "ghost"], abilities: ["Good as Gold"] },
  { name: "Kingambit", dex: 983, types: ["dark", "steel"], abilities: ["Defiant", "Supreme Overlord", "Pressure"] },
  { name: "Dragonite", dex: 149, types: ["dragon", "flying"], abilities: ["Inner Focus", "Multiscale"] },
  { name: "Garchomp", dex: 445, types: ["dragon", "ground"], abilities: ["Sand Veil", "Rough Skin"] },
  { name: "Torkoal", dex: 324, types: ["fire"], abilities: ["White Smoke", "Drought", "Shell Armor"] },
  { name: "Pelipper", dex: 279, types: ["water", "flying"], abilities: ["Keen Eye", "Drizzle", "Rain Dish"] },
  { name: "Whimsicott", dex: 547, types: ["grass", "fairy"], abilities: ["Prankster", "Infiltrator", "Chlorophyll"] },
  { name: "Tornadus", dex: 641, types: ["flying"], abilities: ["Prankster", "Defiant"] },
  { name: "Landorus", dex: 645, types: ["ground", "flying"], abilities: ["Sand Force", "Sheer Force"] },
  { name: "Landorus Therian", dex: 645, spriteDex: 10021, types: ["ground", "flying"], abilities: ["Intimidate"] },
  { name: "Thundurus", dex: 642, types: ["electric", "flying"], abilities: ["Prankster", "Defiant"] },
  { name: "Chi-Yu", dex: 1004, types: ["dark", "fire"], abilities: ["Beads of Ruin"] },
  { name: "Chien-Pao", dex: 1002, types: ["dark", "ice"], abilities: ["Sword of Ruin"] },
  { name: "Ting-Lu", dex: 1003, types: ["dark", "ground"], abilities: ["Vessel of Ruin"] },
  { name: "Wo-Chien", dex: 1001, types: ["dark", "grass"], abilities: ["Tablets of Ruin"] },
  { name: "Iron Hands", dex: 992, types: ["fighting", "electric"], abilities: ["Quark Drive"] },
  { name: "Iron Bundle", dex: 991, types: ["ice", "water"], abilities: ["Quark Drive"] },
  { name: "Iron Valiant", dex: 1006, types: ["fairy", "fighting"], abilities: ["Quark Drive"] },
  { name: "Iron Crown", dex: 1023, types: ["steel", "psychic"], abilities: ["Quark Drive"] },
  { name: "Iron Treads", dex: 990, types: ["ground", "steel"], abilities: ["Quark Drive"] },
  { name: "Iron Moth", dex: 994, types: ["fire", "poison"], abilities: ["Quark Drive"] },
  { name: "Roaring Moon", dex: 1005, types: ["dragon", "dark"], abilities: ["Protosynthesis"] },
  { name: "Scream Tail", dex: 985, types: ["fairy", "psychic"], abilities: ["Protosynthesis"] },
  { name: "Great Tusk", dex: 984, types: ["ground", "fighting"], abilities: ["Protosynthesis"] },
  { name: "Raging Bolt", dex: 1021, types: ["electric", "dragon"], abilities: ["Protosynthesis"] },
  { name: "Gouging Fire", dex: 1020, types: ["fire", "dragon"], abilities: ["Protosynthesis"] },
  { name: "Walking Wake", dex: 1009, types: ["water", "dragon"], abilities: ["Protosynthesis"] },
  { name: "Calyrex Ice", dex: 898, spriteDex: 10193, types: ["psychic", "ice"], abilities: ["As One"] },
  { name: "Calyrex Shadow", dex: 898, spriteDex: 10194, types: ["psychic", "ghost"], abilities: ["As One"] },
  { name: "Miraidon", dex: 1008, types: ["electric", "dragon"], abilities: ["Hadron Engine"] },
  { name: "Koraidon", dex: 1007, types: ["fighting", "dragon"], abilities: ["Orichalcum Pulse"] },
  { name: "Zamazenta", dex: 889, types: ["fighting"], abilities: ["Dauntless Shield"] },
  { name: "Zacian", dex: 888, types: ["fairy"], abilities: ["Intrepid Sword"] },
  { name: "Kyogre", dex: 382, types: ["water"], abilities: ["Drizzle"] },
  { name: "Groudon", dex: 383, types: ["ground"], abilities: ["Drought"] },
  { name: "Lunala", dex: 792, types: ["psychic", "ghost"], abilities: ["Shadow Shield"] },
  { name: "Solgaleo", dex: 791, types: ["psychic", "steel"], abilities: ["Full Metal Body"] },
  { name: "Eternatus", dex: 890, types: ["poison", "dragon"], abilities: ["Pressure"] },
  { name: "Terapagos", dex: 1024, types: ["normal"], abilities: ["Tera Shift"] },
  { name: "Annihilape", dex: 979, types: ["fighting", "ghost"], abilities: ["Vital Spirit", "Inner Focus", "Defiant"] },
  { name: "Dragapult", dex: 887, types: ["dragon", "ghost"], abilities: ["Clear Body", "Infiltrator", "Cursed Body"] },
  { name: "Glimmora", dex: 970, types: ["rock", "poison"], abilities: ["Toxic Debris", "Corrosion"] },
  { name: "Maushold", dex: 925, types: ["normal"], abilities: ["Friend Guard", "Cheek Pouch", "Technician"] },
  { name: "Dondozo", dex: 977, types: ["water"], abilities: ["Unaware", "Oblivious", "Water Veil"] },
  { name: "Tatsugiri", dex: 978, types: ["dragon", "water"], abilities: ["Commander", "Storm Drain"] },
  { name: "Palafin", dex: 964, types: ["water"], abilities: ["Zero to Hero"] },
  { name: "Baxcalibur", dex: 998, types: ["dragon", "ice"], abilities: ["Thermal Exchange", "Ice Body"] },
  { name: "Garganacl", dex: 934, types: ["rock"], abilities: ["Purifying Salt", "Sturdy", "Clear Body"] },
  { name: "Armarouge", dex: 936, types: ["fire", "psychic"], abilities: ["Flash Fire", "Weak Armor"] },
  { name: "Ceruledge", dex: 937, types: ["fire", "ghost"], abilities: ["Flash Fire", "Weak Armor"] },
  { name: "Kilowattrel", dex: 941, types: ["electric", "flying"], abilities: ["Wind Power", "Volt Absorb", "Competitive"] },
  { name: "Bombirdier", dex: 962, types: ["flying", "dark"], abilities: ["Big Pecks", "Keen Eye", "Rocky Payload"] },
  { name: "Orthworm", dex: 968, types: ["steel"], abilities: ["Earth Eater", "Sand Veil"] },
  { name: "Hatterene", dex: 858, types: ["psychic", "fairy"], abilities: ["Healer", "Anticipation", "Magic Bounce"] },
  { name: "Grimmsnarl", dex: 861, types: ["dark", "fairy"], abilities: ["Prankster", "Frisk", "Pickpocket"] },
  { name: "Tinkaton", dex: 959, types: ["fairy", "steel"], abilities: ["Mold Breaker", "Own Tempo", "Pickpocket"] },
  { name: "Ninetales-A", dex: 38, spriteDex: 10104, types: ["ice", "fairy"], abilities: ["Snow Cloak", "Snow Warning"] },
  { name: "Arcanine-H", dex: 59, spriteDex: 10230, types: ["fire", "rock"], abilities: ["Intimidate", "Flash Fire", "Rock Head"] },
  { name: "Typhlosion-H", dex: 157, spriteDex: 10233, types: ["fire", "ghost"], abilities: ["Blaze", "Frisk"] },
  { name: "Samurott-H", dex: 503, spriteDex: 10236, types: ["water", "dark"], abilities: ["Torrent", "Sharpness"] },
  { name: "Decidueye-H", dex: 724, spriteDex: 10244, types: ["grass", "fighting"], abilities: ["Overgrow", "Scrappy"] },
  { name: "Lilligant-H", dex: 549, spriteDex: 10237, types: ["grass", "fighting"], abilities: ["Chlorophyll", "Hustle", "Leaf Guard"] },
  { name: "Electrode-H", dex: 101, spriteDex: 10232, types: ["electric", "grass"], abilities: ["Soundproof", "Static", "Aftermath"] },
  { name: "Goodra-H", dex: 706, spriteDex: 10242, types: ["steel", "dragon"], abilities: ["Sap Sipper", "Shell Armor", "Gooey"] },
  { name: "Sneasler", dex: 903, types: ["fighting", "poison"], abilities: ["Pressure", "Unburden", "Poison Touch"] },
  { name: "Overqwil", dex: 904, types: ["dark", "poison"], abilities: ["Poison Point", "Swift Swim", "Intimidate"] },
  { name: "Basculegion", dex: 902, types: ["water", "ghost"], abilities: ["Swift Swim", "Adaptability", "Mold Breaker"] },
  { name: "Ursaluna", dex: 901, types: ["ground", "normal"], abilities: ["Guts", "Bulletproof", "Unnerve"] },
  { name: "Ursaluna Bloodmoon", dex: 901, spriteDex: 10272, types: ["ground", "normal"], abilities: ["Mind's Eye"] },
  { name: "Enamorus", dex: 905, types: ["fairy", "flying"], abilities: ["Cute Charm", "Contrary"] },
  { name: "Heatran", dex: 485, types: ["fire", "steel"], abilities: ["Flash Fire", "Flame Body"] },
  { name: "Cresselia", dex: 488, types: ["psychic"], abilities: ["Levitate"] },
  { name: "Regieleki", dex: 894, types: ["electric"], abilities: ["Transistor"] },
  { name: "Regidrago", dex: 895, types: ["dragon"], abilities: ["Dragon's Maw"] },
  { name: "Spectrier", dex: 897, types: ["ghost"], abilities: ["Grim Neigh"] },
  { name: "Glastrier", dex: 896, types: ["ice"], abilities: ["Chilling Neigh"] },
  { name: "Chandelure", dex: 609, types: ["ghost", "fire"], abilities: ["Flash Fire", "Flame Body", "Infiltrator"] },
  { name: "Metagross", dex: 376, types: ["steel", "psychic"], abilities: ["Clear Body", "Light Metal"] },
  { name: "Tyranitar", dex: 248, types: ["rock", "dark"], abilities: ["Sand Stream", "Unnerve"] },
  { name: "Excadrill", dex: 530, types: ["ground", "steel"], abilities: ["Sand Rush", "Sand Force", "Mold Breaker"] },
  { name: "Gastrodon", dex: 423, types: ["water", "ground"], abilities: ["Sticky Hold", "Storm Drain", "Sand Force"] },
  { name: "Porygon2", dex: 233, types: ["normal"], abilities: ["Trace", "Download", "Analytic"] },
  { name: "Porygon-Z", dex: 474, types: ["normal"], abilities: ["Adaptability", "Download", "Analytic"] },
  { name: "Charizard", dex: 6, types: ["fire", "flying"], abilities: ["Blaze", "Solar Power"] },
  { name: "Venusaur", dex: 3, types: ["grass", "poison"], abilities: ["Overgrow", "Chlorophyll"] },
  { name: "Blastoise", dex: 9, types: ["water"], abilities: ["Torrent", "Rain Dish"] },
  { name: "Gengar", dex: 94, types: ["ghost", "poison"], abilities: ["Cursed Body"] },
  { name: "Gyarados", dex: 130, types: ["water", "flying"], abilities: ["Intimidate", "Moxie"] },
  { name: "Lucario", dex: 448, types: ["fighting", "steel"], abilities: ["Steadfast", "Inner Focus", "Justified"] },
  { name: "Gardevoir", dex: 282, types: ["psychic", "fairy"], abilities: ["Synchronize", "Trace", "Telepathy"] },
  { name: "Gallade", dex: 475, types: ["psychic", "fighting"], abilities: ["Steadfast", "Sharpness", "Justified"] },
  { name: "Hydreigon", dex: 635, types: ["dark", "dragon"], abilities: ["Levitate"] },
  { name: "Volcarona", dex: 637, types: ["bug", "fire"], abilities: ["Flame Body", "Swarm"] },
  { name: "Aegislash", dex: 681, types: ["steel", "ghost"], abilities: ["Stance Change"] },
  { name: "Kommo-o", dex: 784, types: ["dragon", "fighting"], abilities: ["Bulletproof", "Soundproof", "Overcoat"] },
  { name: "Primarina", dex: 730, types: ["water", "fairy"], abilities: ["Torrent", "Liquid Voice"] },
  { name: "Corviknight", dex: 823, types: ["flying", "steel"], abilities: ["Pressure", "Unnerve", "Mirror Armor"] },
  { name: "Toxtricity", dex: 849, types: ["electric", "poison"], abilities: ["Punk Rock", "Plus", "Technician"] },
  { name: "Dragalge", dex: 691, types: ["poison", "dragon"], abilities: ["Poison Point", "Poison Touch", "Adaptability"] },
  { name: "Sinistcha", dex: 1013, types: ["grass", "ghost"], abilities: ["Hospitality", "Heatproof"] },
  { name: "Okidogi", dex: 1014, types: ["poison", "fighting"], abilities: ["Toxic Chain", "Guard Dog"] },
  { name: "Munkidori", dex: 1015, types: ["poison", "psychic"], abilities: ["Toxic Chain", "Frisk"] },
  { name: "Fezandipiti", dex: 1016, types: ["poison", "fairy"], abilities: ["Toxic Chain", "Technician"] },
  { name: "Pecharunt", dex: 1025, types: ["poison", "ghost"], abilities: ["Poison Puppeteer"] },
];

export const VGC_ITEMS_RAW = [
  "Ability Shield",
  "Assault Vest",
  "Booster Energy",
  "Choice Band",
  "Choice Scarf",
  "Choice Specs",
  "Clear Amulet",
  "Covert Cloak",
  "Eject Button",
  "Eject Pack",
  "Focus Sash",
  "Life Orb",
  "Loaded Dice",
  "Mental Herb",
  "Mirror Herb",
  "Power Herb",
  "Rocky Helmet",
  "Safety Goggles",
  "Sitrus Berry",
  "Wiki Berry",
  "Iapapa Berry",
  "Aguav Berry",
  "Figy Berry",
  "Mago Berry",
  "Leftovers",
  "Lum Berry",
  "Occa Berry",
  "Colbur Berry",
  "Chople Berry",
  "Kasib Berry",
  "Babiri Berry",
  "Shuca Berry",
  "Yache Berry",
  "Charti Berry",
  "Passho Berry",
  "Rindo Berry",
  "Wacan Berry",
  "Fairy Feather",
  "Punching Glove",
  "Wide Lens",
  "Scope Lens",
  "Weakness Policy",
  "Air Balloon",
  "Red Card",
  "Light Clay",
  "Terrain Extender",
  "Heat Rock",
  "Damp Rock",
  "Smooth Rock",
  "Icy Rock",
  "Throat Spray",
  "Room Service",
  "Heavy-Duty Boots",
  "Expert Belt",
  "Muscle Band",
  "Wise Glasses",
  "Charcoal",
  "Mystic Water",
  "Miracle Seed",
  "Magnet",
  "Never-Melt Ice",
  "Black Belt",
  "Poison Barb",
  "Soft Sand",
  "Sharp Beak",
  "Twisted Spoon",
  "Silver Powder",
  "Hard Stone",
  "Spell Tag",
  "Dragon Fang",
  "Black Glasses",
  "Metal Coat",
  "Pink Bow",
  "Rusted Sword",
  "Rusted Shield",
  "Wellspring Mask",
  "Hearthflame Mask",
  "Cornerstone Mask",
  "Eviolite",
  "Black Sludge",
  "Flame Orb",
  "Toxic Orb",
  "Life Orb",
  "White Herb",
  "Mental Herb",
  "Mirror Herb",
  "Power Herb",
  "Eject Button",
  "Eject Pack",
  "Red Card",
  "Air Balloon",
  "Focus Sash",
  "Focus Band",
  "Binding Band",
  "Iron Ball",
  "Lagging Tail",
  "Shed Shell",
  "Sticky Barb",
  "Float Stone",
  "Ring Target",
  "Protective Pads",
  "Punching Glove",
  "Loaded Dice",
  "Covert Cloak",
  "Clear Amulet",
  "Ability Shield",
  "Booster Energy",
  "Fairy Feather",
  "Throat Spray",
  "Room Service",
  "Blunder Policy",
  "Weakness Policy",
  "Adrenaline Orb",
  "Terrain Extender",
  "Light Clay",
  "Heat Rock",
  "Damp Rock",
  "Smooth Rock",
  "Icy Rock",
  "Electric Seed",
  "Grassy Seed",
  "Misty Seed",
  "Psychic Seed",
  "Safety Goggles",
  "Heavy-Duty Boots",
  "Rocky Helmet",
  "Assault Vest",
  "Choice Band",
  "Choice Scarf",
  "Choice Specs",
  "Expert Belt",
  "Life Orb",
  "Leftovers",
  "Sitrus Berry",
  "Wiki Berry",
  "Iapapa Berry",
  "Aguav Berry",
  "Figy Berry",
  "Mago Berry",
  "Lum Berry",
  "Chesto Berry",
  "Pecha Berry",
  "Rawst Berry",
  "Aspear Berry",
  "Persim Berry",
  "Leppa Berry",
  "Oran Berry",
  "Liechi Berry",
  "Ganlon Berry",
  "Salac Berry",
  "Petaya Berry",
  "Apicot Berry",
  "Starf Berry",
  "Lansat Berry",
  "Micle Berry",
  "Custap Berry",
  "Enigma Berry",
  "Kee Berry",
  "Maranga Berry",
  "Jaboca Berry",
  "Rowap Berry",
  "Roseli Berry",
  "Kasib Berry",
  "Colbur Berry",
  "Babiri Berry",
  "Chople Berry",
  "Charti Berry",
  "Chilan Berry",
  "Coba Berry",
  "Haban Berry",
  "Payapa Berry",
  "Tanga Berry",
  "Wacan Berry",
  "Occa Berry",
  "Passho Berry",
  "Rindo Berry",
  "Shuca Berry",
  "Yache Berry",
  "Kebia Berry",
  "Rusted Sword",
  "Rusted Shield",
  "Wellspring Mask",
  "Hearthflame Mask",
  "Cornerstone Mask",
  "Adamant Crystal",
  "Lustrous Globe",
  "Griseous Core",
  "Booster Energy",
];

export const VGC_ITEMS = [...new Set(VGC_ITEMS_RAW)].sort((a, b) => a.localeCompare(b));

export type MoveDef = { name: string; type: PokeType };

export const VGC_MOVES: MoveDef[] = [
  ["Acrobatics", "flying"],
  ["Aerial Ace", "flying"],
  ["Air Slash", "flying"],
  ["Alluring Voice", "fairy"],
  ["Ancient Power", "rock"],
  ["Aqua Jet", "water"],
  ["Aqua Tail", "water"],
  ["Armor Cannon", "fire"],
  ["Astonish", "ghost"],
  ["Astral Barrage", "ghost"],
  ["Aura Sphere", "fighting"],
  ["Aurora Veil", "ice"],
  ["Axe Kick", "fighting"],
  ["Baton Pass", "normal"],
  ["Behemoth Bash", "steel"],
  ["Behemoth Blade", "steel"],
  ["Bitter Blade", "fire"],
  ["Blizzard", "ice"],
  ["Body Press", "fighting"],
  ["Body Slam", "normal"],
  ["Brave Bird", "flying"],
  ["Breaking Swipe", "dragon"],
  ["Brick Break", "fighting"],
  ["Bug Buzz", "bug"],
  ["Bulk Up", "fighting"],
  ["Bulldoze", "ground"],
  ["Bullet Punch", "steel"],
  ["Calm Mind", "psychic"],
  ["Ceaseless Edge", "dark"],
  ["Chilling Water", "water"],
  ["Chilly Reception", "ice"],
  ["Chloroblast", "grass"],
  ["Clear Smog", "poison"],
  ["Close Combat", "fighting"],
  ["Coaching", "fighting"],
  ["Coil", "poison"],
  ["Collision Course", "fighting"],
  ["Comeuppance", "dark"],
  ["Court Change", "normal"],
  ["Crunch", "dark"],
  ["Dark Pulse", "dark"],
  ["Dazzling Gleam", "fairy"],
  ["Decorate", "fairy"],
  ["Destiny Bond", "ghost"],
  ["Disable", "normal"],
  ["Discharge", "electric"],
  ["Double Shock", "electric"],
  ["Draco Meteor", "dragon"],
  ["Dragon Claw", "dragon"],
  ["Dragon Dance", "dragon"],
  ["Dragon Darts", "dragon"],
  ["Dragon Pulse", "dragon"],
  ["Dragon Tail", "dragon"],
  ["Drain Punch", "fighting"],
  ["Draining Kiss", "fairy"],
  ["Earth Power", "ground"],
  ["Earthquake", "ground"],
  ["Electro Drift", "electric"],
  ["Electro Shot", "electric"],
  ["Electroweb", "electric"],
  ["Encore", "normal"],
  ["Endeavor", "normal"],
  ["Energy Ball", "grass"],
  ["Expanding Force", "psychic"],
  ["Extreme Speed", "normal"],
  ["Facade", "normal"],
  ["Fake Out", "normal"],
  ["Fake Tears", "dark"],
  ["Feint", "normal"],
  ["Fiery Dance", "fire"],
  ["Fiery Wrath", "dark"],
  ["Fire Blast", "fire"],
  ["Fire Punch", "fire"],
  ["Flamethrower", "fire"],
  ["Flare Blitz", "fire"],
  ["Flash Cannon", "steel"],
  ["Fling", "dark"],
  ["Flip Turn", "water"],
  ["Flower Trick", "grass"],
  ["Focus Blast", "fighting"],
  ["Follow Me", "normal"],
  ["Foul Play", "dark"],
  ["Freeze-Dry", "ice"],
  ["Giga Drain", "grass"],
  ["Glacial Lance", "ice"],
  ["Glaive Rush", "dragon"],
  ["Grass Knot", "grass"],
  ["Grassy Glide", "grass"],
  ["Gravity", "psychic"],
  ["Gunk Shot", "poison"],
  ["Gyro Ball", "steel"],
  ["Hard Press", "steel"],
  ["Haze", "ice"],
  ["Headlong Rush", "ground"],
  ["Heat Wave", "fire"],
  ["Heavy Slam", "steel"],
  ["Helping Hand", "normal"],
  ["High Horsepower", "ground"],
  ["High Jump Kick", "fighting"],
  ["Hurricane", "flying"],
  ["Hydro Pump", "water"],
  ["Hyper Voice", "normal"],
  ["Ice Beam", "ice"],
  ["Ice Punch", "ice"],
  ["Ice Shard", "ice"],
  ["Ice Spinner", "ice"],
  ["Icicle Crash", "ice"],
  ["Icy Wind", "ice"],
  ["Imprison", "psychic"],
  ["Incinerate", "fire"],
  ["Iron Defense", "steel"],
  ["Iron Head", "steel"],
  ["Ivy Cudgel", "grass"],
  ["Jet Punch", "water"],
  ["Knock Off", "dark"],
  ["Kowtow Cleave", "dark"],
  ["Last Respects", "ghost"],
  ["Leaf Blade", "grass"],
  ["Leaf Storm", "grass"],
  ["Leech Life", "bug"],
  ["Light Screen", "psychic"],
  ["Liquidation", "water"],
  ["Low Kick", "fighting"],
  ["Lumina Crash", "psychic"],
  ["Lunar Blessing", "psychic"],
  ["Mach Punch", "fighting"],
  ["Make It Rain", "steel"],
  ["Matcha Gotcha", "grass"],
  ["Metal Sound", "steel"],
  ["Meteor Mash", "steel"],
  ["Mighty Cleave", "rock"],
  ["Moonblast", "fairy"],
  ["Moongeist Beam", "ghost"],
  ["Moonlight", "fairy"],
  ["Morning Sun", "normal"],
  ["Mortal Spin", "poison"],
  ["Muddy Water", "water"],
  ["Mystical Fire", "fire"],
  ["Nasty Plot", "dark"],
  ["Night Shade", "ghost"],
  ["Night Slash", "dark"],
  ["Nuzzle", "electric"],
  ["Order Up", "dragon"],
  ["Outrage", "dragon"],
  ["Overheat", "fire"],
  ["Pain Split", "normal"],
  ["Parting Shot", "dark"],
  ["Perish Song", "normal"],
  ["Play Rough", "fairy"],
  ["Poison Jab", "poison"],
  ["Pollen Puff", "bug"],
  ["Population Bomb", "normal"],
  ["Pounce", "bug"],
  ["Power Gem", "rock"],
  ["Power Whip", "grass"],
  ["Protect", "normal"],
  ["Psychic", "psychic"],
  ["Psychic Fangs", "psychic"],
  ["Psychic Noise", "psychic"],
  ["Psycho Cut", "psychic"],
  ["Psyshock", "psychic"],
  ["Rage Fist", "ghost"],
  ["Rage Powder", "bug"],
  ["Rain Dance", "water"],
  ["Rapid Spin", "normal"],
  ["Recover", "normal"],
  ["Reflect", "psychic"],
  ["Rest", "psychic"],
  ["Roar", "normal"],
  ["Rock Slide", "rock"],
  ["Rock Tomb", "rock"],
  ["Sacred Sword", "fighting"],
  ["Salt Cure", "rock"],
  ["Scald", "water"],
  ["Scale Shot", "dragon"],
  ["Scary Face", "normal"],
  ["Screech", "normal"],
  ["Seed Bomb", "grass"],
  ["Shadow Ball", "ghost"],
  ["Shadow Claw", "ghost"],
  ["Shadow Sneak", "ghost"],
  ["Shed Tail", "normal"],
  ["Shock Wave", "electric"],
  ["Silk Trap", "bug"],
  ["Slack Off", "normal"],
  ["Sleep Powder", "grass"],
  ["Sleep Talk", "normal"],
  ["Sludge Bomb", "poison"],
  ["Sludge Wave", "poison"],
  ["Smart Strike", "steel"],
  ["Snarl", "dark"],
  ["Solar Beam", "grass"],
  ["Spicy Extract", "grass"],
  ["Spikes", "ground"],
  ["Spore", "grass"],
  ["Stealth Rock", "rock"],
  ["Stone Axe", "rock"],
  ["Stone Edge", "rock"],
  ["Stored Power", "psychic"],
  ["Struggle Bug", "bug"],
  ["Substitute", "normal"],
  ["Sucker Punch", "dark"],
  ["Sunny Day", "fire"],
  ["Super Fang", "normal"],
  ["Supercell Slam", "electric"],
  ["Surf", "water"],
  ["Surging Strikes", "water"],
  ["Swagger", "normal"],
  ["Sweet Kiss", "fairy"],
  ["Swords Dance", "normal"],
  ["Synthesis", "grass"],
  ["Tachyon Cutter", "steel"],
  ["Tailwind", "flying"],
  ["Take Heart", "psychic"],
  ["Taunt", "dark"],
  ["Tera Blast", "normal"],
  ["Tera Starstorm", "normal"],
  ["Thunder", "electric"],
  ["Thunder Punch", "electric"],
  ["Thunder Wave", "electric"],
  ["Thunderbolt", "electric"],
  ["Thunderclap", "electric"],
  ["Tickle", "normal"],
  ["Torch Song", "fire"],
  ["Toxic", "poison"],
  ["Toxic Spikes", "poison"],
  ["Trailblaze", "grass"],
  ["Transform", "normal"],
  ["Trick", "psychic"],
  ["Trick Room", "psychic"],
  ["Triple Arrows", "fighting"],
  ["Triple Axel", "ice"],
  ["Twin Beam", "psychic"],
  ["U-turn", "bug"],
  ["Upper Hand", "fighting"],
  ["Vacuum Wave", "fighting"],
  ["Volt Switch", "electric"],
  ["Water Pulse", "water"],
  ["Water Shuriken", "water"],
  ["Water Spout", "water"],
  ["Wave Crash", "water"],
  ["Weather Ball", "normal"],
  ["Whirlwind", "normal"],
  ["Wicked Blow", "dark"],
  ["Wide Guard", "rock"],
  ["Wild Charge", "electric"],
  ["Will-O-Wisp", "fire"],
  ["Wood Hammer", "grass"],
  ["X-Scissor", "bug"],
  ["Yawn", "normal"],
  ["Zen Headbutt", "psychic"],
].map(([name, type]) => ({ name, type: type as PokeType }));

export function findMove(name: string): MoveDef | undefined {
  const key = name.trim().toLowerCase();
  if (!key) return undefined;
  return VGC_MOVES.find((m) => m.name.toLowerCase() === key) ?? VGC_MOVES.find((m) => m.name.toLowerCase().startsWith(key));
}

export const VGC_ABILITIES = [...new Set(SPECIES.flatMap((s) => s.abilities))].sort((a, b) => a.localeCompare(b));

export function findSpecies(name: string): SpeciesDef | undefined {
  const key = name.trim().toLowerCase();
  if (!key) return undefined;
  return SPECIES.find((s) => s.name.toLowerCase() === key) ?? SPECIES.find((s) => s.name.toLowerCase().includes(key));
}

export function mergeTeam(raw: unknown): TeamMon[] {
  const list = Array.isArray(raw) ? raw : [];
  return emptyTeam().map((slot, i) => {
    const row = list[i];
    if (!row || typeof row !== "object") return slot;
    const incoming = row as Partial<TeamMon>;
    const moves = Array.isArray(incoming.moves) ? incoming.moves : [];
    const species = typeof incoming.species === "string" ? incoming.species : "";
    return {
      species,
      dex: typeof incoming.dex === "number" ? incoming.dex : 0,
      types: mergeTypes(incoming.types, species),
      tera: TERA_OPTIONS.includes(incoming.tera as TeraType) ? (incoming.tera as TeraType) : "",
      ability: typeof incoming.ability === "string" ? incoming.ability : "",
      item: typeof incoming.item === "string" ? incoming.item : "",
      moves: [0, 1, 2, 3].map((idx) => {
        const move = moves[idx];
        if (!move || typeof move !== "object") return emptyMove();
        return {
          name: typeof move.name === "string" ? move.name : "",
          type: (move.type as PokeType | "") || "",
        };
      }) as TeamMon["moves"],
    };
  });
}

export function sampleTeamA(): TeamMon[] {
  return [
    mon("Scovillain", "fire", "Moody", "Life Orb", [
      ["Flamethrower", "fire"],
      ["Giga Drain", "grass"],
      ["Rage Powder", "bug"],
      ["Protect", "normal"],
    ]),
    mon("Archaludon", "dragon", "Stamina", "Leftovers", [
      ["Dragon Pulse", "dragon"],
      ["Flash Cannon", "steel"],
      ["Electro Shot", "electric"],
      ["Protect", "normal"],
    ]),
    mon("Espathra", "psychic", "Speed Boost", "Colbur Berry", [
      ["Lumina Crash", "psychic"],
      ["Calm Mind", "psychic"],
      ["Baton Pass", "normal"],
      ["Protect", "normal"],
    ]),
    mon("Incineroar", "grass", "Intimidate", "Charcoal", [
      ["Fake Out", "normal"],
      ["Flare Blitz", "fire"],
      ["Throat Chop", "dark"],
      ["Parting Shot", "dark"],
    ]),
    mon("Politoed", "water", "Drizzle", "Choice Scarf", [
      ["Weather Ball", "normal"],
      ["Muddy Water", "water"],
      ["Ice Beam", "ice"],
      ["Icy Wind", "ice"],
    ]),
    mon("Sylveon", "fairy", "Pixilate", "Fairy Feather", [
      ["Hyper Voice", "normal"],
      ["Moonblast", "fairy"],
      ["Psych Up", "normal"],
      ["Protect", "normal"],
    ]),
  ];
}

export function sampleTeamB(): TeamMon[] {
  return [
    mon("Flutter Mane", "fairy", "Protosynthesis", "Booster Energy", [
      ["Moonblast", "fairy"],
      ["Shadow Ball", "ghost"],
      ["Icy Wind", "ice"],
      ["Protect", "normal"],
    ]),
    mon("Incineroar", "grass", "Intimidate", "Safety Goggles", [
      ["Fake Out", "normal"],
      ["Flare Blitz", "fire"],
      ["Knock Off", "dark"],
      ["Parting Shot", "dark"],
    ]),
    mon("Amoonguss", "water", "Regenerator", "Rocky Helmet", [
      ["Pollen Puff", "bug"],
      ["Rage Powder", "bug"],
      ["Spore", "grass"],
      ["Protect", "normal"],
    ]),
    mon("Raging Bolt", "electric", "Protosynthesis", "Assault Vest", [
      ["Thunderclap", "electric"],
      ["Dragon Pulse", "dragon"],
      ["Thunderbolt", "electric"],
      ["Snarl", "dark"],
    ]),
    mon("Urshifu Rapid", "water", "Unseen Fist", "Choice Scarf", [
      ["Surging Strikes", "water"],
      ["Close Combat", "fighting"],
      ["U-turn", "bug"],
      ["Aqua Jet", "water"],
    ]),
    mon("Farigiraf", "psychic", "Armor Tail", "Throat Spray", [
      ["Hyper Voice", "normal"],
      ["Psychic", "psychic"],
      ["Trick Room", "psychic"],
      ["Helping Hand", "normal"],
    ]),
  ];
}

function mon(
  name: string,
  tera: PokeType,
  ability: string,
  item: string,
  moves: Array<[string, PokeType]>,
): TeamMon {
  const species = findSpecies(name);
  return {
    species: name,
    dex: species ? speciesArtDex(species) : 0,
    types: [species?.types[0] ?? "", species?.types[1] ?? ""],
    tera,
    ability,
    item,
    moves: [0, 1, 2, 3].map((i) => ({
      name: moves[i]?.[0] ?? "",
      type: moves[i]?.[1] ?? "",
    })) as TeamMon["moves"],
  };
}

export function teamHasMons(team: TeamMon[] | undefined): boolean {
  return countFilledMons(team) > 0;
}

export function countFilledMons(team: TeamMon[] | undefined): number {
  return (team ?? []).filter((mon) => mon.species.trim()).length;
}
