/** Legends: Z-A / Mega Dimension formes not on the SV national list. */

export const ZA_FORMES = [
  {
    name: "Floette Eternal",
    slug: "floette-eternal",
    dex: 670,
    spriteDex: 10061,
    types: ["fairy"],
    abilities: ["Flower Veil", "Symbiosis", "Fairy Aura"],
  },
  {
    name: "Mega Floette",
    slug: "floette-mega",
    dex: 670,
    types: ["fairy"],
    abilities: ["Fairy Aura"],
  },
  {
    name: "Mega Meganium",
    slug: "meganium-mega",
    dex: 154,
    types: ["grass", "fairy"],
    abilities: ["Mega Sol"],
  },
  {
    name: "Mega Emboar",
    slug: "emboar-mega",
    dex: 500,
    types: ["fire", "fighting"],
    abilities: [],
  },
  {
    name: "Mega Feraligatr",
    slug: "feraligatr-mega",
    dex: 160,
    types: ["water", "dragon"],
    abilities: ["Dragonize"],
  },
  {
    name: "Mega Barbaracle",
    slug: "barbaracle-mega",
    dex: 689,
    types: ["rock", "fighting"],
    abilities: [],
  },
  {
    name: "Mega Starmie",
    slug: "starmie-mega",
    dex: 121,
    types: ["water", "psychic"],
    abilities: [],
  },
  {
    name: "Mega Pyroar",
    slug: "pyroar-mega",
    dex: 668,
    types: ["fire", "normal"],
    abilities: [],
  },
  {
    name: "Mega Clefable",
    slug: "clefable-mega",
    dex: 36,
    types: ["fairy", "flying"],
    abilities: [],
  },
  {
    name: "Mega Scolipede",
    slug: "scolipede-mega",
    dex: 545,
    types: ["bug", "poison"],
    abilities: [],
  },
  {
    name: "Mega Victreebel",
    slug: "victreebel-mega",
    dex: 71,
    types: ["grass", "poison"],
    abilities: [],
  },
  {
    name: "Mega Excadrill",
    slug: "excadrill-mega",
    dex: 530,
    types: ["ground", "steel"],
    abilities: ["Piercing Drill"],
  },
  {
    name: "Mega Eelektross",
    slug: "eelektross-mega",
    dex: 604,
    types: ["electric"],
    abilities: [],
  },
  {
    name: "Mega Dragonite",
    slug: "dragonite-mega",
    dex: 149,
    types: ["dragon", "flying"],
    abilities: ["Multiscale"],
  },
  {
    name: "Mega Malamar",
    slug: "malamar-mega",
    dex: 687,
    types: ["dark", "psychic"],
    abilities: [],
  },
  {
    name: "Mega Dragalge",
    slug: "dragalge-mega",
    dex: 691,
    types: ["poison", "dragon"],
    abilities: [],
  },
  {
    name: "Mega Froslass",
    slug: "froslass-mega",
    dex: 478,
    types: ["ice", "ghost"],
    abilities: [],
  },
  {
    name: "Mega Hawlucha",
    slug: "hawlucha-mega",
    dex: 701,
    types: ["fighting", "flying"],
    abilities: [],
  },
  {
    name: "Mega Scrafty",
    slug: "scrafty-mega",
    dex: 560,
    types: ["dark", "fighting"],
    abilities: [],
  },
  {
    name: "Mega Chandelure",
    slug: "chandelure-mega",
    dex: 609,
    types: ["ghost", "fire"],
    abilities: ["Infiltrator"],
  },
  {
    name: "Mega Greninja",
    slug: "greninja-mega",
    dex: 658,
    types: ["water", "dark"],
    abilities: [],
  },
  {
    name: "Mega Falinks",
    slug: "falinks-mega",
    dex: 870,
    types: ["fighting"],
    abilities: [],
  },
  {
    name: "Mega Chesnaught",
    slug: "chesnaught-mega",
    dex: 652,
    types: ["grass", "fighting"],
    abilities: [],
  },
  {
    name: "Mega Skarmory",
    slug: "skarmory-mega",
    dex: 227,
    types: ["steel", "flying"],
    abilities: [],
  },
  {
    name: "Mega Delphox",
    slug: "delphox-mega",
    dex: 655,
    types: ["fire", "psychic"],
    abilities: [],
  },
  {
    name: "Mega Drampa",
    slug: "drampa-mega",
    dex: 780,
    types: ["normal", "dragon"],
    abilities: [],
  },
  {
    name: "Mega Zygarde",
    slug: "zygarde-mega",
    dex: 718,
    types: ["dragon", "ground"],
    abilities: [],
  },
  {
    name: "Mega Raichu X",
    slug: "raichu-mega-x",
    dex: 26,
    types: ["electric"],
    abilities: ["Electric Surge"],
  },
  {
    name: "Mega Raichu Y",
    slug: "raichu-mega-y",
    dex: 26,
    types: ["electric"],
    abilities: [],
  },
  {
    name: "Mega Absol Z",
    slug: "absol-mega-z",
    dex: 359,
    types: ["dark", "ghost"],
    abilities: [],
  },
  {
    name: "Mega Lucario Z",
    slug: "lucario-mega-z",
    dex: 448,
    types: ["fighting", "steel"],
    abilities: ["Aura Guard"],
  },
  {
    name: "Mega Garchomp Z",
    slug: "garchomp-mega-z",
    dex: 445,
    types: ["dragon", "ground"],
    abilities: [],
  },
  {
    name: "Mega Meowstic",
    slug: "meowstic-mega",
    dex: 678,
    types: ["psychic"],
    abilities: [],
  },
  {
    name: "Mega Baxcalibur",
    slug: "baxcalibur-mega",
    dex: 998,
    types: ["dragon", "ice"],
    abilities: [],
  },
  {
    name: "Mega Chimecho",
    slug: "chimecho-mega",
    dex: 358,
    types: ["psychic"],
    abilities: [],
  },
  {
    name: "Mega Crabominable",
    slug: "crabominable-mega",
    dex: 740,
    types: ["fighting", "ice"],
    abilities: [],
  },
  {
    name: "Mega Darkrai",
    slug: "darkrai-mega",
    dex: 491,
    types: ["dark"],
    abilities: [],
  },
  {
    name: "Mega Glimmora",
    slug: "glimmora-mega",
    dex: 970,
    types: ["rock", "poison"],
    abilities: ["Adaptability"],
  },
  {
    name: "Mega Golisopod",
    slug: "golisopod-mega",
    dex: 768,
    types: ["bug", "water"],
    abilities: [],
  },
  {
    name: "Mega Golurk",
    slug: "golurk-mega",
    dex: 623,
    types: ["ground", "ghost"],
    abilities: [],
  },
  {
    name: "Mega Heatran",
    slug: "heatran-mega",
    dex: 485,
    types: ["fire", "steel"],
    abilities: [],
  },
  {
    name: "Mega Magearna",
    slug: "magearna-mega",
    dex: 801,
    types: ["steel", "fairy"],
    abilities: [],
  },
  {
    name: "Mega Scovillain",
    slug: "scovillain-mega",
    dex: 952,
    types: ["grass", "fire"],
    abilities: [],
  },
  {
    name: "Mega Staraptor",
    slug: "staraptor-mega",
    dex: 398,
    types: ["normal", "flying"],
    abilities: [],
  },
  {
    name: "Mega Tatsugiri",
    slug: "tatsugiri-mega",
    dex: 978,
    types: ["dragon", "water"],
    abilities: [],
  },
  {
    name: "Mega Zeraora",
    slug: "zeraora-mega",
    dex: 807,
    types: ["electric"],
    abilities: [],
  },
] as const;

export const ZA_MOVES: { name: string; type: "dragon" | "fairy" | "electric" | "fighting" | "fire" | "grass" | "water" | "psychic" | "dark" | "steel" | "ghost" | "normal" }[] = [
  { name: "Nihil Light", type: "dragon" },
];

export const ZA_ABILITY_FILL: Record<string, string[]> = {
  Flabébé: ["Flower Veil", "Symbiosis"],
  Floette: ["Flower Veil", "Symbiosis"],
  Florges: ["Flower Veil", "Symbiosis"],
};
