/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BrowserRouteImport } from './routes/browser'
import { Route as LoginRouteImport } from './routes/login'
import { Route as OverlayRouteRouteImport } from './routes/overlay/route'
import { Route as PodRouteImport } from './routes/pod'
import { Route as ProductionRouteImport } from './routes/production'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as TabletRouteImport } from './routes/tablet'
import { Route as TournamentRouteImport } from './routes/tournament'
import { Route as GameSignupRouteImport } from './routes/$game/signup'
import { Route as GameTabletRouteImport } from './routes/$game/tablet'
import { Route as ApiBrowserRouteImport } from './routes/api/browser'
import { Route as ApiDeskRouteImport } from './routes/api/desk'
import { Route as ApiHostInfoRouteImport } from './routes/api/host-info'
import { Route as ApiLorcanaCardsRouteImport } from './routes/api/lorcana-cards'
import { Route as ApiOpArtRouteImport } from './routes/api/op-art'
import { Route as ApiOpCardsRouteImport } from './routes/api/op-cards'
import { Route as ApiPtcgArtRouteImport } from './routes/api/ptcg-art'
import { Route as ApiPtcgCardsRouteImport } from './routes/api/ptcg-cards'
import { Route as ApiPtcgCatalogRouteImport } from './routes/api/ptcg-catalog'
import { Route as ApiPtcgDeckImportRouteImport } from './routes/api/ptcg-deck-import'
import { Route as ApiRiftCardsRouteImport } from './routes/api/rift-cards'
import { Route as ApiSwuCardsRouteImport } from './routes/api/swu-cards'
import { Route as ApiTournamentRouteImport } from './routes/api/tournament'
import { Route as ApiYgoCardsRouteImport } from './routes/api/ygo-cards'
import { Route as OverlayIndexRouteImport } from './routes/overlay/index'
import { Route as OverlayBracketRouteImport } from './routes/overlay/bracket'
import { Route as OverlayCardRouteImport } from './routes/overlay/card'
import { Route as OverlayCastersRouteImport } from './routes/overlay/casters'
import { Route as OverlayEventLogoRouteImport } from './routes/overlay/event-logo'
import { Route as OverlayFloorClockRouteImport } from './routes/overlay/floor-clock'
import { Route as OverlayGameWinRouteImport } from './routes/overlay/game-win'
import { Route as OverlayHudRouteImport } from './routes/overlay/hud'
import { Route as OverlayLowerThirdRouteImport } from './routes/overlay/lower-third'
import { Route as OverlayResourceRouteImport } from './routes/overlay/resource'
import { Route as OverlayRosterRouteImport } from './routes/overlay/roster'
import { Route as OverlayScorebugRouteImport } from './routes/overlay/scorebug'
import { Route as OverlaySlateRouteImport } from './routes/overlay/slate'
import { Route as OverlaySponsorsRouteImport } from './routes/overlay/sponsors'
import { Route as OverlayStreamClockRouteImport } from './routes/overlay/stream-clock'
import { Route as OverlayTimerRouteImport } from './routes/overlay/timer'
import { Route as OverlayUpcomingRouteImport } from './routes/overlay/upcoming'
import { Route as OverlayVersusRouteImport } from './routes/overlay/versus'
import { Route as OverlayWinnerRouteImport } from './routes/overlay/winner'
import { Route as PrintDeckListRouteImport } from './routes/print/deck-list'
import { Route as PrintTeamListRouteImport } from './routes/print/team-list'
import { Route as GameSlotTabletRouteImport } from './routes/$game/$slot/tablet'
import { Route as GameOverlaySourceRouteImport } from './routes/$game/overlay/$source'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiTournamentExportRouteImport } from './routes/api/tournament/export'
import { Route as ApiTournamentSignupRouteImport } from './routes/api/tournament/signup'
import { Route as ApiTournamentTdfRouteImport } from './routes/api/tournament/tdf'
import { Route as GameSlotOverlaySourceRouteImport } from './routes/$game/$slot/overlay/$source'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BrowserRoute = BrowserRouteImport.update({
  id: '/browser',
  path: '/browser',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const OverlayRouteRoute = OverlayRouteRouteImport.update({
  id: '/overlay',
  path: '/overlay',
  getParentRoute: () => rootRouteImport,
} as any)
const PodRoute = PodRouteImport.update({
  id: '/pod',
  path: '/pod',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductionRoute = ProductionRouteImport.update({
  id: '/production',
  path: '/production',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const TabletRoute = TabletRouteImport.update({
  id: '/tablet',
  path: '/tablet',
  getParentRoute: () => rootRouteImport,
} as any)
const TournamentRoute = TournamentRouteImport.update({
  id: '/tournament',
  path: '/tournament',
  getParentRoute: () => rootRouteImport,
} as any)
const GameSignupRoute = GameSignupRouteImport.update({
  id: '/$game/signup',
  path: '/$game/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const GameTabletRoute = GameTabletRouteImport.update({
  id: '/$game/tablet',
  path: '/$game/tablet',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBrowserRoute = ApiBrowserRouteImport.update({
  id: '/api/browser',
  path: '/api/browser',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDeskRoute = ApiDeskRouteImport.update({
  id: '/api/desk',
  path: '/api/desk',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHostInfoRoute = ApiHostInfoRouteImport.update({
  id: '/api/host-info',
  path: '/api/host-info',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLorcanaCardsRoute = ApiLorcanaCardsRouteImport.update({
  id: '/api/lorcana-cards',
  path: '/api/lorcana-cards',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOpArtRoute = ApiOpArtRouteImport.update({
  id: '/api/op-art',
  path: '/api/op-art',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOpCardsRoute = ApiOpCardsRouteImport.update({
  id: '/api/op-cards',
  path: '/api/op-cards',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPtcgArtRoute = ApiPtcgArtRouteImport.update({
  id: '/api/ptcg-art',
  path: '/api/ptcg-art',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPtcgCardsRoute = ApiPtcgCardsRouteImport.update({
  id: '/api/ptcg-cards',
  path: '/api/ptcg-cards',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPtcgCatalogRoute = ApiPtcgCatalogRouteImport.update({
  id: '/api/ptcg-catalog',
  path: '/api/ptcg-catalog',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPtcgDeckImportRoute = ApiPtcgDeckImportRouteImport.update({
  id: '/api/ptcg-deck-import',
  path: '/api/ptcg-deck-import',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRiftCardsRoute = ApiRiftCardsRouteImport.update({
  id: '/api/rift-cards',
  path: '/api/rift-cards',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSwuCardsRoute = ApiSwuCardsRouteImport.update({
  id: '/api/swu-cards',
  path: '/api/swu-cards',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTournamentRoute = ApiTournamentRouteImport.update({
  id: '/api/tournament',
  path: '/api/tournament',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiYgoCardsRoute = ApiYgoCardsRouteImport.update({
  id: '/api/ygo-cards',
  path: '/api/ygo-cards',
  getParentRoute: () => rootRouteImport,
} as any)
const OverlayIndexRoute = OverlayIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OverlayRouteRoute,
} as any)
const OverlayBracketRoute = OverlayBracketRouteImport.update({
  id: '/bracket',
  path: '/bracket',
  getParentRoute: () => OverlayRouteRoute,
} as any)
const OverlayCardRoute = OverlayCardRouteImport.update({
  id: '/card',
  path: '/card',
  getParentRoute: () => OverlayRouteRoute,
} as any)
const OverlayCastersRoute = OverlayCastersRouteImport.update({
  id: '/casters',
  path: '/casters',
  getParentRoute: () => OverlayRouteRoute,
} as any)
const OverlayEventLogoRoute = OverlayEventLogoRouteImport.update({
  id: '/event-logo',
  path: '/event-logo',
  getParentRoute: () => OverlayRouteRoute,
} as any)
const OverlayFloorClockRoute = OverlayFloorClockRouteImport.update({
  id: '/floor-clock',
  path: '/floor-clock',
  getParentRoute: () => OverlayRouteRoute,
} as any)
const OverlayGameWinRoute = OverlayGameWinRouteImport.update({
  id: '/game-win',
  path: '/game-win',
  getParentRoute: () => OverlayRouteRoute,
} as any)
const OverlayHudRoute = OverlayHudRouteImport.update({
  id: '/hud',
  path: '/hud',
  getParentRoute: () => OverlayRouteRoute,
} as any)
const OverlayLowerThirdRoute = OverlayLowerThirdRouteImport.update({
  id: '/lower-third',
  path: '/lower-third',
  getParentRoute: () => OverlayRouteRoute,
} as any)
const OverlayResourceRoute = OverlayResourceRouteImport.update({
  id: '/resource',
  path: '/resource',
  getParentRoute: () => OverlayRouteRoute,
} as any)
const OverlayRosterRoute = OverlayRosterRouteImport.update({
  id: '/roster',
  path: '/roster',
  getParentRoute: () => OverlayRouteRoute,
} as any)
const OverlayScorebugRoute = OverlayScorebugRouteImport.update({
  id: '/scorebug',
  path: '/scorebug',
  getParentRoute: () => OverlayRouteRoute,
} as any)
const OverlaySlateRoute = OverlaySlateRouteImport.update({
  id: '/slate',
  path: '/slate',
  getParentRoute: () => OverlayRouteRoute,
} as any)
const OverlaySponsorsRoute = OverlaySponsorsRouteImport.update({
  id: '/sponsors',
  path: '/sponsors',
  getParentRoute: () => OverlayRouteRoute,
} as any)
const OverlayStreamClockRoute = OverlayStreamClockRouteImport.update({
  id: '/stream-clock',
  path: '/stream-clock',
  getParentRoute: () => OverlayRouteRoute,
} as any)
const OverlayTimerRoute = OverlayTimerRouteImport.update({
  id: '/timer',
  path: '/timer',
  getParentRoute: () => OverlayRouteRoute,
} as any)
const OverlayUpcomingRoute = OverlayUpcomingRouteImport.update({
  id: '/upcoming',
  path: '/upcoming',
  getParentRoute: () => OverlayRouteRoute,
} as any)
const OverlayVersusRoute = OverlayVersusRouteImport.update({
  id: '/versus',
  path: '/versus',
  getParentRoute: () => OverlayRouteRoute,
} as any)
const OverlayWinnerRoute = OverlayWinnerRouteImport.update({
  id: '/winner',
  path: '/winner',
  getParentRoute: () => OverlayRouteRoute,
} as any)
const PrintDeckListRoute = PrintDeckListRouteImport.update({
  id: '/print/deck-list',
  path: '/print/deck-list',
  getParentRoute: () => rootRouteImport,
} as any)
const PrintTeamListRoute = PrintTeamListRouteImport.update({
  id: '/print/team-list',
  path: '/print/team-list',
  getParentRoute: () => rootRouteImport,
} as any)
const GameSlotTabletRoute = GameSlotTabletRouteImport.update({
  id: '/$game/$slot/tablet',
  path: '/$game/$slot/tablet',
  getParentRoute: () => rootRouteImport,
} as any)
const GameOverlaySourceRoute = GameOverlaySourceRouteImport.update({
  id: '/$game/overlay/$source',
  path: '/$game/overlay/$source',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTournamentExportRoute = ApiTournamentExportRouteImport.update({
  id: '/export',
  path: '/export',
  getParentRoute: () => ApiTournamentRoute,
} as any)
const ApiTournamentSignupRoute = ApiTournamentSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => ApiTournamentRoute,
} as any)
const ApiTournamentTdfRoute = ApiTournamentTdfRouteImport.update({
  id: '/tdf',
  path: '/tdf',
  getParentRoute: () => ApiTournamentRoute,
} as any)
const GameSlotOverlaySourceRoute = GameSlotOverlaySourceRouteImport.update({
  id: '/$game/$slot/overlay/$source',
  path: '/$game/$slot/overlay/$source',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/overlay': typeof OverlayRouteRouteWithChildren
  '/browser': typeof BrowserRoute
  '/login': typeof LoginRoute
  '/pod': typeof PodRoute
  '/production': typeof ProductionRoute
  '/signup': typeof SignupRoute
  '/tablet': typeof TabletRoute
  '/tournament': typeof TournamentRoute
  '/$game/signup': typeof GameSignupRoute
  '/$game/tablet': typeof GameTabletRoute
  '/api/browser': typeof ApiBrowserRoute
  '/api/desk': typeof ApiDeskRoute
  '/api/host-info': typeof ApiHostInfoRoute
  '/api/lorcana-cards': typeof ApiLorcanaCardsRoute
  '/api/op-art': typeof ApiOpArtRoute
  '/api/op-cards': typeof ApiOpCardsRoute
  '/api/ptcg-art': typeof ApiPtcgArtRoute
  '/api/ptcg-cards': typeof ApiPtcgCardsRoute
  '/api/ptcg-catalog': typeof ApiPtcgCatalogRoute
  '/api/ptcg-deck-import': typeof ApiPtcgDeckImportRoute
  '/api/rift-cards': typeof ApiRiftCardsRoute
  '/api/swu-cards': typeof ApiSwuCardsRoute
  '/api/tournament': typeof ApiTournamentRouteWithChildren
  '/api/ygo-cards': typeof ApiYgoCardsRoute
  '/overlay/bracket': typeof OverlayBracketRoute
  '/overlay/card': typeof OverlayCardRoute
  '/overlay/casters': typeof OverlayCastersRoute
  '/overlay/event-logo': typeof OverlayEventLogoRoute
  '/overlay/floor-clock': typeof OverlayFloorClockRoute
  '/overlay/game-win': typeof OverlayGameWinRoute
  '/overlay/hud': typeof OverlayHudRoute
  '/overlay/lower-third': typeof OverlayLowerThirdRoute
  '/overlay/resource': typeof OverlayResourceRoute
  '/overlay/roster': typeof OverlayRosterRoute
  '/overlay/scorebug': typeof OverlayScorebugRoute
  '/overlay/slate': typeof OverlaySlateRoute
  '/overlay/sponsors': typeof OverlaySponsorsRoute
  '/overlay/stream-clock': typeof OverlayStreamClockRoute
  '/overlay/timer': typeof OverlayTimerRoute
  '/overlay/upcoming': typeof OverlayUpcomingRoute
  '/overlay/versus': typeof OverlayVersusRoute
  '/overlay/winner': typeof OverlayWinnerRoute
  '/print/deck-list': typeof PrintDeckListRoute
  '/print/team-list': typeof PrintTeamListRoute
  '/overlay/': typeof OverlayIndexRoute
  '/$game/$slot/tablet': typeof GameSlotTabletRoute
  '/$game/overlay/$source': typeof GameOverlaySourceRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/tournament/export': typeof ApiTournamentExportRoute
  '/api/tournament/signup': typeof ApiTournamentSignupRoute
  '/api/tournament/tdf': typeof ApiTournamentTdfRoute
  '/$game/$slot/overlay/$source': typeof GameSlotOverlaySourceRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/browser': typeof BrowserRoute
  '/login': typeof LoginRoute
  '/pod': typeof PodRoute
  '/production': typeof ProductionRoute
  '/signup': typeof SignupRoute
  '/tablet': typeof TabletRoute
  '/tournament': typeof TournamentRoute
  '/$game/signup': typeof GameSignupRoute
  '/$game/tablet': typeof GameTabletRoute
  '/api/browser': typeof ApiBrowserRoute
  '/api/desk': typeof ApiDeskRoute
  '/api/host-info': typeof ApiHostInfoRoute
  '/api/lorcana-cards': typeof ApiLorcanaCardsRoute
  '/api/op-art': typeof ApiOpArtRoute
  '/api/op-cards': typeof ApiOpCardsRoute
  '/api/ptcg-art': typeof ApiPtcgArtRoute
  '/api/ptcg-cards': typeof ApiPtcgCardsRoute
  '/api/ptcg-catalog': typeof ApiPtcgCatalogRoute
  '/api/ptcg-deck-import': typeof ApiPtcgDeckImportRoute
  '/api/rift-cards': typeof ApiRiftCardsRoute
  '/api/swu-cards': typeof ApiSwuCardsRoute
  '/api/tournament': typeof ApiTournamentRouteWithChildren
  '/api/ygo-cards': typeof ApiYgoCardsRoute
  '/overlay/bracket': typeof OverlayBracketRoute
  '/overlay/card': typeof OverlayCardRoute
  '/overlay/casters': typeof OverlayCastersRoute
  '/overlay/event-logo': typeof OverlayEventLogoRoute
  '/overlay/floor-clock': typeof OverlayFloorClockRoute
  '/overlay/game-win': typeof OverlayGameWinRoute
  '/overlay/hud': typeof OverlayHudRoute
  '/overlay/lower-third': typeof OverlayLowerThirdRoute
  '/overlay/resource': typeof OverlayResourceRoute
  '/overlay/roster': typeof OverlayRosterRoute
  '/overlay/scorebug': typeof OverlayScorebugRoute
  '/overlay/slate': typeof OverlaySlateRoute
  '/overlay/sponsors': typeof OverlaySponsorsRoute
  '/overlay/stream-clock': typeof OverlayStreamClockRoute
  '/overlay/timer': typeof OverlayTimerRoute
  '/overlay/upcoming': typeof OverlayUpcomingRoute
  '/overlay/versus': typeof OverlayVersusRoute
  '/overlay/winner': typeof OverlayWinnerRoute
  '/print/deck-list': typeof PrintDeckListRoute
  '/print/team-list': typeof PrintTeamListRoute
  '/overlay': typeof OverlayIndexRoute
  '/$game/$slot/tablet': typeof GameSlotTabletRoute
  '/$game/overlay/$source': typeof GameOverlaySourceRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/tournament/export': typeof ApiTournamentExportRoute
  '/api/tournament/signup': typeof ApiTournamentSignupRoute
  '/api/tournament/tdf': typeof ApiTournamentTdfRoute
  '/$game/$slot/overlay/$source': typeof GameSlotOverlaySourceRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/overlay': typeof OverlayRouteRouteWithChildren
  '/browser': typeof BrowserRoute
  '/login': typeof LoginRoute
  '/pod': typeof PodRoute
  '/production': typeof ProductionRoute
  '/signup': typeof SignupRoute
  '/tablet': typeof TabletRoute
  '/tournament': typeof TournamentRoute
  '/$game/signup': typeof GameSignupRoute
  '/$game/tablet': typeof GameTabletRoute
  '/api/browser': typeof ApiBrowserRoute
  '/api/desk': typeof ApiDeskRoute
  '/api/host-info': typeof ApiHostInfoRoute
  '/api/lorcana-cards': typeof ApiLorcanaCardsRoute
  '/api/op-art': typeof ApiOpArtRoute
  '/api/op-cards': typeof ApiOpCardsRoute
  '/api/ptcg-art': typeof ApiPtcgArtRoute
  '/api/ptcg-cards': typeof ApiPtcgCardsRoute
  '/api/ptcg-catalog': typeof ApiPtcgCatalogRoute
  '/api/ptcg-deck-import': typeof ApiPtcgDeckImportRoute
  '/api/rift-cards': typeof ApiRiftCardsRoute
  '/api/swu-cards': typeof ApiSwuCardsRoute
  '/api/tournament': typeof ApiTournamentRouteWithChildren
  '/api/ygo-cards': typeof ApiYgoCardsRoute
  '/overlay/bracket': typeof OverlayBracketRoute
  '/overlay/card': typeof OverlayCardRoute
  '/overlay/casters': typeof OverlayCastersRoute
  '/overlay/event-logo': typeof OverlayEventLogoRoute
  '/overlay/floor-clock': typeof OverlayFloorClockRoute
  '/overlay/game-win': typeof OverlayGameWinRoute
  '/overlay/hud': typeof OverlayHudRoute
  '/overlay/lower-third': typeof OverlayLowerThirdRoute
  '/overlay/resource': typeof OverlayResourceRoute
  '/overlay/roster': typeof OverlayRosterRoute
  '/overlay/scorebug': typeof OverlayScorebugRoute
  '/overlay/slate': typeof OverlaySlateRoute
  '/overlay/sponsors': typeof OverlaySponsorsRoute
  '/overlay/stream-clock': typeof OverlayStreamClockRoute
  '/overlay/timer': typeof OverlayTimerRoute
  '/overlay/upcoming': typeof OverlayUpcomingRoute
  '/overlay/versus': typeof OverlayVersusRoute
  '/overlay/winner': typeof OverlayWinnerRoute
  '/print/deck-list': typeof PrintDeckListRoute
  '/print/team-list': typeof PrintTeamListRoute
  '/overlay/': typeof OverlayIndexRoute
  '/$game/$slot/tablet': typeof GameSlotTabletRoute
  '/$game/overlay/$source': typeof GameOverlaySourceRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/tournament/export': typeof ApiTournamentExportRoute
  '/api/tournament/signup': typeof ApiTournamentSignupRoute
  '/api/tournament/tdf': typeof ApiTournamentTdfRoute
  '/$game/$slot/overlay/$source': typeof GameSlotOverlaySourceRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/overlay'
    | '/browser'
    | '/login'
    | '/pod'
    | '/production'
    | '/signup'
    | '/tablet'
    | '/tournament'
    | '/$game/signup'
    | '/$game/tablet'
    | '/api/browser'
    | '/api/desk'
    | '/api/host-info'
    | '/api/lorcana-cards'
    | '/api/op-art'
    | '/api/op-cards'
    | '/api/ptcg-art'
    | '/api/ptcg-cards'
    | '/api/ptcg-catalog'
    | '/api/ptcg-deck-import'
    | '/api/rift-cards'
    | '/api/swu-cards'
    | '/api/tournament'
    | '/api/ygo-cards'
    | '/overlay/bracket'
    | '/overlay/card'
    | '/overlay/casters'
    | '/overlay/event-logo'
    | '/overlay/floor-clock'
    | '/overlay/game-win'
    | '/overlay/hud'
    | '/overlay/lower-third'
    | '/overlay/resource'
    | '/overlay/roster'
    | '/overlay/scorebug'
    | '/overlay/slate'
    | '/overlay/sponsors'
    | '/overlay/stream-clock'
    | '/overlay/timer'
    | '/overlay/upcoming'
    | '/overlay/versus'
    | '/overlay/winner'
    | '/print/deck-list'
    | '/print/team-list'
    | '/overlay/'
    | '/$game/$slot/tablet'
    | '/$game/overlay/$source'
    | '/api/auth/$'
    | '/api/tournament/export'
    | '/api/tournament/signup'
    | '/api/tournament/tdf'
    | '/$game/$slot/overlay/$source'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/browser'
    | '/login'
    | '/pod'
    | '/production'
    | '/signup'
    | '/tablet'
    | '/tournament'
    | '/$game/signup'
    | '/$game/tablet'
    | '/api/browser'
    | '/api/desk'
    | '/api/host-info'
    | '/api/lorcana-cards'
    | '/api/op-art'
    | '/api/op-cards'
    | '/api/ptcg-art'
    | '/api/ptcg-cards'
    | '/api/ptcg-catalog'
    | '/api/ptcg-deck-import'
    | '/api/rift-cards'
    | '/api/swu-cards'
    | '/api/tournament'
    | '/api/ygo-cards'
    | '/overlay/bracket'
    | '/overlay/card'
    | '/overlay/casters'
    | '/overlay/event-logo'
    | '/overlay/floor-clock'
    | '/overlay/game-win'
    | '/overlay/hud'
    | '/overlay/lower-third'
    | '/overlay/resource'
    | '/overlay/roster'
    | '/overlay/scorebug'
    | '/overlay/slate'
    | '/overlay/sponsors'
    | '/overlay/stream-clock'
    | '/overlay/timer'
    | '/overlay/upcoming'
    | '/overlay/versus'
    | '/overlay/winner'
    | '/print/deck-list'
    | '/print/team-list'
    | '/overlay'
    | '/$game/$slot/tablet'
    | '/$game/overlay/$source'
    | '/api/auth/$'
    | '/api/tournament/export'
    | '/api/tournament/signup'
    | '/api/tournament/tdf'
    | '/$game/$slot/overlay/$source'
  id:
    | '__root__'
    | '/'
    | '/overlay'
    | '/browser'
    | '/login'
    | '/pod'
    | '/production'
    | '/signup'
    | '/tablet'
    | '/tournament'
    | '/$game/signup'
    | '/$game/tablet'
    | '/api/browser'
    | '/api/desk'
    | '/api/host-info'
    | '/api/lorcana-cards'
    | '/api/op-art'
    | '/api/op-cards'
    | '/api/ptcg-art'
    | '/api/ptcg-cards'
    | '/api/ptcg-catalog'
    | '/api/ptcg-deck-import'
    | '/api/rift-cards'
    | '/api/swu-cards'
    | '/api/tournament'
    | '/api/ygo-cards'
    | '/overlay/bracket'
    | '/overlay/card'
    | '/overlay/casters'
    | '/overlay/event-logo'
    | '/overlay/floor-clock'
    | '/overlay/game-win'
    | '/overlay/hud'
    | '/overlay/lower-third'
    | '/overlay/resource'
    | '/overlay/roster'
    | '/overlay/scorebug'
    | '/overlay/slate'
    | '/overlay/sponsors'
    | '/overlay/stream-clock'
    | '/overlay/timer'
    | '/overlay/upcoming'
    | '/overlay/versus'
    | '/overlay/winner'
    | '/print/deck-list'
    | '/print/team-list'
    | '/overlay/'
    | '/$game/$slot/tablet'
    | '/$game/overlay/$source'
    | '/api/auth/$'
    | '/api/tournament/export'
    | '/api/tournament/signup'
    | '/api/tournament/tdf'
    | '/$game/$slot/overlay/$source'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  OverlayRouteRoute: typeof OverlayRouteRouteWithChildren
  BrowserRoute: typeof BrowserRoute
  LoginRoute: typeof LoginRoute
  PodRoute: typeof PodRoute
  ProductionRoute: typeof ProductionRoute
  SignupRoute: typeof SignupRoute
  TabletRoute: typeof TabletRoute
  TournamentRoute: typeof TournamentRoute
  GameSignupRoute: typeof GameSignupRoute
  GameTabletRoute: typeof GameTabletRoute
  ApiBrowserRoute: typeof ApiBrowserRoute
  ApiDeskRoute: typeof ApiDeskRoute
  ApiHostInfoRoute: typeof ApiHostInfoRoute
  ApiLorcanaCardsRoute: typeof ApiLorcanaCardsRoute
  ApiOpArtRoute: typeof ApiOpArtRoute
  ApiOpCardsRoute: typeof ApiOpCardsRoute
  ApiPtcgArtRoute: typeof ApiPtcgArtRoute
  ApiPtcgCardsRoute: typeof ApiPtcgCardsRoute
  ApiPtcgCatalogRoute: typeof ApiPtcgCatalogRoute
  ApiPtcgDeckImportRoute: typeof ApiPtcgDeckImportRoute
  ApiRiftCardsRoute: typeof ApiRiftCardsRoute
  ApiSwuCardsRoute: typeof ApiSwuCardsRoute
  ApiTournamentRoute: typeof ApiTournamentRouteWithChildren
  ApiYgoCardsRoute: typeof ApiYgoCardsRoute
  PrintDeckListRoute: typeof PrintDeckListRoute
  PrintTeamListRoute: typeof PrintTeamListRoute
  GameSlotTabletRoute: typeof GameSlotTabletRoute
  GameOverlaySourceRoute: typeof GameOverlaySourceRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  GameSlotOverlaySourceRoute: typeof GameSlotOverlaySourceRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/browser': {
      id: '/browser'
      path: '/browser'
      fullPath: '/browser'
      preLoaderRoute: typeof BrowserRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/overlay': {
      id: '/overlay'
      path: '/overlay'
      fullPath: '/overlay'
      preLoaderRoute: typeof OverlayRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pod': {
      id: '/pod'
      path: '/pod'
      fullPath: '/pod'
      preLoaderRoute: typeof PodRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/production': {
      id: '/production'
      path: '/production'
      fullPath: '/production'
      preLoaderRoute: typeof ProductionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tablet': {
      id: '/tablet'
      path: '/tablet'
      fullPath: '/tablet'
      preLoaderRoute: typeof TabletRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tournament': {
      id: '/tournament'
      path: '/tournament'
      fullPath: '/tournament'
      preLoaderRoute: typeof TournamentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$game/signup': {
      id: '/$game/signup'
      path: '/$game/signup'
      fullPath: '/$game/signup'
      preLoaderRoute: typeof GameSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$game/tablet': {
      id: '/$game/tablet'
      path: '/$game/tablet'
      fullPath: '/$game/tablet'
      preLoaderRoute: typeof GameTabletRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/browser': {
      id: '/api/browser'
      path: '/api/browser'
      fullPath: '/api/browser'
      preLoaderRoute: typeof ApiBrowserRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/desk': {
      id: '/api/desk'
      path: '/api/desk'
      fullPath: '/api/desk'
      preLoaderRoute: typeof ApiDeskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/host-info': {
      id: '/api/host-info'
      path: '/api/host-info'
      fullPath: '/api/host-info'
      preLoaderRoute: typeof ApiHostInfoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/lorcana-cards': {
      id: '/api/lorcana-cards'
      path: '/api/lorcana-cards'
      fullPath: '/api/lorcana-cards'
      preLoaderRoute: typeof ApiLorcanaCardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/op-art': {
      id: '/api/op-art'
      path: '/api/op-art'
      fullPath: '/api/op-art'
      preLoaderRoute: typeof ApiOpArtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/op-cards': {
      id: '/api/op-cards'
      path: '/api/op-cards'
      fullPath: '/api/op-cards'
      preLoaderRoute: typeof ApiOpCardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ptcg-art': {
      id: '/api/ptcg-art'
      path: '/api/ptcg-art'
      fullPath: '/api/ptcg-art'
      preLoaderRoute: typeof ApiPtcgArtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ptcg-cards': {
      id: '/api/ptcg-cards'
      path: '/api/ptcg-cards'
      fullPath: '/api/ptcg-cards'
      preLoaderRoute: typeof ApiPtcgCardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ptcg-catalog': {
      id: '/api/ptcg-catalog'
      path: '/api/ptcg-catalog'
      fullPath: '/api/ptcg-catalog'
      preLoaderRoute: typeof ApiPtcgCatalogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ptcg-deck-import': {
      id: '/api/ptcg-deck-import'
      path: '/api/ptcg-deck-import'
      fullPath: '/api/ptcg-deck-import'
      preLoaderRoute: typeof ApiPtcgDeckImportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/rift-cards': {
      id: '/api/rift-cards'
      path: '/api/rift-cards'
      fullPath: '/api/rift-cards'
      preLoaderRoute: typeof ApiRiftCardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/swu-cards': {
      id: '/api/swu-cards'
      path: '/api/swu-cards'
      fullPath: '/api/swu-cards'
      preLoaderRoute: typeof ApiSwuCardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tournament': {
      id: '/api/tournament'
      path: '/api/tournament'
      fullPath: '/api/tournament'
      preLoaderRoute: typeof ApiTournamentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ygo-cards': {
      id: '/api/ygo-cards'
      path: '/api/ygo-cards'
      fullPath: '/api/ygo-cards'
      preLoaderRoute: typeof ApiYgoCardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/overlay/': {
      id: '/overlay/'
      path: '/'
      fullPath: '/overlay/'
      preLoaderRoute: typeof OverlayIndexRouteImport
      parentRoute: typeof OverlayRouteRoute
    }
    '/overlay/bracket': {
      id: '/overlay/bracket'
      path: '/bracket'
      fullPath: '/overlay/bracket'
      preLoaderRoute: typeof OverlayBracketRouteImport
      parentRoute: typeof OverlayRouteRoute
    }
    '/overlay/card': {
      id: '/overlay/card'
      path: '/card'
      fullPath: '/overlay/card'
      preLoaderRoute: typeof OverlayCardRouteImport
      parentRoute: typeof OverlayRouteRoute
    }
    '/overlay/casters': {
      id: '/overlay/casters'
      path: '/casters'
      fullPath: '/overlay/casters'
      preLoaderRoute: typeof OverlayCastersRouteImport
      parentRoute: typeof OverlayRouteRoute
    }
    '/overlay/event-logo': {
      id: '/overlay/event-logo'
      path: '/event-logo'
      fullPath: '/overlay/event-logo'
      preLoaderRoute: typeof OverlayEventLogoRouteImport
      parentRoute: typeof OverlayRouteRoute
    }
    '/overlay/floor-clock': {
      id: '/overlay/floor-clock'
      path: '/floor-clock'
      fullPath: '/overlay/floor-clock'
      preLoaderRoute: typeof OverlayFloorClockRouteImport
      parentRoute: typeof OverlayRouteRoute
    }
    '/overlay/game-win': {
      id: '/overlay/game-win'
      path: '/game-win'
      fullPath: '/overlay/game-win'
      preLoaderRoute: typeof OverlayGameWinRouteImport
      parentRoute: typeof OverlayRouteRoute
    }
    '/overlay/hud': {
      id: '/overlay/hud'
      path: '/hud'
      fullPath: '/overlay/hud'
      preLoaderRoute: typeof OverlayHudRouteImport
      parentRoute: typeof OverlayRouteRoute
    }
    '/overlay/lower-third': {
      id: '/overlay/lower-third'
      path: '/lower-third'
      fullPath: '/overlay/lower-third'
      preLoaderRoute: typeof OverlayLowerThirdRouteImport
      parentRoute: typeof OverlayRouteRoute
    }
    '/overlay/resource': {
      id: '/overlay/resource'
      path: '/resource'
      fullPath: '/overlay/resource'
      preLoaderRoute: typeof OverlayResourceRouteImport
      parentRoute: typeof OverlayRouteRoute
    }
    '/overlay/roster': {
      id: '/overlay/roster'
      path: '/roster'
      fullPath: '/overlay/roster'
      preLoaderRoute: typeof OverlayRosterRouteImport
      parentRoute: typeof OverlayRouteRoute
    }
    '/overlay/scorebug': {
      id: '/overlay/scorebug'
      path: '/scorebug'
      fullPath: '/overlay/scorebug'
      preLoaderRoute: typeof OverlayScorebugRouteImport
      parentRoute: typeof OverlayRouteRoute
    }
    '/overlay/slate': {
      id: '/overlay/slate'
      path: '/slate'
      fullPath: '/overlay/slate'
      preLoaderRoute: typeof OverlaySlateRouteImport
      parentRoute: typeof OverlayRouteRoute
    }
    '/overlay/sponsors': {
      id: '/overlay/sponsors'
      path: '/sponsors'
      fullPath: '/overlay/sponsors'
      preLoaderRoute: typeof OverlaySponsorsRouteImport
      parentRoute: typeof OverlayRouteRoute
    }
    '/overlay/stream-clock': {
      id: '/overlay/stream-clock'
      path: '/stream-clock'
      fullPath: '/overlay/stream-clock'
      preLoaderRoute: typeof OverlayStreamClockRouteImport
      parentRoute: typeof OverlayRouteRoute
    }
    '/overlay/timer': {
      id: '/overlay/timer'
      path: '/timer'
      fullPath: '/overlay/timer'
      preLoaderRoute: typeof OverlayTimerRouteImport
      parentRoute: typeof OverlayRouteRoute
    }
    '/overlay/upcoming': {
      id: '/overlay/upcoming'
      path: '/upcoming'
      fullPath: '/overlay/upcoming'
      preLoaderRoute: typeof OverlayUpcomingRouteImport
      parentRoute: typeof OverlayRouteRoute
    }
    '/overlay/versus': {
      id: '/overlay/versus'
      path: '/versus'
      fullPath: '/overlay/versus'
      preLoaderRoute: typeof OverlayVersusRouteImport
      parentRoute: typeof OverlayRouteRoute
    }
    '/overlay/winner': {
      id: '/overlay/winner'
      path: '/winner'
      fullPath: '/overlay/winner'
      preLoaderRoute: typeof OverlayWinnerRouteImport
      parentRoute: typeof OverlayRouteRoute
    }
    '/print/deck-list': {
      id: '/print/deck-list'
      path: '/print/deck-list'
      fullPath: '/print/deck-list'
      preLoaderRoute: typeof PrintDeckListRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/print/team-list': {
      id: '/print/team-list'
      path: '/print/team-list'
      fullPath: '/print/team-list'
      preLoaderRoute: typeof PrintTeamListRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$game/$slot/tablet': {
      id: '/$game/$slot/tablet'
      path: '/$game/$slot/tablet'
      fullPath: '/$game/$slot/tablet'
      preLoaderRoute: typeof GameSlotTabletRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$game/overlay/$source': {
      id: '/$game/overlay/$source'
      path: '/$game/overlay/$source'
      fullPath: '/$game/overlay/$source'
      preLoaderRoute: typeof GameOverlaySourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tournament/export': {
      id: '/api/tournament/export'
      path: '/export'
      fullPath: '/api/tournament/export'
      preLoaderRoute: typeof ApiTournamentExportRouteImport
      parentRoute: typeof ApiTournamentRoute
    }
    '/api/tournament/signup': {
      id: '/api/tournament/signup'
      path: '/signup'
      fullPath: '/api/tournament/signup'
      preLoaderRoute: typeof ApiTournamentSignupRouteImport
      parentRoute: typeof ApiTournamentRoute
    }
    '/api/tournament/tdf': {
      id: '/api/tournament/tdf'
      path: '/tdf'
      fullPath: '/api/tournament/tdf'
      preLoaderRoute: typeof ApiTournamentTdfRouteImport
      parentRoute: typeof ApiTournamentRoute
    }
    '/$game/$slot/overlay/$source': {
      id: '/$game/$slot/overlay/$source'
      path: '/$game/$slot/overlay/$source'
      fullPath: '/$game/$slot/overlay/$source'
      preLoaderRoute: typeof GameSlotOverlaySourceRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface OverlayRouteRouteChildren {
  OverlayBracketRoute: typeof OverlayBracketRoute
  OverlayCardRoute: typeof OverlayCardRoute
  OverlayCastersRoute: typeof OverlayCastersRoute
  OverlayEventLogoRoute: typeof OverlayEventLogoRoute
  OverlayFloorClockRoute: typeof OverlayFloorClockRoute
  OverlayGameWinRoute: typeof OverlayGameWinRoute
  OverlayHudRoute: typeof OverlayHudRoute
  OverlayLowerThirdRoute: typeof OverlayLowerThirdRoute
  OverlayResourceRoute: typeof OverlayResourceRoute
  OverlayRosterRoute: typeof OverlayRosterRoute
  OverlayScorebugRoute: typeof OverlayScorebugRoute
  OverlaySlateRoute: typeof OverlaySlateRoute
  OverlaySponsorsRoute: typeof OverlaySponsorsRoute
  OverlayStreamClockRoute: typeof OverlayStreamClockRoute
  OverlayTimerRoute: typeof OverlayTimerRoute
  OverlayUpcomingRoute: typeof OverlayUpcomingRoute
  OverlayVersusRoute: typeof OverlayVersusRoute
  OverlayWinnerRoute: typeof OverlayWinnerRoute
  OverlayIndexRoute: typeof OverlayIndexRoute
}

const OverlayRouteRouteChildren: OverlayRouteRouteChildren = {
  OverlayBracketRoute: OverlayBracketRoute,
  OverlayCardRoute: OverlayCardRoute,
  OverlayCastersRoute: OverlayCastersRoute,
  OverlayEventLogoRoute: OverlayEventLogoRoute,
  OverlayFloorClockRoute: OverlayFloorClockRoute,
  OverlayGameWinRoute: OverlayGameWinRoute,
  OverlayHudRoute: OverlayHudRoute,
  OverlayLowerThirdRoute: OverlayLowerThirdRoute,
  OverlayResourceRoute: OverlayResourceRoute,
  OverlayRosterRoute: OverlayRosterRoute,
  OverlayScorebugRoute: OverlayScorebugRoute,
  OverlaySlateRoute: OverlaySlateRoute,
  OverlaySponsorsRoute: OverlaySponsorsRoute,
  OverlayStreamClockRoute: OverlayStreamClockRoute,
  OverlayTimerRoute: OverlayTimerRoute,
  OverlayUpcomingRoute: OverlayUpcomingRoute,
  OverlayVersusRoute: OverlayVersusRoute,
  OverlayWinnerRoute: OverlayWinnerRoute,
  OverlayIndexRoute: OverlayIndexRoute,
}

const OverlayRouteRouteWithChildren = OverlayRouteRoute._addFileChildren(
  OverlayRouteRouteChildren,
)

interface ApiTournamentRouteChildren {
  ApiTournamentExportRoute: typeof ApiTournamentExportRoute
  ApiTournamentSignupRoute: typeof ApiTournamentSignupRoute
  ApiTournamentTdfRoute: typeof ApiTournamentTdfRoute
}

const ApiTournamentRouteChildren: ApiTournamentRouteChildren = {
  ApiTournamentExportRoute: ApiTournamentExportRoute,
  ApiTournamentSignupRoute: ApiTournamentSignupRoute,
  ApiTournamentTdfRoute: ApiTournamentTdfRoute,
}

const ApiTournamentRouteWithChildren = ApiTournamentRoute._addFileChildren(
  ApiTournamentRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  OverlayRouteRoute: OverlayRouteRouteWithChildren,
  BrowserRoute: BrowserRoute,
  LoginRoute: LoginRoute,
  PodRoute: PodRoute,
  ProductionRoute: ProductionRoute,
  SignupRoute: SignupRoute,
  TabletRoute: TabletRoute,
  TournamentRoute: TournamentRoute,
  GameSignupRoute: GameSignupRoute,
  GameTabletRoute: GameTabletRoute,
  ApiBrowserRoute: ApiBrowserRoute,
  ApiDeskRoute: ApiDeskRoute,
  ApiHostInfoRoute: ApiHostInfoRoute,
  ApiLorcanaCardsRoute: ApiLorcanaCardsRoute,
  ApiOpArtRoute: ApiOpArtRoute,
  ApiOpCardsRoute: ApiOpCardsRoute,
  ApiPtcgArtRoute: ApiPtcgArtRoute,
  ApiPtcgCardsRoute: ApiPtcgCardsRoute,
  ApiPtcgCatalogRoute: ApiPtcgCatalogRoute,
  ApiPtcgDeckImportRoute: ApiPtcgDeckImportRoute,
  ApiRiftCardsRoute: ApiRiftCardsRoute,
  ApiSwuCardsRoute: ApiSwuCardsRoute,
  ApiTournamentRoute: ApiTournamentRouteWithChildren,
  ApiYgoCardsRoute: ApiYgoCardsRoute,
  PrintDeckListRoute: PrintDeckListRoute,
  PrintTeamListRoute: PrintTeamListRoute,
  GameSlotTabletRoute: GameSlotTabletRoute,
  GameOverlaySourceRoute: GameOverlaySourceRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  GameSlotOverlaySourceRoute: GameSlotOverlaySourceRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
